---
permalink: audit/common-elements-in-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message, common elements, AMID, ANID, ASES, ASQN, ATID, ATIM, ATYP, AVER, RSLT 
summary: 所有稽核訊息都包含通用元素。 
---
= 稽核訊息中的一般元素
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所有稽核訊息都包含通用元素。

[cols="1a,1a,4a"]
|===
| 程式碼 | 類型 | 說明 


 a| 
在
 a| 
FC32
 a| 
模組 ID ：產生訊息之模組 ID 的四個字元識別碼。這表示產生稽核訊息的程式碼區段。



 a| 
ANID
 a| 
UI32
 a| 
節點ID：指派給產生訊息之服務的網格節點ID。每項服務在StorageGRID 設定和安裝完整套系統時、都會分配一個唯一的識別碼。此 ID 無法變更。



 a| 
。
 a| 
UI64
 a| 
稽核工作階段識別碼：在舊版中、此元素指出在服務啟動後、稽核系統初始化的時間。此時間值是以微秒為單位、自作業系統時代（ 1970 年 1 月 1 日為 00 ： 00 ： 00 UTC ）開始計算。

*注意：*此元素已過時、不再出現在稽核訊息中。



 a| 
ASQN
 a| 
UI64
 a| 
連續數：在先前版本中、此計數器會針對網格節點（ANID）上每個產生的稽核訊息遞增、並在服務重新啟動時重設為零。

*注意：*此元素已過時、不再出現在稽核訊息中。



 a| 
ATID
 a| 
UI64
 a| 
追蹤ID：由單一事件觸發的一組訊息所共用的識別碼。



 a| 
ATIM
 a| 
UI64
 a| 
時間戳記：觸發稽核訊息的事件產生時間、以微秒為單位測量、自作業系統時代（ 1970 年 1 月 1 日 00 ： 00 ： 00 UTC ）。請注意、將時間戳記轉換為本機日期和時間的大多數可用工具都是以毫秒為基礎。

可能需要捨入或捨去記錄的時間戳記。出現在檔案中稽核訊息開頭的人類可讀時間 `audit.log`是 ISO 8601 格式的 ATIM 屬性。日期和時間表示爲 `_YYYY-MMDDTHH:MM:SS.UUUUUU_`，其中 `T`是指示日期時間段開始的文字字符串字符。 `_UUUUUU_`為微秒。



 a| 
ATYP
 a| 
FC32
 a| 
事件類型：所記錄事件的四個字元識別碼。這會規範訊息的「有效負載」內容：包含的屬性。



 a| 
離職者
 a| 
UI32
 a| 
版本：稽核訊息的版本。隨著更新版的支援軟體、新版的服務可能會在稽核報告中加入新功能。StorageGRID此欄位可在AMS服務中啟用向下相容性、以處理舊版服務的訊息。



 a| 
RSRLT
 a| 
FC32
 a| 
結果：事件、程序或交易的結果。如果與訊息無關、則不會使用任何訊息、而不會使用SUCS、因此不會意外篩選訊息。

|===