---
permalink: audit/idel-ilm-initiated-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, IDEL, ILM Initiated Delete 
summary: 此訊息是在ILM開始刪除物件的程序時產生。 
---
= 表意：ILM啟動刪除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此訊息是在ILM開始刪除物件的程序時產生。

idel訊息會在下列任一情況下產生：

* *對於相容S3儲存區中的物件*：此訊息是在ILM啟動自動刪除物件的程序時產生、因為物件的保留期間已過期（假設已啟用自動刪除設定且合法保留已關閉）。
* * 適用於不相容 S3 儲存區中的物件 * 。此訊息是在 ILM 開始刪除物件的程序時產生、因為目前使用中 ILM 原則中沒有套用到物件的放置指示。


[cols="1a,1a,4a"]
|===
| 程式碼 | 欄位 | 說明 


 a| 
CBID
 a| 
內容區塊識別碼
 a| 
物件的CBID。



 a| 
CMPa.
 a| 
法規遵循：自動刪除
 a| 
僅適用於相容S3儲存區中的物件。0（假）或1（真）、表示在保留期間結束時、是否應自動刪除相容物件、除非儲存區處於合法持有狀態。



 a| 
Cmpl
 a| 
法規遵循：合法持有
 a| 
僅適用於相容S3儲存區中的物件。0（假）或1（真）、表示該儲存桶目前是否處於合法持有狀態。



 a| 
CMPR
 a| 
法規遵循：保留期間
 a| 
僅適用於相容S3儲存區中的物件。物件保留期間的長度（以分鐘為單位）。



 a| 
CTME
 a| 
法規遵循：擷取時間
 a| 
僅適用於相容S3儲存區中的物件。物件的擷取時間。您可以將保留期間（以分鐘為單位）新增至此值、以決定何時可從儲存區刪除物件。



 a| 
DMRK
 a| 
刪除標記版本ID
 a| 
從版本控制的儲存區刪除物件時所建立的刪除標記版本ID。貯體的作業不包括此欄位。



 a| 
CSIZ
 a| 
內容大小
 a| 
物件大小（以位元組為單位）。



 a| 
LOCS
 a| 
位置
 a| 
物件資料在StorageGRID 整個作業系統中的儲存位置。如果物件沒有位置（例如、已刪除）、LOCS的值為「」。

CLEC ：對於銷毀編碼物件、抹除編碼設定檔 ID 、以及套用至物件資料的銷毀編碼群組 ID 。

CLDI：對於複寫的物件、則為該物件位置的LDR節點ID和Volume ID。

CLNL：物件資料歸檔時物件位置的旋轉節點ID。



 a| 
路徑
 a| 
S3 鏟斗 / 金鑰
 a| 
S3 貯體名稱和 S3 金鑰名稱。



 a| 
RSRLT
 a| 
結果
 a| 
ILM作業的結果。

SUCS：ILM作業成功。



 a| 
規則
 a| 
規則標籤
 a| 
* 如果相容S3儲存區中的物件因為保留期間已過期而自動刪除、則此欄位為空白。
* 如果物件因為目前沒有更多套用至物件的放置指示而被刪除、此欄位會顯示套用至物件的上一個ILM規則的人類可讀取標籤。




 a| 
SGRP
 a| 
站台（群組）
 a| 
如果存在、則會在指定的站台刪除物件、而非擷取物件的站台。



 a| 
UUID
 a| 
通用唯一識別碼
 a| 
物件在StorageGRID 整個系統內的識別碼。



 a| 
VSID
 a| 
版本ID
 a| 
已刪除物件的特定版本的版本ID。對非版本化貯體中的貯體和物件的作業不包括此欄位。

|===