---
permalink: audit/spos-s3-post.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SPOS, S3 POST 
summary: 當S3用戶端發出POST物件要求時、如果交易成功、伺服器就會發出此訊息。 
---
= SPOS：S3 POST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當S3用戶端發出POST物件要求時、如果交易成功、伺服器就會發出此訊息。

[cols="1a,1a,4a"]
|===
| 程式碼 | 欄位 | 說明 


 a| 
CBID
 a| 
內容區塊識別碼
 a| 
所要求內容區塊的唯一識別碼。如果CBID未知、此欄位會設定為0。



 a| 
CNCH
 a| 
一致性控制標頭
 a| 
一致性控制HTTP要求標頭的值（如果要求中有的話）。



 a| 
CNID
 a| 
連線識別碼
 a| 
TCP/IP連線的唯一系統識別碼。



 a| 
CSIZ
 a| 
內容大小
 a| 
擷取物件的大小（以位元組為單位）。



 a| 
HTRH
 a| 
HTTP要求標頭
 a| 
設定期間選取的記錄HTTP要求標頭名稱和值清單。

 `X-Forwarded-For`如果存在於要求中、且值與要求寄件者 IP 位址（ SAIP 稽核欄位）不同、則會自動納入 `X-Forwarded-For`。

（不適用於 SPOS ）。



 a| 
RSRLT
 a| 
結果代碼
 a| 
RestoreObject 要求的結果。結果永遠是：

SUCS：成功



 a| 
S3AI
 a| 
S3租戶帳戶ID（要求寄件者）
 a| 
傳送要求之使用者的租戶帳戶ID。空白值表示匿名存取。



 a| 
S3AK
 a| 
S3存取金鑰ID（要求傳送者）
 a| 
傳送要求之使用者的雜湊S3存取金鑰ID。空白值表示匿名存取。



 a| 
S3BK
 a| 
S3時段
 a| 
S3儲存區名稱。



 a| 
S3KY
 a| 
S3金鑰
 a| 
S3金鑰名稱、不含儲存區名稱。貯體的作業不包括此欄位。



 a| 
S3SR
 a| 
S3子資源
 a| 
要操作的庫位或物件子資源（若適用）。

將 S3 Select 作業設為「 SELECT 」。



 a| 
SACC
 a| 
S3租戶帳戶名稱（要求寄件者）
 a| 
傳送要求之使用者的租戶帳戶名稱。匿名要求為空白。



 a| 
SAIP
 a| 
IP位址（要求傳送者）
 a| 
發出要求的用戶端應用程式IP位址。



 a| 
小型企業
 a| 
S3租戶帳戶名稱（庫位擁有者）
 a| 
庫位擁有者的租戶帳戶名稱。用於識別跨帳戶或匿名存取。



 a| 
SAI
 a| 
S3租戶帳戶ID（貯體擁有者）
 a| 
目標桶擁有者的租戶帳戶ID。用於識別跨帳戶或匿名存取。



 a| 
SRCF
 a| 
子資源組態
 a| 
還原資訊：



 a| 
SUSE
 a| 
S3使用者URN（要求傳送者）
 a| 
發出要求的使用者之租戶帳戶ID和使用者名稱。使用者可以是本機使用者或LDAP使用者。例如： `urn:sgws:identity::03393893651506583485:root`

匿名要求為空白。



 a| 
時間
 a| 
時間
 a| 
申請的總處理時間（以微秒為單位）。



 a| 
TLIP
 a| 
信任的負載平衡器IP位址
 a| 
如果要求是由信任的第7層負載平衡器路由、則為負載平衡器的IP位址。



 a| 
UUID
 a| 
通用唯一識別碼
 a| 
物件在StorageGRID 整個系統內的識別碼。



 a| 
VSID
 a| 
版本ID
 a| 
所要求之物件的特定版本的版本ID。對非版本化貯體中的貯體和物件的作業不包括此欄位。

|===