---
permalink: audit/sput-s3-put.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SPUT, S3 PUT 
summary: 當S3用戶端發出PUT交易時、系統會要求建立新的物件或儲存區。如果交易成功、伺服器就會發出此訊息。 
---
= SPUT：S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當 S3 用戶端發出 Put 交易時、系統會要求建立新的物件或儲存庫、或移除儲存庫 / 物件子資源。如果交易成功、伺服器就會發出此訊息。

[cols="1a,1a,4a"]
|===
| 程式碼 | 欄位 | 說明 


 a| 
CBID
 a| 
內容區塊識別碼
 a| 
所要求內容區塊的唯一識別碼。如果CBID未知、此欄位會設定為0。貯體的作業不包括此欄位。



 a| 
CMP
 a| 
法規遵循設定
 a| 
建立貯體時所使用的規範設定（如果存在於要求中）（被截斷為前 1024 個字元）。



 a| 
CNCH
 a| 
一致性控制標頭
 a| 
一致性控制HTTP要求標頭的值（如果要求中有的話）。



 a| 
CNID
 a| 
連線識別碼
 a| 
TCP/IP連線的唯一系統識別碼。



 a| 
CSIZ
 a| 
內容大小
 a| 
擷取物件的大小（以位元組為單位）。貯體的作業不包括此欄位。



 a| 
GFID
 a| 
Grid Federation Connection ID
 a| 
與跨網格複寫置入要求相關聯的網格同盟連線連線 ID 。僅包含在目的地網格上的稽核記錄中。



 a| 
GVSA
 a| 
Grid Federation 來源帳戶 ID
 a| 
跨網格複寫置入要求來源網格上租用戶的帳戶 ID 。僅包含在目的地網格上的稽核記錄中。



 a| 
HTRH
 a| 
HTTP要求標頭
 a| 
設定期間選取的記錄HTTP要求標頭名稱和值清單。

 `X-Forwarded-For`如果存在於要求中、且值與要求寄件者 IP 位址（ SAIP 稽核欄位）不同、則會自動納入 `X-Forwarded-For`。

`x-amz-bypass-governance-retention`會在申請中自動加入。



 a| 
LKEN
 a| 
物件鎖定已啟用
 a| 
請求標題的值 `x-amz-bucket-object-lock-enabled`（如果存在於請求中）。



 a| 
LKLH
 a| 
物件鎖定合法持有
 a| 
請求標頭的值 `x-amz-object-lock-legal-hold`（如果 PuttObject 請求中存在）。



 a| 
LKMD
 a| 
物件鎖定保留模式
 a| 
請求標頭的值 `x-amz-object-lock-mode`（如果 PuttObject 請求中存在）。



 a| 
LKRU
 a| 
物件鎖定保留至日期
 a| 
請求標頭的值 `x-amz-object-lock-retain-until-date`（如果 PuttObject 請求中存在）。值限制在擷取物件的日期後 100 年內。



 a| 
MTME
 a| 
上次修改時間
 a| 
Unix時間戳記（以微秒為單位）、表示上次修改物件的時間。



 a| 
RSRLT
 a| 
結果代碼
 a| 
交易結果。結果永遠是：

SUCS：成功



 a| 
S3AI
 a| 
S3租戶帳戶ID（要求寄件者）
 a| 
傳送要求之使用者的租戶帳戶ID。空白值表示匿名存取。



 a| 
S3AK
 a| 
S3存取金鑰ID（要求傳送者）
 a| 
傳送要求之使用者的雜湊S3存取金鑰ID。空白值表示匿名存取。



 a| 
S3BK
 a| 
S3時段
 a| 
S3儲存區名稱。



 a| 
S3KY
 a| 
S3金鑰
 a| 
S3金鑰名稱、不含儲存區名稱。貯體的作業不包括此欄位。



 a| 
S3SR
 a| 
S3子資源
 a| 
要操作的庫位或物件子資源（若適用）。



 a| 
SACC
 a| 
S3租戶帳戶名稱（要求寄件者）
 a| 
傳送要求之使用者的租戶帳戶名稱。匿名要求為空白。



 a| 
SAIP
 a| 
IP位址（要求傳送者）
 a| 
發出要求的用戶端應用程式IP位址。



 a| 
小型企業
 a| 
S3租戶帳戶名稱（庫位擁有者）
 a| 
庫位擁有者的租戶帳戶名稱。用於識別跨帳戶或匿名存取。



 a| 
SAI
 a| 
S3租戶帳戶ID（貯體擁有者）
 a| 
目標桶擁有者的租戶帳戶ID。用於識別跨帳戶或匿名存取。



 a| 
SRCF
 a| 
子資源組態
 a| 
新的子資源組態（截至前1024個字元）。



 a| 
SUSE
 a| 
S3使用者URN（要求傳送者）
 a| 
發出要求的使用者之租戶帳戶ID和使用者名稱。使用者可以是本機使用者或LDAP使用者。例如： `urn:sgws:identity::03393893651506583485:root`

匿名要求為空白。



 a| 
時間
 a| 
時間
 a| 
申請的總處理時間（以微秒為單位）。



 a| 
TLIP
 a| 
信任的負載平衡器IP位址
 a| 
如果要求是由信任的第7層負載平衡器路由、則為負載平衡器的IP位址。



 a| 
使用者ID
 a| 
上傳ID
 a| 
僅包含在用於 CompleteMultpartUpload 作業的 SPUT 訊息中。表示所有零件均已上傳和組裝。



 a| 
UUID
 a| 
通用唯一識別碼
 a| 
物件在StorageGRID 整個系統內的識別碼。



 a| 
VSID
 a| 
版本ID
 a| 
在版本控制儲存區中建立的新物件版本ID。對非版本化貯體中的貯體和物件的作業不包括此欄位。



 a| 
VSST
 a| 
版本管理狀態
 a| 
儲存區的新版本管理狀態。使用兩種狀態：「啟用」或「暫停」。物件上的作業不包含此欄位。

|===