---
permalink: audit/wput-swift-put.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WPUT, Swift PUT 
summary: 當Swift用戶端發出PUT交易時、會要求建立新的物件或容器。如果交易成功、伺服器就會發出此訊息。 
---
= WUTT：Swift Put
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當Swift用戶端發出PUT交易時、會要求建立新的物件或容器。如果交易成功、伺服器就會發出此訊息。

[cols="1a,1a,4a"]
|===
| 程式碼 | 欄位 | 說明 


 a| 
CBID
 a| 
內容區塊識別碼
 a| 
所要求內容區塊的唯一識別碼。如果CBID未知、此欄位會設定為0。容器上的作業不包含此欄位。



 a| 
CSIZ
 a| 
內容大小
 a| 
擷取物件的大小（以位元組為單位）。容器上的作業不包含此欄位。



 a| 
HTRH
 a| 
HTTP要求標頭
 a| 
設定期間選取的記錄HTTP要求標頭名稱和值清單。

 `X-Forwarded-For`如果存在於要求中、且值與要求寄件者 IP 位址（ SAIP 稽核欄位）不同、則會自動納入 `X-Forwarded-For`。



 a| 
MTME
 a| 
上次修改時間
 a| 
Unix時間戳記（以微秒為單位）、表示上次修改物件的時間。



 a| 
RSRLT
 a| 
結果代碼
 a| 
交易結果。結果永遠是：

SUCS：成功



 a| 
SAIP
 a| 
要求用戶端的IP位址
 a| 
發出要求的用戶端應用程式IP位址。



 a| 
時間
 a| 
時間
 a| 
申請的總處理時間（以微秒為單位）。



 a| 
TLIP
 a| 
信任的負載平衡器IP位址
 a| 
如果要求是由信任的第7層負載平衡器路由、則為負載平衡器的IP位址。



 a| 
UUID
 a| 
通用唯一識別碼
 a| 
物件在StorageGRID 整個系統內的識別碼。



 a| 
WAC
 a| 
Swift帳戶ID
 a| 
由支援系統指定的唯一帳戶ID StorageGRID 。



 a| 
WCON
 a| 
Swift Container
 a| 
Swift容器名稱。



 a| 
WOBJ
 a| 
Swift物件
 a| 
Swift物件識別碼。容器上的作業不包含此欄位。



 a| 
WUSR
 a| 
Swift帳戶使用者
 a| 
Swift帳戶使用者名稱、可唯一識別執行交易的用戶端。

|===