---
permalink: swnodes/automating-installation-linux.html 
sidebar: sidebar 
keywords: how to automate linux installation 
summary: 您可以自動化StorageGRID主機服務的 Linux 安裝和網格節點的設定。 
---
= 自動化安裝（Linux）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以自動化StorageGRID 安裝支援服務和網格節點的組態。

.關於這項工作

NOTE: 「Linux」指的是 RHEL、Ubuntu 或 Debian 部署。有關受支援版本的列表，請參閱 https://imt.netapp.com/matrix/#welcome["NetApp互通性對照表工具IMT （不含）"^]。

在下列任一情況下、自動化部署可能會很有用：

* 您已經使用標準協調架構（例如Ansible、Puppet或Chef）來部署及設定實體或虛擬主機。
* 您打算部署多StorageGRID 個實例。
* 您正在部署一個龐大且複雜StorageGRID 的實體執行個體。


這個支援服務是由套件安裝、並由組態檔案驅動。StorageGRID您可以使用下列其中一種方法來建立組態檔：

* link:creating-node-configuration-files.html["建立組態檔"]在手動安裝期間互動。
* 如本文所述、預先準備組態檔案（或以程式設計方式）、以使用標準協調架構來啟用自動化安裝。
+
StorageGRID 提供選用的 Python 指令碼、可將 StorageGRID 應用裝置和整個 StorageGRID 系統（「網格」）的組態自動化。您可以直接使用這些指令碼、也可以檢查這些指令碼、瞭解如何在您自己開發的網格部署和組態工具中使用link:overview-of-installation-rest-api.html["安裝REST API StorageGRID"]。





== 自動化StorageGRID 安裝及設定整套的支援服務

您可以StorageGRID 使用Ansible、Puppet、Chef、Fabric或SaltStack等標準協調架構來自動化安裝支援服務。

StorageGRID主機服務打包在 DEB（Ubuntu 或 Debian）或 RPM（RHEL）中，並由您可以提前（或以程式設計方式）準備的設定檔驅動，以實現自動安裝。如果您已經使用標準編排框架來安裝和設定您的 Linux 部署，那麼將StorageGRID新增至您的劇本或配方應該很簡單。

您可以自動化準備主機和部署虛擬網格節點的所有步驟。



=== Ansible角色與方針範例

範例 Ansible 角色和教戰手冊隨附於資料夾中的安裝封存 `/extras`。Ansible 教戰手冊說明角色如何 `storagegrid`準備主機、並將 StorageGRID 安裝到目標伺服器上。您可以視需要自訂角色或方針。


NOTE: 範例播放手冊不包含在開始StorageGRID 執行「支援服務」之前建立網路裝置所需的步驟。在完成及使用本方針之前、請先新增這些步驟。

[role="tabbed-block"]
====
.紅帽企業版
--
對於 RHEL，提供的安裝任務 `storagegrid`角色範例使用 `ansible.builtin.dnf`模組從本機 RPM 檔案或遠端 Yum 儲存庫執行安裝。如果模組不可用或不受支持，您可能需要編輯以下文件中的相應 Ansible 任務以使用 `yum`或者 `ansible.builtin.yum`模組：

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`


--
.Ubuntu或DEBIAN
--
對於 Ubuntu 或 Debian，提供的安裝任務 `storagegrid`角色範例使用 `ansible.builtin.apt`模組從本機 DEB 檔案或遠端 apt 儲存庫執行安裝。如果模組不可用或不受支持，您可能需要編輯以下文件中的相應 Ansible 任務以使用 `ansible.builtin.apt`模組：

* `roles/storagegrid/tasks/deb_install_from_repo.yml`
* `roles/storagegrid/tasks/deb_install_from_local.yml`


--
====


== 自動化StorageGRID 功能組態

部署完網格節點之後、您可以自動化StorageGRID 設定該系統。

.開始之前
* 您可以從安裝歸檔中得知下列檔案的位置。
+
[cols="1a,1a"]
|===
| 檔案名稱 | 說明 


| configure-storagegrid.py  a| 
Python指令碼用於自動化組態



| 設定-storagegrid。same.json  a| 
用於指令碼的組態檔範例



| 設定-storagegrid。blank.json  a| 
與指令碼搭配使用的空白組態檔

|===
* 您已建立 `configure-storagegrid.json`組態檔案。要創建此文件，您可以修改示例配置文件(`configure-storagegrid.blank.json`）(`configure-storagegrid.sample.json`或空白配置文件）。



CAUTION: 儲存修改後的密碼部分的管理密碼和設定密碼 `configure-storagegrid.json`設定檔保存在安全的位置。安裝、擴充和維護過程都需要這些密碼。您還應該備份修改後的 `configure-storagegrid.json`設定檔並將其儲存在安全的位置。

.關於這項工作
您可以使用 `configure-storagegrid.py` Python 指令碼和 `configure-storagegrid.json`組態檔來自動化 StorageGRID 系統的組態。


NOTE: 您也可以使用Grid Manager或安裝API來設定系統。

.步驟
. 登入您用來執行Python指令碼的Linux機器。
. 切換至您擷取安裝歸檔的目錄。
+
例如：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
其中 `platform`是 `debs`、 `rpms`或 `vsphere`。

. 執行Python指令碼並使用您建立的組態檔。
+
例如：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.結果
恢復套件 `.zip`檔案會在組態程序期間產生、並下載到執行安裝和組態程序的目錄。您必須備份「恢復套件」檔案、以便StorageGRID 在一個或多個網格節點故障時、恢復該系統。例如、將其複製到安全的備份網路位置、以及安全的雲端儲存位置。


CAUTION: 必須保護恢復套件檔案、因為其中包含可用於從StorageGRID 該系統取得資料的加密金鑰和密碼。

如果您指定應產生隨機密碼、請開啟檔案、 `Passwords.txt`並尋找存取 StorageGRID 系統所需的密碼。

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
系統會在顯示確認訊息時安裝及設定您的系統。StorageGRID

[listing]
----
StorageGRID has been configured and installed.
----