---
permalink: swnodes/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure container engine storage volume, Docker, Podman 
summary: 在安裝 Docker 或 Podman 容器引擎之前，您可能需要格式化儲存磁碟區並掛載它。 
---
= 配置容器引擎儲存磁碟區（Linux）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安裝 Docker 或 Podman 容器引擎之前，您可能需要格式化儲存磁碟區並掛載它。


NOTE: 將 Docker 作為僅限軟體部署的容器引擎的支援已過時。Docker 將在未來版本中以另一個 Container 引擎取代。


NOTE: 「Linux」指的是 RHEL、Ubuntu 或 Debian 部署。有關受支援版本的列表，請參閱 https://imt.netapp.com/matrix/#welcome["NetApp互通性對照表工具IMT （不含）"^]。

.關於這項工作
如果您打算將根卷用於 Docker 或 Podman 儲存卷，並且主機分割區上有足夠的可用空間，則可以跳過以下步驟：

* Podman： `/var/lib/containers`
* Docker： `/var/lib/docker`


.步驟
. 在容器引擎儲存磁碟區上建立檔案系統：
+
[role="tabbed-block"]
====
.紅帽企業版
--
[listing]
----
sudo mkfs.ext4 container-engine-storage-volume-device
----
--
.Ubuntu或DEBIAN
--
[listing]
----
sudo mkfs.ext4 docker-storage-volume-device
----
--
====
. 掛載Container Engine儲存磁碟區：
+
[role="tabbed-block"]
====
.紅帽企業版
--
** 適用於Docker：
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
** 若為Podman：
+
[listing]
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----


--
.Ubuntu或DEBIAN
--
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount docker-storage-volume-device /var/lib/docker
----
** 若為Podman：
+
[listing]
----
sudo mkdir -p /var/lib/podman
sudo mount container-storage-volume-device /var/lib/podman
----


--
====
. 將容器儲存磁碟區裝置的條目新增至 /etc/fstab。
+
** RHEL：容器儲存卷設備
** Ubuntu 或 Debian：docker-storage-volume-device
+
此步驟可確保儲存磁碟區在主機重新開機後自動重新掛載。







== 安裝Docker

StorageGRID系統可以作為容器集合在 Linux 上運作。

* 在為 Ubuntu 或 Debian 安裝StorageGRID之前，您必須安裝 Docker。
* 如果您選擇使用 Docker 容器引擎，請依照下列步驟安裝 Docker。否則，<<install-podman-rhel,安裝Podman>> 。



NOTE: 將 Docker 作為僅限軟體部署的容器引擎的支援已過時。Docker 將在未來版本中以另一個 Container 引擎取代。

.步驟
. 請依照Linux套裝作業系統的指示來安裝Docker。
+

NOTE: 如果您的Linux套裝作業系統未隨附Docker、您可以從Docker網站下載。

. 執行下列兩個命令、確保已啟用及啟動Docker：
+
[listing]
----
sudo systemctl enable docker
----
+
[listing]
----
sudo systemctl start docker
----
. 輸入下列命令、確認您已安裝Docker的預期版本：
+
[listing]
----
sudo docker version
----
+
用戶端和伺服器版本必須為 1.11.0 或更新版本。





== 安裝Podman

StorageGRID系統作為容器集合運作。如果您選擇使用 Podman 容器引擎，請依照以下步驟安裝 Podman。否則，<<安裝Docker,安裝Docker>> 。

.步驟
. 依照Linux套裝作業系統的指示、安裝Podman和Podman-Docker。
+

NOTE: 安裝Podman時、您也必須安裝Podman-Docker套件。

. 輸入下列命令、確認您已安裝Podman和Podman-Docker的預期版本：
+
[listing]
----
sudo docker version
----
+

NOTE: 使用Podman-Docker套件可以使用Docker命令。

+
用戶端和伺服器版本必須為 3.2.3 或更新版本。

+
[listing]
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----


.相關資訊
link:configuring-host-storage.html["設定主機儲存設備"]
