---
permalink: swnodes/cpu-and-ram-requirements.html 
sidebar: sidebar 
keywords: cpu, ram, cpu cores 
summary: 安裝StorageGRID 支援功能軟體之前、請先確認並設定硬體、使其準備好支援StorageGRID 該系統。 
---
= CPU與RAM需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝StorageGRID 支援功能軟體之前、請先確認並設定硬體、使其準備好支援StorageGRID 該系統。

每StorageGRID 個支援節點都需要下列最低資源：

* CPU核心：每個節點8個
* RAM ：視可用的總 RAM 和系統上執行的非 StorageGRID 軟體數量而定
+
** 一般而言、每個節點至少 24 GB 、比系統總 RAM 少 2 至 16 GB
** 每個租戶至少 64 GB 、擁有約 5 、 000 個貯體




軟體型中繼資料專用節點資源必須符合現有的儲存節點資源。例如：

* 如果現有的 StorageGRID 站台使用 SG6000 或 SG6100 應用裝置，則僅限軟體型中繼資料節點必須符合下列最低需求：
+
** 128 GB RAM
** 8 核心 CPU
** 8 TB SSD 或與 Cassandra 資料庫相同的儲存設備（ rangedb/0 ）


* 如果現有的StorageGRID站點使用具有 24 GB RAM、8 核心 CPU 和 3 TB 或 4TB 元資料儲存的虛擬儲存節點，則基於軟體的僅元資料節點應使用類似的資源（24 GB RAM、8 核心 CPU 和 4TB 元資料儲存（rangedb/0））。


新增 StorageGRID 站台時，新站台的中繼資料總容量至少應與現有的 StorageGRID 站台和新站台資源相符，且應與現有 StorageGRID 站台的儲存節點相符。


NOTE: 「Linux」指的是 RHEL、Ubuntu 或 Debian 部署。有關受支援版本的列表，請參閱 https://imt.netapp.com/matrix/#welcome["NetApp互通性對照表工具IMT （不含）"^]。

[role="tabbed-block"]
====
.Linux
--
確保StorageGRID 您計畫在每個實體或虛擬主機上執行的各個節點數量、不會超過CPU核心數量或可用的實體RAM。如果主機並非專屬執行 StorageGRID （不建議）、請務必考慮其他應用程式的資源需求。

--
.VMware
--
VMware 支援每部虛擬機器一個節點。確保 StorageGRID 節點不超過可用的實體 RAM 。每個虛擬機器都必須專用於執行 StorageGRID 。

--
====

CAUTION: 定期監控CPU和記憶體使用量、確保這些資源能持續因應您的工作負載。例如、將虛擬儲存節點的RAM和CPU配置加倍、可提供類似StorageGRID 於針對應用裝置節點所提供的資源。此外、如果每個節點的中繼資料量超過500 GB、請考慮將每個節點的RAM增加至48 GB以上。如需管理物件中繼資料儲存、增加中繼資料保留空間設定link:../admin/index.html["管理"]、以及監控 CPU 和記憶體使用量的相關資訊、請參閱、link:../monitor/index.html["監控"]和 link:../upgrade/index.html["升級"]StorageGRID 的指示。

如果在基礎實體主機上啟用超執行緒、您可以為每個節點提供8個虛擬核心（4個實體核心）。如果基礎實體主機上未啟用超執行緒、則每個節點必須提供8個實體核心。

如果您使用虛擬機器做為主機、並控制VM的大小和數量、您應該為每StorageGRID 個支援節點使用單一VM、並據此調整VM大小。

（僅限 RHEL、Debian 和 Ubuntu）對於生產部署，您不應在相同實體儲存硬體或虛擬主機上執行多個儲存節點。單一StorageGRID部署中的每個儲存節點都應位於其自己的隔離故障域中。如果確保單一硬體故障僅影響單一儲存節點，則可以最大限度地提高物件資料的持久性和可用性。

另請參閱link:storage-and-performance-requirements.html["儲存與效能需求"]。
