---
permalink: swnodes/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation REST API 
summary: 提供執行安裝工作所需的安裝API。StorageGRID StorageGRID 
---
= 了解 StorageGRID 安裝 REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
提供執行安裝工作所需的安裝API。StorageGRID StorageGRID

API使用Swagger開放原始碼API平台來提供API文件。Swagger可讓開發人員和非開發人員在使用者介面中與API互動、說明API如何回應參數和選項。本文件假設您熟悉標準網路技術和 JSON 資料格式。


CAUTION: 您使用 API 文件網頁執行的任何 API 作業都是即時作業。請小心不要錯誤地建立、更新或刪除組態資料或其他資料。

每個REST API命令都包含API的URL、HTTP動作、任何必要或選用的URL參數、以及預期的API回應。



[[storagegrid-installation-api]]
== 安裝API StorageGRID

StorageGRID 安裝 API 僅在您初次設定 StorageGRID 系統、以及需要執行主要管理節點還原時可用。安裝API可透過HTTPS從Grid Manager存取。

若要存取 API 文件、請前往主要管理節點上的安裝網頁、然後從功能表列選取 * 說明 * > * API 文件 * 。

《程式集安裝API》包含下列各節：StorageGRID

* *config*：與產品版本和 API 版本相關的操作。您可以列出產品發行版本以及該版本支援的 API 主要版本。
* *grid*：網格層級組態操作。您可以取得和更新網格設定，包括網格詳細資訊、Grid Network 子網路、網格密碼以及 NTP 和 DNS 伺服器 IP 位址。
* *節點*：節點層級組態操作。您可以擷取網格節點清單、刪除網格節點、設定網格節點、檢視網格節點、重設網格節點的組態。
* *provision*：資源配置操作。您可以啟動資源配置操作並檢視資源配置操作的狀態。
* *恢復*：主要管理節點恢復作業。您可以重設資訊、上傳 Recovery Package、啟動恢復，以及檢視恢復作業的狀態。
* *recovery-package*：下載 Recovery Package 的操作。
* *sites*：站台層級的組態操作。您可以建立、檢視、刪除和修改站台。
* *temporary-password*: 在安裝期間對臨時密碼執行操作，以保護 mgmt-api 的安全。

