---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.0 使用網格管理 API 的第 4 版。版本 4 棄用了版本 3；但是，版本 1、2 和 3 仍然受支援。 
---
= StorageGRID 中 Grid Management API 的變更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 使用網格管理 API 的第 4 版。版本 4 棄用了版本 3；但是，版本 1、2 和 3 仍然受支援。


NOTE: 您可以繼續使用StorageGRID 12.0 中已棄用的管理 API 版本；但是， StorageGRID的未來版本將不再支援這些版本的 API。升級到StorageGRID 12.0 後，您可以使用 `PUT /grid/config/management`API。

若要深入瞭解link:../admin/using-grid-management-api.html["使用Grid Management API"]、請前往。



== 分支儲存桶的新端點

已新增以下端點，以便您link:../tenant/what-is-branch-bucket.html["管理分支儲存桶"]：

`GET /org/containers/{branchBucketName}/branch`

`PUT /org/containers/{branchBucketName}/branch`



== Move ADC 的新專用終端點

已新增下列私有端點，以便您link:../maintain/move-adc-service.html["行動 ADC 服務"]從一個儲存節點到同一站點上的另一個儲存節點：

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`



== 轉換為僅資料節點的新私有端點

已新增下列私有端點，以便您link:../maintain/convert-to-data-only-node.html["轉換一個或多個組合儲存節點"]不包含 ADC 服務到僅資料節點。

`/private/convert-to-data-only-node`

`/private/convert-to-data-only-node/start`

`/private/convert-to-data-only-node/retry`
