---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 請根據升級所需的時間考慮何時升級。請注意在升級的每個階段中、您可以執行哪些作業、哪些作業無法執行。 
---
= 預估完成升級所需的時間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請根據升級所需的時間考慮何時升級。請注意在升級的每個階段中、您可以執行哪些作業、哪些作業無法執行。

.關於這項工作
完成升級所需的時間StorageGRID 取決於多種因素、例如用戶端負載和硬體效能。

下表摘要說明主要的升級工作、並列出每項工作所需的大約時間。表格後的步驟提供您可用來預估系統升級時間的指示。

[cols="1a,2a,2a,4a"]
|===
| 升級工作 | 說明 | 大約所需時間 | 在此工作期間 


 a| 
執行預先檢查並升級主要管理節點
 a| 
系統會執行升級預先檢查、並停止、升級及重新啟動主要管理節點。
 a| 
30 分鐘到 1 小時、服務應用裝置節點需要最多時間。

未解決的預先檢查錯誤將會增加這次時間。
 a| 
您無法存取主要管理節點。可能會回報連線錯誤、您可以忽略這些錯誤。

在開始升級之前執行升級預先檢查、可讓您在排定的升級維護時間之前解決任何錯誤。



 a| 
開始升級服務
 a| 
軟體檔案隨即散佈、並啟動升級服務。
 a| 
每個網格節點 3 分鐘
 a| 



 a| 
升級其他網格節點
 a| 
所有其他網格節點上的軟體均按照您批准節點的順序進行升級。一個管理節點或網關節點與一個儲存節點同時升級。
 a| 
每個節點15分鐘到1小時、應用裝置節點最需要時間

* 注意 * ：對於應用裝置節點、 StorageGRID 應用裝置安裝程式會自動更新至最新版本。
 a| 
* 請勿變更網格組態。
* 請勿變更稽核層級組態。
* 請勿更新 ILM 組態。
* 您無法執行其他維護程序、例如修復程式、取消委任或擴充。


* 注意 * ：如果您需要執行恢復、請聯絡技術支援部門。



 a| 
啟用功能
 a| 
新版本的新功能已啟用。
 a| 
不到5分鐘
 a| 
* 請勿變更網格組態。
* 請勿變更稽核層級組態。
* 請勿更新 ILM 組態。
* 您無法執行其他維護程序。




 a| 
升級資料庫
 a| 
升級過程檢查每個節點以驗證 Cassandra 資料庫不需要更新。
 a| 
每個節點10秒或整個網格幾分鐘
 a| 
升級到StorageGRID 12.0 包括 Cassandra 資料庫升級。從StorageGRID 11.9 升級到 12.0 後，元資料格式更新將在背景進行一到三天。在此期間，某些維護程序（例如擴充）將被停用。

對於未來StorageGRID 的版本、Cassandra資料庫更新步驟可能需要幾天的時間才能完成。



 a| 
最終升級步驟
 a| 
移除暫用檔案、並完成新版本的升級。
 a| 
5 分鐘
 a| 
當 * 最終升級步驟 * 工作完成時、您可以執行所有維護程序。

|===


== 估計升級時間

.步驟
. 預估升級所有網格節點所需的時間。
+
.. 將您的支援系統中的節點數乘StorageGRID 以1小時/節點。
+
一般而言、應用裝置節點的升級時間比軟體型節點長。

.. 在此時間加上 1 小時、以說明下載檔案、執行預先檢查驗證、以及完成最終升級步驟所需的時間 `.upgrade`。


. 如果您有Linux節點、請為每個節點新增15分鐘、以說明下載及安裝RPM或Deb套件所需的時間。
. 新增步驟1和步驟2的結果、計算升級的預估總時間。




== 範例：升級到StorageGRID 12.0 的預計時間

假設您的系統有14個網格節點、其中8個是Linux節點。

. 將14乘以1小時/節點。
. 加1小時以說明下載、預先檢查及最終步驟。
+
升級所有節點的預估時間為15小時。

. 將8乘以15分鐘/節點、以計算在Linux節點上安裝RPM或Deb套件的時間。
+
此步驟的預估時間為2小時。

. 將這些值加在一起。
+
您最多需要 17 小時才能完成系統到StorageGRID 12.0.0 的升級。




NOTE: 視需要、您可以核准網格節點的子集以在多個工作階段中升級、將維護時段分割成較小的視窗。例如、您可能偏好在一個工作階段中升級站台 A 的節點、然後在稍後的工作階段中升級站台 B 的節點。如果您選擇在多個工作階段中執行升級、請注意、在所有節點都升級之前、您無法開始使用新功能。
