---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 瞭解 StorageGRID 系統在升級期間會受到哪些影響。 
---
= 系統在升級期間的影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解 StorageGRID 系統在升級期間會受到哪些影響。



== 不中斷升級StorageGRID

整個升級過程中、這個系統可以從用戶端應用程式擷取及擷取資料。StorageGRID如果您核准所有類型相同的節點進行升級（例如儲存節點）、則節點會一次關閉一個節點、因此當某種類型的所有網格節點或所有網格節點都無法使用時、就不會有任何時間。

為了確保持續可用、請確保 ILM 原則包含指定儲存每個物件多個複本的規則。您也必須確定所有外部 S3 用戶端都已設定為傳送要求至下列其中一項：

* 高可用度（ HA ）群組虛擬 IP 位址
* 高可用度協力廠商負載平衡器
* 每個用戶端有多個閘道節點
* 每個用戶端有多個儲存節點




== 用戶端應用程式可能會遭遇短期中斷

StorageGRID 系統可在整個升級程序中從用戶端應用程式擷取和擷取資料、但是、如果升級需要在這些節點上重新啟動服務、用戶端與個別閘道節點或儲存節點的連線可能會暫時中斷。升級程序完成後、連線能力將會恢復、而服務會在個別節點上恢復。

如果連線中斷一段短時間是不可接受的、您可能需要排程停機時間來套用升級。您可以使用選擇性核准來排程特定節點的更新時間。


NOTE: 您可以使用多個閘道和高可用度（ HA ）群組、在升級過程中提供自動容錯移轉。請參閱的說明link:../admin/configure-high-availability-group.html["設定高可用度群組"]。



== 應用裝置韌體已升級

在 StorageGRID 11.9 升級期間：

* 所有 StorageGRID 應用裝置節點都會自動升級至 StorageGRID 應用裝置安裝程式韌體 3.9 版。
* SG6060 和 SGF6024 應用裝置會自動升級至 BIOS 韌體版本 3B08.EX 和 BMC 韌體版本 4.00.07 。
* SG100 和 SG1000 應用裝置會自動升級至 BIOS 韌體版本 3B13.EC 和 BMC 韌體版本 4.74.07 。
* SGF6112 、 SG6160 、 SG110 和 SG1100 設備會自動升級至 BMC 韌體 3.16.07 版。




== ILM 原則的處理方式會因其狀態而異

* 升級後、作用中原則將維持不變。
* 升級時只會保留最新的 10 項歷史原則。
* 如果有建議的原則、則會在升級期間刪除。




== 可能會觸發警示

當服務啟動和停止時、StorageGRID 以及當作業系統以混合版本環境運作時、可能會觸發警示（部分網格節點執行較早版本、而其他節點則已升級至較新版本）。升級完成後、可能會觸發其他警示。

例如、當服務停止時、您可能會看到 * 無法與 node* 通訊警示、或者當某些節點已升級至 StorageGRID 11.9 、但其他節點仍在執行 StorageGRID 11.8 時、您可能會看到 * Cassandra 通訊錯誤 * 警示。一般而言、這些警示會在升級完成時清除。

當 StorageGRID 11.9 升級期間停止儲存節點時、可能會觸發 * ILM 放置無法達成 * 警示。升級完成後、此警示可能會持續1天。

升級完成後、您可以從 Grid Manager 儀表板選取 * 最近解決的警示 * 或 * 目前警示 * 、來檢閱任何與升級相關的警示。



== 會產生許多SNMP通知

請注意、當網格節點在升級期間停止並重新啟動時、可能會產生大量的SNMP通知。若要避免過多通知、請清除 * 啟用 SNMP 代理程式通知 * 核取方塊（ * 組態 * > * 監控 * > * SNMP 代理程式 * ）、以在開始升級之前停用 SNMP 通知。然後在升級完成後重新啟用通知。



== 組態變更受到限制


NOTE: 此清單特別適用於從 StorageGRID 11.8 升級至 StorageGRID 11.9 。如果您要升級至另一個 StorageGRID 版本、請參閱該版本升級指示中的限制變更清單。

在*啟用新功能*工作完成之前：

* 請勿變更任何網格組態。
* 請勿啟用或停用任何新功能。
* 請勿更新 ILM 組態。否則、您可能會遇到不一致且非預期的ILM行為。
* 請勿套用 Hotfix 或恢復網格節點。
+

NOTE: 如果您需要在升級期間恢復節點、請聯絡技術支援部門。

* 升級至 StorageGRID 11.9 時、不應管理 HA 群組、 VLAN 介面或負載平衡器端點。
* 在升級至 StorageGRID 11.9 完成之前、請勿刪除任何 HA 群組。其他 HA 群組中的虛擬 IP 位址可能無法存取。


直到*最終升級步驟*工作完成為止：

* 請勿執行擴充程序。
* 請勿執行取消委任程序。




== 您無法從租戶管理程式檢視貯體詳細資料或管理貯體

在升級至 StorageGRID 11.9 期間（也就是說、當系統以混合版本環境運作時）、您無法使用租戶管理程式來檢視貯體詳細資料或管理貯體。下列其中一個錯誤會出現在Tenant Manager的「桶」頁面上：

* 升級至 11.9 時無法使用此 API 。
* 當您升級至 11.9 時、無法在租戶管理程式中檢視貯體版本設定詳細資料。


此錯誤將在升級至 11.9 後解決。

.因應措施
11.9 升級進行中時、請使用下列工具來檢視貯體詳細資料或管理貯體、而非使用租戶管理程式：

* 若要在貯體上執行標準 S3 作業、請使用link:../s3/operations-on-buckets.html["S3 REST API"]或link:../tenant/understanding-tenant-management-api.html["租戶管理API"]。
* 若要在貯體上執行 StorageGRID 自訂作業（例如檢視及修改貯體一致性、啟用或停用上次存取時間更新、或設定搜尋整合）、請使用租戶管理 API 。

