---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 瞭解 StorageGRID 系統在升級期間會受到哪些影響。 
---
= StorageGRID 升級如何影響您的系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解 StorageGRID 系統在升級期間會受到哪些影響。



== 升級完成前允許外部 SSH 訪問

升級期間允許外部 SSH 存取。升級完成後，外部 SSH 存取預設會被阻止。升級後，您可以使用“網格管理器”>“安全性設定”頁面上的“阻止 SSH”選項卡來link:../admin/manage-external-ssh-access.html["管理外部 SSH 訪問"]。網格節點之間的 SSH 存取不受影響。



== 不中斷升級StorageGRID

整個升級過程中、這個系統可以從用戶端應用程式擷取及擷取資料。StorageGRID如果您核准所有類型相同的節點進行升級（例如儲存節點）、則節點會一次關閉一個節點、因此當某種類型的所有網格節點或所有網格節點都無法使用時、就不會有任何時間。

為了確保持續可用、請確保 ILM 原則包含指定儲存每個物件多個複本的規則。您也必須確定所有外部 S3 用戶端都已設定為傳送要求至下列其中一項：

* 高可用度（ HA ）群組虛擬 IP 位址
* 高可用度協力廠商負載平衡器
* 每個用戶端有多個閘道節點
* 每個用戶端有多個儲存節點




== 用戶端應用程式可能會遭遇短期中斷

StorageGRID 系統可在整個升級程序中從用戶端應用程式擷取和擷取資料、但是、如果升級需要在這些節點上重新啟動服務、用戶端與個別閘道節點或儲存節點的連線可能會暫時中斷。升級程序完成後、連線能力將會恢復、而服務會在個別節點上恢復。

如果連線中斷一段短時間是不可接受的、您可能需要排程停機時間來套用升級。您可以使用選擇性核准來排程特定節點的更新時間。


NOTE: 您可以使用多個閘道和高可用度（ HA ）群組、在升級過程中提供自動容錯移轉。請參閱的說明link:../admin/configure-high-availability-group.html["設定高可用度群組"]。



== 後台修復無法在具有混合版本節點的網格上運行

當網格包含混合版本節點時，升級期間不會執行背景修復。在網站中斷期間出現的任何不一致問題在升級完成之前都不會修復。



== 應用裝置韌體已升級

在StorageGRID 12.0 升級期間：

* 所有StorageGRID設備節點都會自動升級到StorageGRID Appliance Installer 韌體版本 12.0。
* SG6060 和 SGF6024 設備自動升級到 BIOS 韌體版本 3B08.EX 和BMC韌體版本 4.01.07。
* SG100 和 SG1000 裝置自動升級至 BIOS 韌體版本 3B13.EC 和BMC韌體版本 4.75.07。
* SGF6112、SG6160、SG110 和 SG1100 設備自動升級至 BIOS 韌體版本 3A14.QD 和BMC韌體版本 3.19.07。




== ILM 原則的處理方式會因其狀態而異

* 升級後、作用中原則將維持不變。
* 升級時只會保留最新的 10 項歷史原則。
* 如果有建議的原則、則會在升級期間刪除。




== 可能會觸發警示

當服務啟動和停止時、StorageGRID 以及當作業系統以混合版本環境運作時、可能會觸發警示（部分網格節點執行較早版本、而其他節點則已升級至較新版本）。升級完成後、可能會觸發其他警示。

例如，當服務停止時，您可能會看到*無法與節點通訊*警報，或當某些節點已升級至StorageGRID 12.0 但其他節點仍在執行StorageGRID 11.9 時，您可能會看到*Cassandra 通訊錯誤*警報。一般來說，升級完成後這些警報將會清除。

在升級到StorageGRID 12.0 期間儲存節點停止時，可能會觸發 *ILM 放置無法實現* 警報。升級完成後，此警報可能會持續 1 天。

升級完成後、您可以從 Grid Manager 儀表板選取 * 最近解決的警示 * 或 * 目前警示 * 、來檢閱任何與升級相關的警示。



== 組態變更受到限制


NOTE: 此清單專門適用於從StorageGRID 11.9 升級到StorageGRID 12.0。如果您要升級到另一個StorageGRID版本，請參閱該版本升級說明中的受限變更清單。

在*啟用新功能*工作完成之前：

* 請勿變更任何網格組態。
* 請勿啟用或停用任何新功能。
* 請勿更新 ILM 組態。否則、您可能會遇到不一致且非預期的ILM行為。
* 請勿套用 Hotfix 或恢復網格節點。
+

NOTE: 如果您需要在升級期間恢復節點、請聯絡技術支援部門。

* 升級至StorageGRID 12.0 時，您不應管理 HA 群組、VLAN 介面或負載平衡器端點。
* 在升級到StorageGRID 12.0 完成之前，請勿刪除任何 HA 群組。其他 HA 群組中的虛擬 IP 位址可能變得無法存取。


直到*最終升級步驟*工作完成為止：

* 請勿執行擴充程序。
* 請勿執行取消委任程序。

