---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, how to perform a software upgrade 
summary: 您可以升級至 StorageGRID 11.9 、並同時套用該版本的最新 Hotfix 。StorageGRID 升級頁面提供建議的升級路徑、並直接連結至正確的下載頁面。 
---
= 執行升級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升級至 StorageGRID 11.9 、並同時套用該版本的最新 Hotfix 。StorageGRID 升級頁面提供建議的升級路徑、並直接連結至正確的下載頁面。

.開始之前
您已檢閱所有考量事項、並完成所有規劃與準備步驟。



== 存取 StorageGRID 升級頁面

第一步是在 Grid Manager 中存取 StorageGRID 升級頁面。

.步驟
. 使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
. 選擇*維護*>*系統*>*軟體更新*。
. 從 StorageGRID 升級方塊中、選取 * 升級 * 。




== 選取檔案

「 StorageGRID 升級」頁面上的更新路徑會指出您必須安裝哪些主要版本（例如 11.9.2 ）和 Hotfix （例如 11.9.0.1 ）、才能取得最新的 StorageGRID 版本。您應該依照所示順序安裝建議的版本和 Hotfix 。


TIP: 如果未顯示更新路徑、您的瀏覽器可能無法存取 NetApp 支援網站、或是 AutoSupport 頁面（ * 支援 * > * 工具 * > * AutoSupport * > * 設定 * ）上的 * 檢查軟體更新 * 核取方塊可能已停用。

.步驟
. 如需 * 選取檔案 * 步驟、請檢閱更新路徑。
. 從「下載檔案」區段中、選取每個 * 下載 * 連結、即可從 NetApp 支援網站 下載所需的檔案。
+
如果沒有顯示更新路徑、請前往 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下載StorageGRID"^]以判斷是否有新版本或 Hotfix 可用、並下載您需要的檔案。

+

NOTE: 如果您需要在所有 Linux 主機上下載並安裝 RPM 或 Deb 套件、您可能已經在更新路徑中列出 StorageGRID 升級和 Hotfix 檔案。

. 選擇 * 瀏覽 * 將版本升級檔案上傳至 StorageGRID ： `NetApp_StorageGRID_11.9.0_Software_uniqueID.upgrade`
+
完成上傳與驗證程序後、檔案名稱旁會出現綠色核取記號。

. 如果您下載了 Hotfix 檔案、請選取 * 瀏覽 * 來上傳該檔案。Hotfix 將會在版本升級時自動套用。
. 選擇*繼續*。




== 執行預先檢查

執行預先檢查可讓您在開始升級網格之前、先偵測並解決任何升級問題。

.步驟
. 在「 * 執行預先檢查 * 」步驟中、請先輸入您網格的資源配置複雜密碼。
. 選擇*下載恢復套件*。
+
您應該先下載最新的還原套件檔案複本，然後再升級主要管理節點。恢復套件檔案可讓您在發生故障時還原系統。

. 下載檔案後、請確認您可以存取內容、包括 `Passwords.txt`檔案。
. 將下載(`.zip`的檔案複製到兩個安全且獨立的位置。
+

CAUTION: 恢復套件檔案必須受到保護、因為它包含可用於從 StorageGRID 系統取得資料的加密金鑰和密碼。

. 選取 * 執行預先檢查 * 、然後等待預先檢查完成。
. 檢閱每個報告的預先檢查詳細資料、並解決任何回報的錯誤。請參閱 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["StorageGRID 軟體升級解決方案指南"^]以取得 StorageGRID 11.9 版本。
+
您必須先解決所有預先檢查錯誤 _ 、才能升級系統。不過、您不需要在升級前先處理預先檢查 _ 警告 _ 。

+

CAUTION: 如果您已開啟任何自訂防火牆連接埠、系統會在預先檢查驗證期間通知您。您必須先聯絡技術支援部門、才能繼續升級。

. 如果您進行任何組態變更以解決回報的問題、請再次選取 * 執行預先檢查 * 以取得更新的結果。
+
如果所有錯誤都已解決、系統會提示您開始升級。





== 開始升級並升級主要管理節點

當您開始升級時、升級預先檢查會再次執行、而且會自動升級主要管理節點。此部分升級最多可能需要 30 分鐘。


NOTE: 當主要管理節點正在升級時、您將無法存取任何其他 Grid Manager 頁面。稽核記錄也無法使用。

.步驟
. 選擇 * 開始升級 * 。
+
系統會出現警告、提醒您暫時失去 Grid Manager 的存取權。

. 選擇 * 確定 * 以確認警告並開始升級。
. 等待執行升級前置檢查、並讓主要管理節點升級。
+

NOTE: 如果報告了任何預先檢查錯誤、請予以解決、然後再次選取 * 開始升級 * 。

+
如果網格有另一個已上線且已就緒的管理節點、您可以使用該網格來監控主要管理節點的狀態。一旦主管理節點升級、您就可以核准其他網格節點。

. 視需要選取 * 繼續 * 以存取 * 升級其他節點 * 步驟。




== 升級其他節點

您必須升級所有網格節點、但您可以執行多個升級工作階段、並自訂升級順序。例如、您可能偏好在一個工作階段中升級站台 A 的節點、然後在稍後的工作階段中升級站台 B 的節點。如果您選擇在多個工作階段中執行升級、請注意、在所有節點都升級之前、您無法開始使用新功能。

如果節點升級順序很重要、請一次核准一個節點或節點群組、並等到每個節點上的升級完成後、再核准下一個節點或節點群組。


NOTE: 在網格節點上開始升級時、該節點上的服務會停止。之後、網格節點會重新開機。為了避免與節點通訊的用戶端應用程式發生服務中斷、除非您確定節點已準備好要停止並重新開機、否則請勿核准節點的升級。視需要排程維護時段或通知客戶。

.步驟
. 對於 * 升級其他節點 * 步驟、請檢閱摘要、其中提供整個升級的開始時間、以及每個主要升級工作的狀態。
+
** * 開始升級服務 * 是第一項升級工作。在此工作期間、軟體檔案會發佈至網格節點、並在每個節點上啟動升級服務。
** 當 * 開始升級服務 * 工作完成時， * 升級其他網格節點 * 工作會啟動，並提示您下載新的恢復套件複本。


. 出現提示時，請輸入您的資源配置密碼，然後下載恢復套件的新複本。
+

CAUTION: 升級主管理節點之後，您應該下載新的還原套件檔案複本。恢復套件檔案可讓您在發生故障時還原系統。

. 檢閱每種節點類型的狀態表。有非主要管理節點、閘道節點和儲存節點的表格。
+
當表格第一次出現時、網格節點可以處於下列其中一個階段：

+
** 打開升級的包裝
** 正在下載
** 等待核准


. [[approvion-step ]] 當您準備好選擇要升級的網格節點（或需要取消核准選取的節點）時、請使用下列指示：
+
[cols="1a,1a"]
|===
| 工作 | 指示 


 a| 
搜尋要核准的特定節點、例如特定站台上的所有節點
 a| 
在 * 搜尋 * 欄位中輸入搜尋字串



 a| 
選取所有節點以進行升級
 a| 
選取 * 核准所有節點 *



 a| 
選取所有類型相同的節點進行升級（例如、所有儲存節點）
 a| 
選取節點類型的 * 核准全部 * 按鈕

如果您核准多個相同類型的節點、則節點將一次升級一個。



 a| 
選取要升級的個別節點
 a| 
選取節點的 * 核准 * 按鈕



 a| 
延後所有選取節點的升級
 a| 
選取 * 取消核准所有節點 *



 a| 
在所有相同類型的選定節點上延遲升級
 a| 
選擇 * 不核准所有 * 按鈕作為節點類型



 a| 
延後個別節點上的升級
 a| 
選取節點的 * Unapprov* 按鈕

|===
. 等待核准的節點繼續進行這些升級階段：
+
** 已核准、正在等待升級
** 停止服務
+

NOTE: 當節點的「階段」達到 * 停止服務 * 時、您無法移除該節點。「 *Unapprov* 」按鈕已停用。

** 正在停止 Container
** 清理 Docker 影像
** 升級基礎作業系統套件
+

NOTE: 當應用裝置節點到達此階段時、應用裝置上的 StorageGRID 應用裝置安裝程式軟體即會更新。此自動化程序可確保StorageGRID SynsanceAppliance Installer版本與StorageGRID 支援的更新版本保持同步。

** 重新開機
+

NOTE: 某些應用裝置機型可能會多次重新開機、以升級韌體和 BIOS 。

** 重新開機後執行步驟
** 啟動服務
** 完成


. 視需要重複<<approval-step,核准步驟>>多次、直到所有網格節點都升級為止。




== 完整升級

當所有網格節點完成升級階段後、 * 升級其他網格節點 * 工作會顯示為已完成。其餘的升級工作會在背景中自動執行。

.步驟
. 一旦 * 啟用功能 * 工作完成（很快就會發生）、您就可以在升級的 StorageGRID 版本中開始使用link:whats-new.html["新功能"]。
. 在 * 升級資料庫 * 工作期間、升級程序會檢查每個節點、確認 Cassandra 資料庫不需要更新。
+

NOTE: 從 StorageGRID 11.8 升級至 11.9 不需要 Cassandra 資料庫升級、但 Cassandra 服務將會在每個儲存節點上停止並重新啟動。對於未來StorageGRID 的版本、Cassandra資料庫更新步驟可能需要幾天的時間才能完成。

. 當 * 升級資料庫 * 工作完成時、請等待幾分鐘、等待 * 最終升級步驟 * 完成。
. * 最終升級步驟 * 完成後、即完成升級。第一步 * 選擇檔案 * 會以綠色成功橫幅重新顯示。
. 確認網格作業已恢復正常：
+
.. 檢查服務是否正常運作、以及是否沒有非預期的警示。
.. 確認用戶端連線StorageGRID 至該系統的運作正常。



