---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: 如果執行升級時發生問題、您可以自行解決問題。如果您無法解決問題、請盡可能收集更多資訊、然後聯絡技術支援部門。 
---
= 疑難排解升級問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果執行升級時發生問題、您可以自行解決問題。如果您無法解決問題、請盡可能收集更多資訊、然後聯絡技術支援部門。



== 升級未完成

下列各節說明如何從部分升級失敗的情況中恢復。



=== 升級預先檢查錯誤

若要偵測並解決問題、您可以在開始實際升級之前、手動執行升級前置檢查。大多數預先檢查錯誤都提供如何解決問題的相關資訊。



=== 資源配置失敗

如果自動資源配置程序失敗、請聯絡技術支援部門。



=== 網格節點當機或無法啟動

如果網格節點在升級過程中當機、或在升級完成後無法成功啟動、請聯絡技術支援部門以調查並修正任何潛在問題。



=== 擷取或資料擷取中斷

如果在您不升級網格節點時、資料擷取或擷取意外中斷、請聯絡技術支援部門。



=== 資料庫升級錯誤

如果資料庫升級失敗並出現錯誤、請重試升級。如果再次失敗、請聯絡技術支援部門。

.相關資訊
link:checking-systems-condition-before-upgrading-software.html["在升級軟體之前、請先檢查系統狀況"]



== 使用者介面問題

在升級期間或之後、您可能會遇到與 Grid Manager 或 Tenant Manager 有關的問題。



=== Grid Manager 會在升級期間顯示多個錯誤訊息

如果您在升級主要管理節點時重新整理瀏覽器或瀏覽至其他 Grid Manager 頁面、可能會看到多則「 503 ：服務無法使用」和「連線至伺服器時發生問題」訊息。您可以安全地忽略這些訊息、這些訊息會在節點升級後立即停止顯示。

如果這些訊息在您開始升級後超過一小時出現、可能是發生了一些導致主要管理節點無法升級的情況。如果您無法自行解決問題、請聯絡技術支援部門。



=== Web介面未如預期回應

Grid Manager或Tenant Manager在StorageGRID 升級完更新版的更新軟體後、可能無法如預期般回應。

如果您在使用網路介面時遇到問題：

* 請確定您使用的link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]是。
+

NOTE: 瀏覽器支援通常會針對每StorageGRID 個版本進行變更。

* 清除網頁瀏覽器快取。
+
清除快取會移除舊版StorageGRID 的更新資源、並允許使用者介面再次正確運作。如需相關指示、請參閱網頁瀏覽器的說明文件。





== 「 Docker image Availability check 」錯誤訊息

嘗試開始升級程序時、您可能會收到錯誤訊息、指出「 Docker 映像可用度檢查驗證套件已識別下列問題」。您必須先解決所有問題、才能完成升級。

如果您不確定解決已知問題所需的變更、請聯絡技術支援部門。

[cols="1a,1a,1a"]
|===
| 訊息 | 原因 | 解決方案 


 a| 
無法判斷升級版本。升級版本資訊檔案 `{file_path}`與預期格式不符。
 a| 
升級套件毀損。
 a| 
重新上傳升級套件、然後再試一次。如果問題持續發生、請聯絡技術支援部門。



 a| 
找不到升級版本資訊檔案 `{file_path}`。無法判斷升級版本。
 a| 
升級套件毀損。
 a| 
重新上傳升級套件、然後再試一次。如果問題持續發生、請聯絡技術支援部門。



 a| 
無法確定上目前安裝的版本 `{node_name}`。
 a| 
節點上的重要檔案已毀損。
 a| 
聯絡技術支援。



 a| 
嘗試在上列出版本時發生連線錯誤 `{node_name}`
 a| 
節點離線或連線中斷。
 a| 
請檢查以確定所有節點均已上線、且可從主要管理節點存取、然後再試一次。



 a| 
節點的主機 `{node_name}`未載入 StorageGRID `{upgrade_version}` 映像。必須先在主機上安裝映像和服務、才能繼續升級。
 a| 
用於升級的RPM或Dub套件尚未安裝在執行節點的主機上、或影像仍在匯入中。

*附註：*此錯誤僅適用於以容器形式在Linux上執行的節點。
 a| 
請檢查以確定已在所有執行節點的Linux主機上安裝RPM或Deb套件。確認服務和映像檔的版本都正確。請稍候幾分鐘、然後再試一次。

請參閱。 link:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux：在所有主機上安裝RPM或Deb套件"]



 a| 
檢查節點時發生錯誤 `{node_name}`
 a| 
發生非預期的錯誤。
 a| 
請稍候幾分鐘、然後再試一次。



 a| 
執行預先檢查時發生未捕捉的錯誤。 `{error_string}`
 a| 
發生非預期的錯誤。
 a| 
請稍候幾分鐘、然後再試一次。

|===