---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 在開始升級之前、請確認先前版本的 StorageGRID 目前已安裝、並套用最新的可用 Hotfix 。 
---
= 在升級前驗證已安裝的 StorageGRID 版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在開始升級之前、請確認先前版本的 StorageGRID 目前已安裝、並套用最新的可用 Hotfix 。

.關於這項工作
在升級至 StorageGRID 12.1 之前，您的網格必須安裝 StorageGRID 12.0 或更新版本。如果您目前使用的是舊版 StorageGRID，則必須安裝所有先前的升級檔案及其最新的 Hotfix（強烈建議），直到您的網格目前版本至少達到 StorageGRID 12.0.0。

中顯示了一個可能的升級途徑<<example-upgrade-path,範例>>。


CAUTION: NetApp強烈建議您在升級到下一個版本之前為每個StorageGRID版本應用最新的修補程序，並且還為您安裝的每個新版本應用最新的修補程序。在某些情況下，您必須套用修補程式以避免資料遺失的風險。參考 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下載StorageGRID"^]以及每個修補程式的發行說明以了解更多資訊。



[[verify-installed-version]]
== 驗證已安裝的版本

.步驟
. 使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
. 從網格管理器的頂端、選取*說明*>*關於*。
. 驗證*版本*是否為 11.9.0.8 或更高版本。
. 如果*版本*不是 11.9.0.8 或更高版本，請前往 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下載StorageGRID"^]下載您需要的升級和修補程式檔案。
. link:../upgrade/index.html["請按照升級說明進行操作"]對於您下載的每個版本。link:../maintain/storagegrid-hotfix-procedure.html["應用最新的修補程序"]對於每個版本（強烈建議）。


參考以下升級範例。



[[example-upgrade-pathexample-upgrade-to-storagegrid-12-0-from-version-11-8]]
== [[example-upgrade-path]]範例：從版本 11.8 升級到StorageGRID 12.0

以下範例說明從 StorageGRID 版本 11.9 升級至版本 12.0 的步驟，以準備進行 StorageGRID 12.1 升級。

請依下列順序下載並安裝軟體、以準備系統進行升級：

. 升級至 StorageGRID 11.8.0 主要版本。
. 套用最新的 StorageGRID 11.8.0._y_ Hotfix 。
. 升級到StorageGRID 11.9.0 主要版本。
. 應用StorageGRID 11.9.0.8 或更高版本的修補程式。

