= 
:allow-uri-read: 


[role="tabbed-block"]
====
.複寫資料
--
* 若要取得複寫修復的估計完成百分比、請將選項新增 `show-replicated-repair-status`至 repair 資料命令。
+
`repair-data show-replicated-repair-status`

* 若要判斷維修是否完成：
+
.. 選擇 *節點* > *_正在修復的儲存節點_* > *ILM*。
.. 檢閱「評估」區段中的屬性。當修復完成時、「*等待-全部*」屬性會指出0個物件。


* 若要更詳細地監控維修：
+
.. 選擇*節點*。
.. 選擇*網格名稱_*>* ILM *。
.. 將遊標放在 ILM 佇列圖上，查看 *掃描速率（物件/秒）* 屬性的值，該值是網格中物件被掃描並排隊等待 ILM 的速率。
.. 在 ILM 佇列部分中，查看以下屬性：
+
*** * 掃描週期 - 預估 * ：完成所有物件完整 ILM 掃描的預估時間。
+
全面掃描並不能保證 ILM 已套用於所有物件。

*** *嘗試修復*：針對被視為高風險的複製資料嘗試的物件修復操作的總數。高風險對像是任何僅剩一個副本的對象，無論是由 ILM 策略指定的還是由於副本遺失造成的。每次儲存節點嘗試修復高風險物件時，此計數都會增加。如果電網變得繁忙，則優先進行高風險的 ILM 修復。
+
如果修復後複製失敗，則相同物件修復可能會再次增加。 + 當您監控儲存節點磁碟區復原的進度時，這些屬性非常有用。如果嘗試修復的次數停止增加並且完整掃描已完成，則修復可能已完成。



.. 或者，提交 Prometheus 查詢 `storagegrid_ilm_scan_period_estimated_minutes`和 `storagegrid_ilm_repairs_attempted`。




--
.銷毀編碼（ EC ）資料
--
若要監控銷毀編碼資料的修復、然後重試任何可能失敗的要求：

. 判斷銷毀編碼資料修復的狀態：
+
** 選擇「*支援*」>「*工具*」>「*指標*」來查看目前作業的預計完成時間和完成百分比。然後，在 Grafana 部分中選擇 *EC Overview*。查看*Grid EC 作業預計完成時間*和*Grid EC 作業完成百分比*儀表板。
** 使用此命令查看特定作業的狀態 `repair-data`：
+
`repair-data show-ec-repair-status --repair-id repair ID`

** 使用此命令列出所有修復：
+
`repair-data show-ec-repair-status`

+
輸出會列出所有先前和目前正在執行的修復的資訊、包括 `repair ID`。



. 如果輸出顯示修復作業失敗、請使用 `--repair-id`選項重試修復。
+
此命令會使用修復ID 6949309319275667690、重試失敗的節點修復：

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
此命令會使用修復ID 6949309319275667690重試失敗的Volume修復：

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====