= 什麼是S3物件鎖定？
:allow-uri-read: 




== 什麼是S3物件鎖定？

「物件鎖定」功能是物件保護解決方案、StorageGRID 相當於Amazon Simple Storage Service（Amazon S3）中的S3物件鎖定。

當 StorageGRID 系統啟用全域 S3 物件鎖定設定時、 S3 租戶帳戶可以建立已啟用或未啟用 S3 物件鎖定的貯體。如果貯體已啟用 S3 物件鎖定、則需要設定貯體版本、而且會自動啟用。

* 沒有 S3 物件鎖定 * 的貯體只能有未指定保留設定的物件。任何擷取的物件都不會有保留設定。

* 具有 S3 物件鎖定 * 的儲存貯體可以有物件、無論是否有 S3 用戶端應用程式指定的保留設定。某些擷取的物件會有保留設定。

* 已設定 S3 物件鎖定和預設保留 * 的貯體、可以使用指定的保留設定來上傳物件、也可以不保留設定來上傳新物件。新物件會使用預設設定、因為尚未在物件層級設定保留設定。

有效地說、所有新擷取的物件在設定預設保留時都會有保留設定。沒有物件保留設定的現有物件不會受到影響。



=== 保留模式

StorageGRID S3 物件鎖定功能支援兩種保留模式、可將不同層級的保護套用至物件。這些模式相當於 Amazon S3 保留模式。

* 在法規遵循模式中：
+
** 直到達到物件的保留日期、才能刪除物件。
** 物件的保留日期可以增加、但不能減少。
** 直到達到該日期為止、才能移除物件的保留日期。


* 在治理模式中：
+
** 具有特殊權限的使用者可以在修改特定保留設定的要求中使用略過標頭。
** 這些使用者可以在達到物件版本的保留截止日期之前刪除物件版本。
** 這些使用者可以增加、減少或移除物件的保留到目前為止。






=== 物件版本的保留設定

如果在啟用 S3 物件鎖定的情況下建立貯體、使用者可以使用 S3 用戶端應用程式、針對新增至貯體的每個物件、選擇性地指定下列保留設定：

* * 保留模式 * ：法規遵循或治理。
* * 保留至日期 * ：如果物件版本的保留至未來日期、則可以擷取物件、但無法刪除。
* *合法持有*：將合法持有套用至物件版本、會立即鎖定該物件。例如、您可能需要對與調查或法律爭議相關的物件保留法律。合法持有沒有到期日、但在明確移除之前、仍會保留到位。合法持有不受保留至日期的限制。
+

NOTE: 如果物件處於合法保留狀態、則無論物件的保留模式為何、任何人都無法刪除該物件。

+
如需物件設定的詳細資料、請參閱link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]。





=== 貯體的預設保留設定

如果在啟用 S3 物件鎖定的情況下建立貯體、使用者可以選擇性地指定貯體的下列預設設定：

* * 預設保留模式 * ：法規遵循或治理。
* * 預設保留期間 * ：新增至此貯體的物件版本應保留多久、從新增物件之日起算。


預設的貯體設定僅適用於沒有自己保留設定的新物件。當您新增或變更這些預設設定時、現有的貯體物件不會受到影響。

請參閱link:../tenant/creating-s3-bucket.html["建立S3儲存區"]和link:../tenant/update-default-retention-settings.html["更新 S3 物件鎖定預設保留"]。
