---
permalink: tenant/creating-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create your own S3 access key 
summary: 如果您使用的是S3租戶、而且您擁有適當的權限、則可以建立自己的S3存取金鑰。您必須擁有存取金鑰才能存取您的貯體和物件。 
---
= 建立自己的S3存取金鑰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是S3租戶、而且您擁有適當的權限、則可以建立自己的S3存取金鑰。您必須擁有存取金鑰才能存取您的貯體和物件。

.開始之前
* 您可以使用登入租戶管理程式link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有的使用者群組link:tenant-management-permissions.html["管理您自己的 S3 認證或根存取權限"]。


.關於這項工作
您可以建立一或多個S3存取金鑰、以便為租戶帳戶建立及管理貯體。建立新的存取金鑰之後、請使用新的存取金鑰ID和秘密存取金鑰來更新應用程式。為了安全起見、請勿建立超出您所需的金鑰、並刪除您未使用的金鑰。如果您只有一個金鑰即將過期、請在舊金鑰過期之前建立新金鑰、然後刪除舊金鑰。

每個金鑰都可以有特定的到期時間、或是沒有到期時間。請遵循下列到期時間準則：

* 設定金鑰的到期時間、將存取限制在特定時間段內。如果您的存取金鑰ID和秘密存取金鑰意外暴露、設定短的到期時間有助於降低風險。過期的金鑰會自動移除。
* 如果環境中的安全風險較低、而且您不需要定期建立新金鑰、就不需要設定金鑰的到期時間。如果您決定稍後再建立新金鑰、請手動刪除舊金鑰。



CAUTION: 您可以使用租戶管理程式中顯示的帳戶存取金鑰ID和秘密存取金鑰、來存取屬於您帳戶的S3儲存區和物件。因此、請像保護密碼一樣保護存取金鑰。定期旋轉存取金鑰、從帳戶中移除任何未使用的金鑰、而且切勿與其他使用者共用。

.步驟
. 選擇*儲存設備（S3）*>*我的存取金鑰*。
+
「我的存取金鑰」頁面隨即出現、並列出任何現有的存取金鑰。

. 選取*建立金鑰*。
. 執行下列其中一項：
+
** 選取*不要設定到期時間*以建立不會過期的金鑰。（預設）
** 選取*設定到期時間*、然後設定到期日和時間。
+

NOTE: 到期日最長可為從目前日期算起的五年。到期時間最短可從目前時間開始一分鐘。



. 選取*建立存取金鑰*。
+
此時會出現「下載存取金鑰」對話方塊、列出您的存取金鑰ID和秘密存取金鑰。

. 將存取金鑰ID和秘密存取金鑰複製到安全位置、或選取*下載.csv*以儲存內含存取金鑰ID和秘密存取金鑰的試算表檔案。
+

CAUTION: 在複製或下載此資訊之前、請勿關閉此對話方塊。對話方塊關閉後、您無法複製或下載金鑰。

. 選擇*完成*。
+
新金鑰會列在「我的存取金鑰」頁面上。

. 如果您的租戶帳戶具有 * 使用網格同盟連線 * 權限、請選擇性使用租戶管理 API 、將 S3 存取金鑰從來源網格上的租戶手動複製到目的地網格上的租戶。請參閱。 link:grid-federation-clone-keys-with-api.html["使用 API 複製 S3 存取金鑰"]

