---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: 您可以使用租戶管理程式來建立S3儲存區以供物件資料使用。 
---
= 建立S3儲存區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用租戶管理程式來建立S3儲存區以供物件資料使用。

.開始之前
* 您可以使用登入租戶管理程式link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有 root 存取權或管理所有儲存區的使用者群組link:tenant-management-permissions.html["權限"]。這些權限會覆寫群組或儲存區原則中的權限設定。
+

NOTE: 可以授予設定或修改儲存區或物件之 S3 物件鎖定屬性的權限link:../s3/bucket-and-group-access-policies.html["庫位原則或群組原則"]。

* 如果您計畫為貯體啟用 S3 物件鎖定、則網格管理員已為 StorageGRID 系統啟用全域 S3 物件鎖定設定、而且您已檢閱 S3 物件鎖定貯體和物件的需求。
* 如果每個租戶都有 5 、 000 個貯體、則網格中的每個儲存節點至少有 64 GB 的 RAM 。
+

NOTE: 每個網格最多可有 100,000 個貯體link:../tenant/manage-branch-buckets.html["分公司庫存箱"]，包括。





== 存取精靈

.步驟
. 從儀表板選取 * 檢視貯體 * 、或選取 * 儲存空間（ S3 ） * > * 鏟斗 * 。
. 選取*建立桶*。




== 輸入詳細資料

.步驟
. 輸入貯體的詳細資料。
+
[cols="1a,3a"]
|===
| 欄位 | 說明 


 a| 
儲存區名稱
 a| 
符合以下規則的貯體名稱：

** 必須在各個StorageGRID 方面都是獨一無二的（不只是租戶帳戶內的獨特功能）。
** 必須符合DNS規範。
** 必須包含至少 3 個字元、不得超過 63 個字元。
** 每個標籤都必須以英文字母或數字開頭和結尾、而且只能使用英文字母、數字和連字號。
** 不得包含虛擬託管樣式要求的句點。期間會導致伺服器萬用字元憑證驗證發生問題。


如需詳細資訊，請參閱 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Amazon Web Services（AWS）儲存區命名規則文件"^]。

* 附註 * ：建立貯體後、您無法變更貯體名稱。



 a| 
區域
 a| 
貯體的區域。

您的系統管理員負責管理可用的區域。StorageGRID儲存區的區域可能會影響套用至物件的資料保護原則。依預設、所有貯體都會建立在區域中 `us-east-1`。

* 附註 * ：建立貯體後、您無法變更區域。

|===
. 選擇*繼續*。




== 管理設定

.步驟
. 或者、為儲存區啟用物件版本管理。
+
如果您要儲存此儲存區中每個物件的每個版本、請啟用物件版本管理。然後您可以視需要擷取物件的舊版。

+
在下列情況下，您必須啟用物件版本設定：

+
** 貯體將用於跨網格複寫。
** 您想要從此貯體建立link:../tenant/manage-branch-buckets.html["分支庫位"]。


. 如果啟用全域 S3 物件鎖定設定、則可選擇性啟用儲存區的 S3 物件鎖定、以使用一次寫入多讀（ WORM ）模式來儲存物件。
+
只有當您需要保留物件一段固定時間（例如、為了符合特定法規要求）時、才需要為貯體啟用 S3 物件鎖定。S3 物件鎖定是一項永久性設定、可協助您防止物件在固定的時間內或無限期地遭到刪除或覆寫。

+

CAUTION: 為貯體啟用 S3 物件鎖定設定之後、就無法停用該設定。擁有正確權限的任何人都可以將無法變更的物件新增至此貯體。您可能無法刪除這些物件或貯體本身。

+
如果您為儲存區啟用S3物件鎖定、則會自動啟用儲存區版本設定。

. 如果您選取 * 啟用 S3 物件鎖定 * 、則可選擇性啟用此貯體的 * 預設保留 * 。
+

NOTE: 您的網格管理員必須授予您權限link:../tenant/using-s3-object-lock.html["使用 S3 物件鎖定的特定功能"]。

+
啟用 * 預設保留 * 時、新增至貯體的新物件將會自動受到保護、不被刪除或覆寫。「 * 預設保留 * 」設定不會套用至具有其本身保留期間的物件。

+
.. 如果啟用 * 預設保留 * 、請為貯體指定 * 預設保留模式 * 。
+
[cols="1a,2a"]
|===
| 預設保留模式 | 說明 


 a| 
治理
 a| 
*** 擁有權限的使用者 `s3:BypassGovernanceRetention`可以使用 `x-amz-bypass-governance-retention: true`要求標頭來略過保留設定。
*** 這些使用者可以在達到物件版本的保留截止日期之前刪除物件版本。
*** 這些使用者可以增加、減少或移除物件的保留到目前為止。




 a| 
法規遵循
 a| 
*** 直到達到物件的保留日期、才能刪除物件。
*** 物件的保留日期可以增加、但不能減少。
*** 直到達到該日期為止、才能移除物件的保留日期。


* 注意 * ：您的網格管理員必須允許您使用法規遵循模式。

|===
.. 如果啟用 * 預設保留 * 、請指定貯體的 * 預設保留期間 * 。
+
「 * 預設保留期間 * 」表示新增至此貯體的物件應保留多久、從擷取開始算起。指定小於或等於租用戶保留期間上限的值、如網格管理員所設定。

+
網格管理員建立租戶時、會設定 _ 最大 _ 保留期間（可為 1 天至 100 年）。當您設定 _default_ 保留期間時、其值不得超過保留期間上限的設定值。如有需要、請要求您的網格管理員增加或縮短最長保留期間。



. [[capity-limit ]] （選擇性）選取 * 啟用容量限制 * ，輸入值，然後選取容量單位。
+
容量上限是此貯體物件可用的最大容量。此值代表邏輯數量（物件大小）、而非實體數量（磁碟大小）。

+
如果未設定上限、則此貯體的容量是無限的。如需詳細資訊、請參閱 link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量限制使用率"] 。

. [[object-count-limit ]] （選擇性）選取 * 啟用物件數限制 * ，然後輸入一個至少 1 且不超過 1 ， 000 ， 000 ， 000 ， 000 ， 000 ， 000 ， 000 ， 000 ， 000 ， 000 ， 000 ， 000 ， 000 。
+
物件數上限是此貯體可包含的物件數上限。此值代表邏輯數量（物件數）。如果未設定限制，則物件數是無限的。

. 選取*建立桶*。
+
此庫位會建立並新增至「庫位」頁面上的表格。

. 您也可以選擇 * 移至貯體詳細資料頁面 * 、以link:viewing-s3-bucket-details.html["檢視貯體詳細資料"]執行其他組態。


您也可以link:../tenant/manage-branch-buckets.html["建立分行庫存箱"]視需要進行。
