---
permalink: tenant/creating-groups-for-swift-tenant.html 
sidebar: sidebar 
keywords: how to create Swift tenant groups 
summary: 您可以匯入聯盟群組或建立本機群組、來管理Swift租戶帳戶的存取權限。至少一個群組必須具有Swift Administrator權限、這是管理Swift租戶帳戶的容器和物件所需的權限。 
---
= 為Swift租戶建立群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以匯入聯盟群組或建立本機群組、來管理Swift租戶帳戶的存取權限。至少一個群組必須具有Swift Administrator權限、這是管理Swift租戶帳戶的容器和物件所需的權限。


NOTE: Swift 用戶端應用程式的支援已過時、未來版本將會移除。

.開始之前
* 您可以使用登入租戶管理程式link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有的使用者群組link:tenant-management-permissions.html["root 存取權限"]。
* 如果您計畫匯入同盟群組、則您擁有link:using-identity-federation.html["已設定的身分識別聯盟"]、且同盟群組已存在於已設定的身分識別來源中。




== 存取建立群組精靈

.步驟
第一步是存取「建立群組」精靈。

. 選擇*存取管理*>*群組*。
. 選取*建立群組*。




== 選擇群組類型

您可以建立本機群組或匯入同盟群組。

.步驟
. 選取*本機群組*索引標籤以建立本機群組、或選取*聯盟群組*索引標籤、從先前設定的身分識別來源匯入群組。
+
如果StorageGRID 您的系統啟用單一登入（SSO）、屬於本機群組的使用者將無法登入租戶管理程式、不過他們可以根據群組權限、使用用戶端應用程式來管理租戶的資源。

. 輸入群組名稱。
+
** *本機群組*：輸入顯示名稱和唯一名稱。您可以稍後再編輯顯示名稱。
** *聯盟群組*：輸入唯一名稱。對於 Active Directory 、唯一名稱是與屬性相關的名稱 `sAMAccountName`。對於 OpenLDAP 、唯一名稱是與屬性相關聯的名稱 `uid`。


. 選擇*繼續*。




== 管理群組權限

群組權限可控制使用者可在租戶管理器和租戶管理 API 中執行的工作。

.步驟
. 對於 * 存取模式 * 、請選取下列其中一項：
+
** * 讀寫 * （預設）：使用者可以登入租戶管理員並管理租戶組態。
** *唯讀*：使用者只能檢視設定和功能。他們無法在租戶管理員或租戶管理 API 中進行任何變更或執行任何作業。本機唯讀使用者可以變更自己的密碼。
+

NOTE: 如果使用者屬於多個群組、且任何群組設定為唯讀、則使用者將擁有所有選取設定和功能的唯讀存取權。



. 如果群組使用者需要登入租戶管理員或租戶管理 API 、請選取 * 根存取 * 核取方塊。
. 選擇*繼續*。




== 設定 Swift 群組原則

Swift 使用者需要系統管理員權限才能驗證 Swift REST API 、以建立容器和擷取物件。

. 如果群組使用者需要使用 Swift REST API 來管理容器和物件、請選取 * Swift 管理員 * 核取方塊。
. 如果您要建立本機群組、請選取*繼續*。如果您要建立聯盟群組、請選取*建立群組*和*完成*。




== 新增使用者（僅限本機群組）

您可以儲存群組而不新增使用者、也可以選擇性地新增已存在的任何本機使用者。

.步驟
. 您也可以為此群組選取一或多個本機使用者。
+
如果您尚未建立本機使用者、可以在「使用者」頁面上將此群組新增至使用者。請參閱。 link:../tenant/managing-local-users.html["管理本機使用者"]

. 選擇* Create group（創建組）*和* Finish（完成）*。
+
您建立的群組會出現在群組清單中。


