---
permalink: tenant/deleting-s3-bucket.html 
sidebar: sidebar 
keywords: how to delete S3 bucket 
summary: 您可以使用租戶管理程式刪除空的S3儲存區。 
---
= 刪除S3儲存區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用租戶管理程式刪除一或多個空的S3儲存區。

.開始之前
* 您可以使用登入租戶管理程式link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有的使用者群組link:tenant-management-permissions.html["管理所有貯體或根目錄存取權限"]。這些權限會覆寫群組或儲存區原則中的權限設定。
* 您要刪除的儲存區是空的。如果您要刪除的貯體不是空的，link:../tenant/deleting-s3-bucket-objects.html["刪除貯體中的物件"]。


.關於這項工作
這些指示說明如何使用租戶管理程式刪除S3儲存區。您也可以使用或刪除 S3 儲存區link:understanding-tenant-management-api.html["租戶管理API"]link:../s3/operations-on-buckets.html["S3 REST API"]。

如果 S3 儲存區包含物件、非目前物件版本或刪除標記、則無法刪除該儲存區。如需如何刪除 S3 版本化物件的相關資訊，請參閱link:../ilm/how-objects-are-deleted.html["如何刪除物件"]。

.步驟
. 從儀表板選取 * 檢視貯體 * 、或選取 * 儲存空間（ S3 ） * > * 鏟斗 * 。
+
此時會顯示「庫位」頁面、並顯示所有現有的S3庫位。

. 使用 * 動作 * 功能表或特定儲存庫的詳細資料頁面。
+
[role="tabbed-block"]
====
.「行動」功能表
--
.. 選取您要刪除的每個貯體的核取方塊。
.. 選取 * 動作 * > * 刪除儲存區 * 。


--
.詳細資料頁面
--
.. 選取貯體名稱以顯示其詳細資料。
.. 選取 * 刪除儲存庫 * 。


--
====
. 當確認對話方塊出現時、請選取 * 是 * 。
+
確認每個儲存區都是空的、然後刪除每個儲存區。StorageGRID此作業可能需要幾分鐘的時間。

+
如果儲存區不是空的、就會出現錯誤訊息。您必須link:../tenant/deleting-s3-bucket-objects.html["刪除貯體中的所有物件和任何刪除標記"]先刪除貯體、才能刪除該貯體。


