---
permalink: tenant/enable-cross-origin-resource-sharing-for-management-interface.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors, management, api, domain 
summary: 如果您想要使用管理 API 將 StorageGRID 中的資料存取至另一個網域，您可以啟用跨來源資源共用（ CORS ），以進行 StorageGRID 的管理 API 要求。 
---
= 為管理介面啟用 StorageGRID CORS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要使用管理 API 將 StorageGRID 中的資料存取至另一個網域，您可以啟用跨來源資源共用（ CORS ），以進行 StorageGRID 的管理 API 要求。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* link:tenant-management-permissions.html["root 存取權限"]可存取所有 CORS 組態要求。


.關於這項工作
CORS 是一種安全機制，可讓一個網域中的用戶端 Web 應用程式存取不同網域中的資源。例如，假設您要在域中爲 StorageGRID 構建監控儀表板 `\http://www.example.com`。StorageGRID 網域在 StorageGRID for 和「 Grid Manager 」中啟用 CORS ，即可 `\http://www.example.com`回應來自的網格管理 API 要求 `\http://www.example.com`。

CORS 支援具有或 `multipart/formdata`要求的 `Content-Type`管理 API （ mgmt-API ）要求 `application/json`。

.步驟
. 在 StorageGRID 組態頁面的 * 網路 * 下，選取 * 管理介面 CORS 設定 * 。
. 選擇 * Grid Manager* ， * Tenant Manager* 或兩者選項。
+
** * Grid Manager* ：啟用 CORS 以處理跨網域 Grid Management API 要求。
** * 租戶管理器 * ：啟用 CORS 以處理跨網域租戶管理 API 要求。


. 在 * 網域 * 欄位中輸入其他網域的 URL 。
+
如果要在 StorageGRID 中針對多個網域啟用 CORS ，請選取 * 新增其他網域 * 。

. 選擇*保存*。


.相關資訊
link:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["為貯體和物件設定 StorageGRID CORS"]
