---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: 當網格管理員建立StorageGRID 資訊生命週期管理（ILM）規則以供選用時、他們可以選擇性地指定物件的上次存取時間、以決定是否要將該物件移至不同的儲存位置。如果您使用的是S3租戶、您可以針對S3儲存區中的物件啟用上次存取時間更新、藉此充分利用這類規則。 
---
= 啟用或停用上次存取時間更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當網格管理員為StorageGRID 某個系統建立資訊生命週期管理（ILM）規則時、他們可以選擇性地指定物件的上次存取時間、以決定是否要將該物件移到不同的儲存位置。如果您使用的是S3租戶、您可以針對S3儲存區中的物件啟用上次存取時間更新、藉此充分利用這類規則。

這些指示僅適用於至少包含一個 ILM 規則的 StorageGRID 系統、該規則使用 * 上次存取時間 * 選項作為進階篩選器或參考時間。如果您的支援系統不包含此類規則、您可以忽略這些指示StorageGRID 。如需詳細資訊、請參閱 link:../ilm/using-last-access-time-in-ilm-rules.html["在 ILM 規則中使用上次存取時間"] 。

.開始之前
* 您可以使用登入租戶管理程式link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有的使用者群組link:tenant-management-permissions.html["管理所有貯體或根目錄存取權限"]。這些權限會覆寫群組或儲存區原則中的權限設定。


.關於這項工作
* 上次存取時間 * 是 ILM 規則的 * 參考時間 * 放置指示可用的選項之一。將規則的參考時間設為上次存取時間、可讓網格管理員根據上次擷取（讀取或檢視）物件的時間、指定物件放置在特定儲存位置。

例如、為了確保最近檢視的物件仍保留在較快的儲存空間、網格管理員可以建立ILM規則、指定下列項目：

* 過去一個月擷取的物件應保留在本機儲存節點上。
* 過去一個月未擷取的物件應移至異地位置。


根據預設、上次存取時間的更新會停用。如果您的 StorageGRID 系統包含使用 * 上次存取時間 * 選項的 ILM 規則、且您想要將此選項套用至此儲存庫中的物件、則必須針對該規則中指定的 S3 儲存區、啟用更新至上次存取時間。


CAUTION: 更新上次擷取物件的存取時間、可能會降低StorageGRID 功能性、尤其是小型物件的效能。

上次存取時間更新會影響效能、因為StorageGRID 每次擷取物件時、VMware都必須執行下列額外步驟：

* 使用新的時間戳記更新物件
* 將物件新增至ILM佇列、以便根據目前的ILM規則和原則重新評估


下表摘要說明上次存取時間停用或啟用時、套用至儲存區中所有物件的行為。

[cols="1a,1a,1a,1a,1a"]
|===


.2+| 申請類型 2+| 停用上次存取時間時的行為（預設） 2+| 啟用上次存取時間時的行為 


| 上次存取時間已更新？ | 新增至ILM評估佇列的物件？ | 上次存取時間已更新？ | 新增至ILM評估佇列的物件？ 


 a| 
發出 HEAD 操作時請求擷取物件的元數據
 a| 
否
 a| 
否
 a| 
否
 a| 
否



 a| 
要求擷取物件、其存取控制清單或其中繼資料
 a| 
否
 a| 
否
 a| 
是的
 a| 
是的



 a| 
要求更新物件的中繼資料
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
要求列出物件或物件版本
 a| 
否
 a| 
否
 a| 
否
 a| 
否



 a| 
要求將物件從一個儲存區複製到另一個儲存區
 a| 
* 否、來源複本
* 是、適用於目的地複本

 a| 
* 否、來源複本
* 是、適用於目的地複本

 a| 
* 是、來源複本
* 是、適用於目的地複本

 a| 
* 是、來源複本
* 是、適用於目的地複本




 a| 
要求完成多部分上傳
 a| 
是的、適用於組裝好的物件
 a| 
是的、適用於組裝好的物件
 a| 
是的、適用於組裝好的物件
 a| 
是的、適用於組裝好的物件

|===
.步驟
. 從儀表板選取 * 檢視貯體 * 、或選取 * 儲存空間（ S3 ） * > * 鏟斗 * 。
. 從表格中選取貯體名稱。
+
此時會顯示「庫位詳細資料」頁面。

. 從 *Bucket options* 標籤中、選取 * 上次存取時間更新 * 手風琴。
. 啟用或停用上次存取時間更新。
. 選取*儲存變更*。

