---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: '租用戶帳戶可讓您使用簡單儲存服務 (S3) REST API 在StorageGRID系統中儲存和擷取物件。' 
---
= 使用租戶帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租戶帳戶可讓您使用簡易儲存服務（ S3 ） REST API 來儲存及擷取 StorageGRID 系統中的物件。



== 什麼是租戶帳戶？

每個租戶帳戶都有自己的同盟或本機群組、使用者、 S3 貯體和物件。

租戶帳戶可用來分隔不同實體所儲存的物件。例如、多個租戶帳戶可用於下列任一使用案例：

* *企業使用案例：* StorageGRID 如果在企業內部使用此功能、則網格的物件儲存設備可能會由組織內的不同部門加以分隔。例如、行銷部門、客戶支援部門、人力資源部門等可能有租戶帳戶。
+

NOTE: 如果您使用 S3 用戶端協議，您也可以使用 S3 儲存桶和儲存桶策略在企業各部門之間隔離物件。您不需要建立單獨的租用戶帳戶。請參閱實施說明link:../s3/use-access-policies.html["S3 貯體和貯體原則"]了解更多。

* *服務供應商使用案例：* StorageGRID 如果服務供應商正在使用此功能、則網格的物件儲存設備可能會由租用儲存設備的不同實體加以分隔。例如、公司A、公司B、公司C等可能有租戶帳戶。




== 如何建立租戶帳戶

租戶帳戶是由建立link:../admin/managing-tenants.html["使用Grid Manager的網格管理員StorageGRID"]的。建立租戶帳戶時、網格管理員會指定下列項目：

* 基本資訊、包括租戶名稱、用戶端類型（ S3 ）和選用的儲存配額。
* 租戶帳戶的權限、例如租戶帳戶是否可以使用 S3 平台服務、設定自己的身分識別來源、使用 S3 Select 或使用網格同盟連線。
* 租戶的初始根存取權、取決於 StorageGRID 系統是使用本機群組和使用者、身分識別聯盟或單一登入（ SSO ）。


此外、如果StorageGRID S3租戶帳戶需要符合法規要求、網格管理員也可以針對該系統啟用S3物件鎖定設定。啟用S3物件鎖定時、所有S3租戶帳戶都能建立及管理相容的儲存區。



=== 設定S3租戶

之後link:../admin/creating-tenant-account.html["S3租戶帳戶已建立"]、您可以存取租戶管理程式來執行下列工作：

* 設定身分識別聯盟（除非身分識別來源與網格共用）
* 管理群組和使用者
* 使用網格同盟進行帳戶複製和跨網格複寫
* 管理S3存取金鑰
* 建立及管理 S3 儲存區
* 使用 S3 平台服務
* 使用S3 Select
* 監控儲存使用量



TIP: 雖然您可以使用租戶管理程式來建立和管理 S3 貯體、但您必須使用link:../s3/index.html["S3用戶端"]或link:use-s3-console.html["S3 主控台"]來擷取和管理物件。
