---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: 分支庫位可讓您存取貯體中的物件，只要它們仍存在於貯體中，就如同它們在特定時間存在一樣。使用 Tenant Manager 來建立和檢視分公司貯體。 
---
= 管理分行庫存箱
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
分支庫位可讓您存取貯體中的物件，只要它們仍存在於貯體中，就如同它們在特定時間存在一樣。使用 Tenant Manager 來建立和檢視分公司貯體。

分支儲存區可存取受保護的資料，但無法作為備份。若要繼續保護資料，請在基礎貯體上使用下列功能：

* link:../tenant/using-s3-object-lock.html["S3物件鎖定"]
* link:../admin/grid-federation-what-is-cross-grid-replication.html["跨網格複寫"]適用於基礎鏟斗
* link:../tenant/manage-bucket-policy.html["貯體原則"]用於清理舊物件版本的版本


.關於這項工作
您可以從現有的貯體建立分支貯體。建立分支貯體之後，其建立來源的原始貯體稱為基礎貯體。此外，您也可以從其他分行庫位建立分行庫位。當您在基礎貯體上執行作業時，分支貯體的結果取決於您所建立的作業和分支貯體類型。

您可以使用分支貯體來移除毀損的物件，方法是在毀損發生前的某個時間點建立分支貯體，然後將應用程式指向分支貯體，而非指向含有毀損物件的基礎貯體。


CAUTION: 分支庫位並不做為備份，但可存取受保護的資料。您必須繼續使用link:../ilm/managing-objects-with-s3-object-lock.html["S3物件鎖定"]或link:../admin/grid-federation-what-is-cross-grid-replication.html["跨網格複寫"]保護資料。

分支貯體不支援跨網格複寫。

.開始之前
* 您已使用登入租戶管理程式link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有 root 存取權或管理所有儲存區的使用者群組link:tenant-management-permissions.html["權限"]。這些權限會覆寫群組或儲存區原則中的權限設定。
* 您想要從中建立分支的基礎貯體有link:../tenant/changing-bucket-versioning.html["已啟用版本設定"]。
* 您是基礎貯體的擁有者。
+

NOTE: 可以授予設定或修改儲存區或物件之 S3 物件鎖定屬性的權限link:../s3/bucket-and-group-access-policies.html["庫位原則或群組原則"]。





== 建立分公司貯體

.步驟
. 從儀表板選取 * 檢視貯體 * 、或選取 * 儲存空間（ S3 ） * > * 鏟斗 * 。
. 選取您要從中建立分支的貯體（「基礎貯體」）。
. 在「庫位詳細資料」頁面上，選取 * 分支 * > * 建立分支庫位 * 。
+
如果基礎貯體未啟用版本設定，則會停用 * 建立分支貯體 * 按鈕。





== 輸入詳細資料

.步驟
. 輸入分行庫位的詳細資料。
+
[cols="1a,3a"]
|===
| 欄位 | 說明 


 a| 
分支庫位名稱
 a| 
符合以下規則的分支庫位名稱：

** 必須在各個StorageGRID 方面都是獨一無二的（不只是租戶帳戶內的獨特功能）。
** 必須符合DNS規範。
** 必須包含至少 3 個字元、不得超過 63 個字元。
** 每個標籤都必須以英文字母或數字開頭和結尾、而且只能使用英文字母、數字和連字號。
** 不得包含虛擬託管樣式要求的句點。期間會導致伺服器萬用字元憑證驗證發生問題。


如需詳細資訊，請參閱 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Amazon Web Services（AWS）儲存區命名規則文件"^]。

* 附註 * ：建立分行庫位後，您無法變更名稱。



 a| 
區域（無法修改分行庫存箱）
 a| 
分行庫位的區域。

分支庫位的區域必須符合基礎貯體的區域，因此分支庫位的此欄位會停用。



 a| 
在時間之前
 a| 
從分支庫位可存取的基礎貯體中所建立物件版本的截止時間。分支庫位可讓您存取早於之前建立的物件版本。



 a| 
分支貯體類型
 a| 
** * 讀寫 * ：您可以在分支儲存區中新增或刪除物件或物件版本。
** * 唯讀 * ：您無法修改分支儲存區中的物件。


|===
. 選擇*繼續*。




== 管理設定

分支貯體的設定不會影響基礎貯體中的物件版本。

.步驟
. 如果已啟用全域 S3 物件鎖定設定，則可選擇性地為分支儲存區啟用 S3 物件鎖定。若要啟用 S3 物件鎖定，分支貯體必須是讀寫貯體。
+
只有當您需要保留物件一段固定時間（例如，為了符合特定法規要求）時，才需啟用分支貯體的 S3 物件鎖定。S3 物件鎖定是一項永久性設定、可協助您防止物件在固定的時間內或無限期地遭到刪除或覆寫。

+

CAUTION: 為貯體啟用 S3 物件鎖定設定之後、就無法停用該設定。擁有正確權限的任何人都可以將物件新增至無法變更的分支庫位。您可能無法刪除這些物件或分支庫位本身。

. 如果您選取 * 啟用 S3 物件鎖定 * ，則可選擇性啟用分支儲存區的 * 預設保留 * 。
+

NOTE: 您的網格管理員必須授予您權限link:../tenant/using-s3-object-lock.html["使用 S3 物件鎖定的特定功能"]。

+
啟用 * 預設保留 * 時，新增至分支儲存區的新物件將會自動受到保護，不被刪除或覆寫。「 * 預設保留 * 」設定不會套用至具有其本身保留期間的物件。

+
.. 如果啟用 * 預設保留 * ，請為分支儲存區指定 * 預設保留模式 * 。
+
[cols="1a,2a"]
|===
| 預設保留模式 | 說明 


 a| 
治理
 a| 
*** 擁有權限的使用者 `s3:BypassGovernanceRetention`可以使用 `x-amz-bypass-governance-retention: true`要求標頭來略過保留設定。
*** 這些使用者可以在達到物件版本的保留截止日期之前刪除物件版本。
*** 這些使用者可以增加、減少或移除物件的保留到目前為止。




 a| 
法規遵循
 a| 
*** 直到達到物件的保留日期、才能刪除物件。
*** 物件的保留日期可以增加、但不能減少。
*** 直到達到該日期為止、才能移除物件的保留日期。


* 注意 * ：您的網格管理員必須允許您使用法規遵循模式。

|===
.. 如果啟用 * 預設保留 * ，請指定分行庫位的 * 預設保留期間 * 。
+
「 * 預設保留期間 * 」表示從擷取新物件開始，新增至分支儲存區的新物件應保留多久。指定小於或等於租用戶保留期間上限的值、如網格管理員所設定。

+
網格管理員建立租戶時、會設定 _ 最大 _ 保留期間（可為 1 天至 100 年）。當您設定 _default_ 保留期間時、其值不得超過保留期間上限的設定值。如有需要、請要求您的網格管理員增加或縮短最長保留期間。



. [[capity-limit ]] （選擇性）選取 * 啟用容量限制 * 。
+
容量上限是分支貯體的最大可用容量。此值代表邏輯數量（物件大小）、而非實體數量（磁碟大小）。

+
如果未設定限制，則分支貯體的容量是無限的。如需詳細資訊、請參閱 link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量限制使用率"] 。

+

NOTE: 此設定僅適用於直接擷取至分支貯體的物件，而不適用於透過分支貯體從基礎貯體可見的物件。

. （可選）選擇 * 啓用對象數限制 * 。
+
物件數上限是指分支庫位可包含的物件數上限。此值代表邏輯數量（物件數）。如果未設定限制，則物件數是無限的。

+

NOTE: 此設定僅適用於直接擷取至分支貯體的物件，而不適用於透過分支貯體從基礎貯體可見的物件。

. 選取*建立桶*。
+
分行庫位會建立並新增至「庫位」頁面上的表格。

. 您也可以選擇 * 移至貯體詳細資料頁面 * 、以link:viewing-s3-bucket-details.html["檢視分行庫位詳細資料"]執行其他組態。
+
在「貯體詳細資料」頁面上，部分與修改物件相關的組態選項會停用於唯讀貯體。


