---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: 使用租戶管理器建立和查看分支儲存桶的詳細資訊。 
---
= 管理分支儲存桶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用租戶管理器建立和查看分支儲存桶的詳細資訊。

.開始之前
* 您已使用link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有 Root 存取權限的使用者群組，或者link:tenant-management-permissions.html["管理所有貯體權限"]。這些權限將覆蓋群組或儲存桶策略中的權限設定。
* 您要從中建立分支的基本儲存桶具有link:../tenant/changing-bucket-versioning.html["已啟用版本控制"]。
* 您是基本儲存桶的擁有者。


.關於這項工作
請注意分支儲存桶的以下資訊：

* 設定儲存桶或物件的 S3 物件鎖定屬性的權限可以透過以下方式授予link:../s3/use-access-policies.html["庫位原則或群組原則"]。
* 如果您暫停對基本儲存桶進行版本控制，則基本儲存桶的內容將不再在其分支儲存桶中可見。



CAUTION: 配置並建立分支儲存桶後，您無法變更該配置。



== 建立分支儲存桶

.步驟
. 從儀表板選取 * 檢視貯體 * 、或選取 * 儲存空間（ S3 ） * > * 鏟斗 * 。
. 選擇要從中建立分支的儲存桶（「基本儲存桶」）。
. 在儲存桶詳情頁面，選擇*分支* > *建立分支儲存桶*。
+
如果基本儲存桶未啟用版本控制，則「建立分支儲存桶」按鈕將會停用。





== 輸入詳細資料

.步驟
. 輸入分支儲存桶的詳細資訊。
+
[cols="1a,3a"]
|===
| 欄位 | 說明 


 a| 
分支儲存桶名稱
 a| 
符合以下規則的分支儲存桶的名稱：

** 必須在各個StorageGRID 方面都是獨一無二的（不只是租戶帳戶內的獨特功能）。
** 必須符合DNS規範。
** 必須包含至少 3 個字元、不得超過 63 個字元。
** 每個標籤都必須以英文字母或數字開頭和結尾、而且只能使用英文字母、數字和連字號。
** 不得包含虛擬託管樣式要求的句點。期間會導致伺服器萬用字元憑證驗證發生問題。


如需詳細資訊，請參閱 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Amazon Web Services（AWS）儲存區命名規則文件"^]。

*注意*：建立分支儲存桶後，您無法變更名稱。



 a| 
區域（無法修改分支儲存桶）
 a| 
分支儲存桶的區域。

分支儲存桶的區域必須與基本儲存桶的區域匹配，因此此欄位對於分支儲存桶是停用的。



 a| 
時間之前
 a| 
可從分支儲存桶存取在基礎儲存桶中建立的物件版本的截止時間。分支儲存桶提供對早於先前時間創建的物件版本的存取。

之前時間必須是已經過去的日期和時間。它不能是未來的日期。



 a| 
分支桶類型
 a| 
** *讀寫*：您可以在分支儲存桶中新增或刪除物件或物件版本。
** *只讀*：您不能修改分支儲存桶中的物件。


*注意*：僅當分支儲存桶為空時，您才可以將分支儲存桶類型設定為唯讀。如果現有分支儲存桶的類型設定為讀寫，而您尚未寫入，則可以將類型變更為唯讀。

|===
. 選擇*繼續*。




== 管理對象設定（可選）

分支儲存桶的物件設定不會影響基礎儲存桶中的物件版本。

.步驟
. 如果啟用了全域 S3 物件鎖定設置，則可以選擇為分支儲存桶啟用 S3 物件鎖定。若要啟用 S3 物件鎖，分支儲存桶必須是讀寫儲存桶。
+
只有當您需要將物件保留一段固定的時間（例如，為了滿足某些監管要求）時，才為分支儲存桶啟用 S3 物件鎖定。  S3 物件鎖定是一種永久性設置，可協助您防止物件在固定時間內或無限期內被刪除或覆蓋。

+

CAUTION: 一旦為儲存桶啟用 S3 物件鎖定設置，就無法停用它。任何擁有正確權限的人都可以將物件新增到無法更改的分支儲存桶中。您可能無法刪除這些物件或分支儲存桶本身。

. 如果您選擇了“啟用 S3 物件鎖定”，則可以選擇為分支儲存桶啟用“預設保留”。
+

NOTE: 您的網格管理員必須授予您權限link:../tenant/using-s3-object-lock.html["使用 S3 物件鎖定的特定功能"]。

+
當啟用*預設保留*時，新增至分支儲存桶的新物件將自動受到保護，免遭刪除或覆蓋。  *預設保留*設定不適用於具有自己的保留期的物件。

+
.. 如果啟用了*預設保留*，請為分支儲存桶指定*預設保留模式*。
+
[cols="1a,2a"]
|===
| 預設保留模式 | 說明 


 a| 
治理
 a| 
*** 擁有權限的使用者 `s3:BypassGovernanceRetention`可以使用 `x-amz-bypass-governance-retention: true`要求標頭來略過保留設定。
*** 這些使用者可以在達到物件版本的保留截止日期之前刪除物件版本。
*** 這些使用者可以增加、減少或移除物件的保留到目前為止。




 a| 
法規遵循
 a| 
*** 直到達到物件的保留日期、才能刪除物件。
*** 物件的保留日期可以增加、但不能減少。
*** 直到達到該日期為止、才能移除物件的保留日期。


* 注意 * ：您的網格管理員必須允許您使用法規遵循模式。

|===
.. 如果啟用了*預設保留*，請指定分支儲存桶的*預設保留期*。
+
*預設保留期*表示從提取新物件開始，新增至分支儲存桶中的新物件應保留多長時間。指定一個小於或等於網格管理員設定的租用戶最大保留期的值。

+
網格管理員建立租戶時、會設定 _ 最大 _ 保留期間（可為 1 天至 100 年）。當您設定 _default_ 保留期間時、其值不得超過保留期間上限的設定值。如有需要、請要求您的網格管理員增加或縮短最長保留期間。



. 或者，選擇“啟用容量限制”。
+
容量限制是分支桶可用的最大容量。該值代表邏輯量（物件大小），而不是物理量（磁碟上的大小）。

+
如果沒有設定限制，則分支桶的容量是無限的。請參閱link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量限制使用率"]了解更多。

+

NOTE: 此設定僅適用於直接提取到分支儲存桶中的對象，而不適用於透過分支儲存桶從基礎儲存桶中可見的對象。

. 或者，選擇“啟用物件計數限制”。
+
物件計數限制是分支儲存桶可以包含的最大物件數。該值代表邏輯數量（物件計數）。如果沒有設定限制，則物件數量不受限制。

+

NOTE: 此設定僅適用於直接提取到分支儲存桶中的對象，而不適用於透過分支儲存桶從基礎儲存桶中可見的對象。

. 選取*建立桶*。
+
分支儲存桶已建立並新增至「儲存桶」頁面上的表格中。

. 或者，選擇“前往儲存桶詳細資料頁面”link:viewing-s3-bucket-details.html["查看分支存儲桶詳細信息"]並執行額外的配置。
+
在 Bucket 詳情頁面，對於唯讀 Bucket，一些與修改物件相關的設定選項已停用。


