---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 建立租戶群組之前、請先考量您要指派給該群組的權限。租戶管理權限可決定使用者可以使用租戶管理程式或租戶管理API執行哪些工作。使用者可以屬於一或多個群組。如果使用者屬於多個群組、則權限是累積性的。 
---
= 租戶管理權限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立租戶群組之前、請先考量您要指派給該群組的權限。租戶管理權限可決定使用者可以使用租戶管理程式或租戶管理API執行哪些工作。使用者可以屬於一或多個群組。如果使用者屬於多個群組、則權限是累積性的。

若要登入租戶管理程式或使用租戶管理API、使用者必須屬於至少擁有一項權限的群組。所有可以登入的使用者都可以執行下列工作：

* 檢視儀表板
* 變更自己的密碼（適用於本機使用者）


對於所有權限、群組的存取模式設定會決定使用者是否可以變更設定及執行作業、或是只能檢視相關設定和功能。


NOTE: 如果使用者屬於多個群組、且任何群組設定為唯讀、則使用者將擁有所有選取設定和功能的唯讀存取權。

您可以為群組指派以下權限。

[cols="1a,3a,3a"]
|===
| 權限 | 說明 | 詳細資料 


 a| 
root存取權
 a| 
提供租戶管理程式和租戶管理API的完整存取權限。
 a| 



 a| 
管理您自己的 S3 認證
 a| 
可讓使用者建立及移除自己的S3存取金鑰。
 a| 
沒有此權限的使用者不會看到 * 儲存設備（ S3 ） * > * My S3 存取鍵 * 功能表選項。



 a| 
檢視所有貯體
 a| 
允許使用者查看所有儲存桶和儲存桶配置。
 a| 
沒有「檢視所有貯體」或「管理所有貯體」權限的使用者、將不會看到「 *buckets 」功能表選項。

此權限已被「管理所有儲存桶」權限取代。它不會影響 S3 用戶端或 S3 控制台使用的 S3 儲存桶或群組原則。



 a| 
管理所有貯體
 a| 
允許使用者使用租用戶管理器和租用戶管理 API 建立和刪除 S3 儲存桶並管理租用戶帳戶中所有 S3 儲存桶的設置，而無需考慮 S3 儲存桶或群組原則。
 a| 
沒有「檢視所有貯體」或「管理所有貯體」權限的使用者、將不會看到「 *buckets 」功能表選項。

此權限取代了查看所有儲存桶的權限。它不會影響 S3 用戶端或 S3 控制台使用的 S3 儲存桶或群組原則。



 a| 
管理端點
 a| 
可讓使用者使用租戶管理器或租戶管理 API 來建立或編輯平台服務端點、這些端點是 StorageGRID 平台服務的目的地。
 a| 
沒有此權限的使用者不會看到 * 平台服務端點 * 功能表選項。



 a| 
使用 S3 Console 標籤
 a| 
與「檢視所有貯體」或「管理所有貯體」權限結合使用時、可讓使用者從儲存庫詳細資料頁面上的「 S3 主控台」索引標籤檢視及管理物件。
 a| 

|===