---
permalink: tenant/understanding-search-integration-service.html 
sidebar: sidebar 
keywords: how to understand search integration service 
summary: 如果您想要使用外部搜尋與資料分析服務來取得物件中繼資料、可以啟用S3儲存區的搜尋整合。 
---
= 瞭解搜尋整合服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要使用外部搜尋與資料分析服務來取得物件中繼資料、可以啟用S3儲存區的搜尋整合。

搜尋整合服務是一項自訂的 StorageGRID 服務、可在建立或刪除物件、或更新其中繼資料或標記時、自動且非同步地將 S3 物件中繼資料傳送至目的地端點。然後、您可以使用目的地服務所提供的精密搜尋、資料分析、視覺化或機器學習工具、來搜尋、分析物件資料、並從中獲得深入見解。

例如、您可以設定儲存區、將S3物件中繼資料傳送至遠端Elasticsearch服務。然後您可以使用Elasticsearch來執行跨儲存區的搜尋、並對物件中繼資料中的模式進行精密分析。

雖然彈性搜尋整合功能可在啟用 S3 物件鎖定的儲存貯體上設定、但傳送至彈性搜尋的中繼資料中不會包含物件的 S3 物件鎖定中繼資料（包括「保留截止日期」和「合法保留」狀態）。


NOTE: 由於搜尋整合服務會將物件中繼資料傳送至目的地、因此其組態 XML 稱為「 _meta 資料 _ 通知組態 XML 」。此組態 XML 與用於啟用 _event_ 通知的「通知組態 XML 」不同。



== 搜尋整合與 S3 儲存區

您可以針對任何版本控制或未版本控制的儲存區啟用搜尋整合服務。搜尋整合是透過將中繼資料通知組態XML與儲存區建立關聯來設定、此儲存區會指定要在哪些物件上執行動作、以及物件中繼資料的目的地。

中繼資料通知會以 JSON 文件的形式產生、名稱為貯體名稱、物件名稱和版本 ID （如果有）。每個中繼資料通知都包含物件的標準系統中繼資料集、以及物件的所有標記和使用者中繼資料。


NOTE: 針對標記和使用者中繼資料StorageGRID 、將日期和數字以字串或S3事件通知的形式傳送至Elasticsearch。若要設定Elasticsearch將這些字串解譯為日期或數字、請遵循Elasticsearch指示進行動態欄位對應、以及對應日期格式。您必須先在索引上啟用動態欄位對應、才能設定搜尋整合服務。建立文件索引後、您就無法編輯索引中文件的欄位類型。



== 搜尋通知

在下列情況下、會產生中繼資料通知並排入佇列以供交付：

* 隨即建立物件。
* 刪除物件、包括因網格ILM原則運作而刪除物件的時間。
* 物件中繼資料或標記會新增、更新或刪除。一律會在更新時傳送完整的中繼資料和標記集、而不只是變更的值。


將中繼資料通知組態XML新增至儲存區之後、系統會針對您所建立的任何新物件、以及您透過更新其資料、使用者中繼資料或標記來修改的任何物件、傳送通知。然而、對於已在貯體中的任何物件、則不會傳送通知。若要確保儲存區中所有物件的物件中繼資料都會傳送到目的地、您應該執行下列其中一項：

* 在建立儲存區之後、以及新增任何物件之前、請立即設定搜尋整合服務。
* 對儲存庫中已有的所有物件執行動作、以觸發將中繼資料通知訊息傳送至目的地。




== 搜尋整合服務和彈性搜尋

支援以Elasticsearch叢集作為目的地的支援。StorageGRID如同其他平台服務、目的地是在端點中指定、而其URN則用於服務的組態XML中。使用 https://imt.netapp.com/matrix/#welcome["NetApp 互通性對照表工具"^]來決定 Elasticsearch 支援的版本。
