---
permalink: tenant/using-s3-object-lock.html 
sidebar: sidebar 
keywords: how to use s3 object lock 
summary: 如果貯體和物件必須符合保留法規要求、您可以使用 S3 物件鎖定。 
---
= 使用 S3 物件鎖定來保留物件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果貯體和物件必須符合保留法規要求、您可以使用 S3 物件鎖定。


NOTE: 您的網格管理員必須授予您使用 S3 物件鎖定特定功能的權限。



== 什麼是S3物件鎖定？

「物件鎖定」功能是物件保護解決方案、StorageGRID 相當於Amazon Simple Storage Service（Amazon S3）中的S3物件鎖定。

當 StorageGRID 系統啟用全域 S3 物件鎖定設定時、 S3 租戶帳戶可以建立已啟用或未啟用 S3 物件鎖定的貯體。如果貯體已啟用 S3 物件鎖定、則需要設定貯體版本、而且會自動啟用。

* 沒有 S3 物件鎖定 * 的貯體只能有未指定保留設定的物件。任何擷取的物件都不會有保留設定。

* 具有 S3 物件鎖定 * 的儲存貯體可以有物件、無論是否有 S3 用戶端應用程式指定的保留設定。某些擷取的物件會有保留設定。

* 已設定 S3 物件鎖定和預設保留 * 的貯體、可以使用指定的保留設定來上傳物件、也可以不保留設定來上傳新物件。新物件會使用預設設定、因為尚未在物件層級設定保留設定。

有效地說、所有新擷取的物件在設定預設保留時都會有保留設定。沒有物件保留設定的現有物件不會受到影響。



=== 保留模式

StorageGRID S3 物件鎖定功能支援兩種保留模式、可將不同層級的保護套用至物件。這些模式相當於 Amazon S3 保留模式。

* 在法規遵循模式中：
+
** 直到達到物件的保留日期、才能刪除物件。
** 物件的保留日期可以增加、但不能減少。
** 直到達到該日期為止、才能移除物件的保留日期。


* 在治理模式中：
+
** 具有特殊權限的使用者可以在修改特定保留設定的要求中使用略過標頭。
** 這些使用者可以在達到物件版本的保留截止日期之前刪除物件版本。
** 這些使用者可以增加、減少或移除物件的保留到目前為止。






=== 物件版本的保留設定

如果在啟用 S3 物件鎖定的情況下建立貯體、使用者可以使用 S3 用戶端應用程式、針對新增至貯體的每個物件、選擇性地指定下列保留設定：

* * 保留模式 * ：法規遵循或治理。
* * 保留至日期 * ：如果物件版本的保留至未來日期、則可以擷取物件、但無法刪除。
* *合法持有*：將合法持有套用至物件版本、會立即鎖定該物件。例如、您可能需要對與調查或法律爭議相關的物件保留法律。合法持有沒有到期日、但在明確移除之前、仍會保留到位。合法持有不受保留至日期的限制。
+

NOTE: 如果物件處於合法保留狀態、則無論物件的保留模式為何、任何人都無法刪除該物件。

+
如需物件設定的詳細資料、請參閱link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]。





=== 貯體的預設保留設定

如果在啟用 S3 物件鎖定的情況下建立貯體、使用者可以選擇性地指定貯體的下列預設設定：

* * 預設保留模式 * ：法規遵循或治理。
* * 預設保留期間 * ：新增至此貯體的物件版本應保留多久、從新增物件之日起算。


預設的貯體設定僅適用於沒有自己保留設定的新物件。當您新增或變更這些預設設定時、現有的貯體物件不會受到影響。

請參閱link:../tenant/creating-s3-bucket.html["建立S3儲存區"]和link:../tenant/update-default-retention-settings.html["更新 S3 物件鎖定預設保留"]。



== S3 物件鎖定工作

下列網格管理員和租戶使用者清單包含使用 S3 物件鎖定功能的高階工作。

網格管理員::
+
--
* 為整個 StorageGRID 系統啟用全域 S3 物件鎖定設定。
* 確保資訊生命週期管理（ ILM ）原則符合 _ 標準 _ link:../ilm/managing-objects-with-s3-object-lock.html["啟用 S3 物件鎖定的貯體需求"]、亦即符合。
* 視需要、允許租戶使用「法規遵循」做為保留模式。否則、只允許使用監管模式。
* 視需要為租戶設定最長保留期間。


--
租戶使用者::
+
--
* 檢閱 S3 物件鎖定的貯體和物件考量事項。
* 如有需要、請聯絡網格管理員以啟用全域 S3 物件鎖定設定並設定權限。
* 建立啟用 S3 物件鎖定的貯體。
* 您也可以選擇設定貯體的預設保留設定：
+
** 預設保留模式：監管或法規遵循（如果網格管理員允許）。
** 預設保留期間：必須小於或等於網格管理員設定的最大保留期間。


* 使用 S3 用戶端應用程式來新增物件、並選擇性地設定物件特定的保留：
+
** 保留模式。監管或法規遵循、如果網格管理員允許的話。
** 保留截止日期：必須小於或等於網格管理員設定的保留期間上限所允許的值。




--




== 啟用S3物件鎖定的儲存區需求

* 如果StorageGRID 已針對整個S3物件鎖定設定啟用for the S廳 系統、您可以使用租戶管理程式、租戶管理API或S3 REST API來建立啟用S3物件鎖定的儲存區。
* 如果您打算使用S3物件鎖定、則必須在建立儲存區時啟用S3物件鎖定。您無法為現有貯體啟用 S3 物件鎖定。
* 當「S3物件鎖定」已啟用時、StorageGRID 即可自動啟用該儲存區的版本管理功能。您無法停用儲存區的 S3 物件鎖定或暫停版本設定。
* 您也可以選擇使用租戶管理員、租戶管理 API 或 S3 REST API 、為每個貯體指定預設保留模式和保留期間。貯體的預設保留設定僅適用於新增至貯體但沒有其本身保留設定的新物件。您可以指定保留模式來覆寫這些預設設定、並在上傳每個物件版本時保留至日期。
* 啟用 S3 物件鎖定的貯體支援貯體生命週期組態。
* 啟用S3物件鎖定的儲存區不支援CloudMirror複寫。




== 啟用S3物件鎖定之儲存區中的物件需求

* 若要保護物件版本、您可以指定貯體的預設保留設定、或是指定每個物件版本的保留設定。可以使用 S3 用戶端應用程式或 S3 REST API 來指定物件層級保留設定。
* 保留設定適用於個別物件版本。物件版本可以同時具有「保留直到日期」和「合法保留」設定、但不能有另一個設定、或兩者都沒有。指定物件的保留截止日期或合法保留設定、只會保護要求中指定的版本。您可以建立物件的新版本、而舊版物件仍會保持鎖定狀態。




== 啟用S3物件鎖定的儲存區物件生命週期

儲存在已啟用 S3 物件鎖定的儲存貯體中的每個物件都會經過下列階段：

. *物件擷取*
+
當物件版本新增至啟用 S3 物件鎖定的儲存區時、保留設定會套用如下：

+
** 如果為物件指定保留設定、則會套用物件層級的設定。任何預設貯體設定都會被忽略。
** 如果未指定物件的保留設定、則會套用預設貯體設定（如果存在）。
** 如果未指定物件或貯體的保留設定、則 S3 物件鎖定不會保護該物件。


+
如果套用保留設定、則物件和任何 S3 使用者定義的中繼資料都會受到保護。

. * 物件保留與刪除 *
+
StorageGRID 會在指定的保留期間內儲存每個受保護物件的多個複本。物件複本和儲存位置的確切數量和類型取決於主動式 ILM 原則中的相容規則。受保護物件是否能在達到保留截止日期之前刪除、取決於其保留模式。

+
** 如果物件處於合法保留狀態、則無論物件的保留模式為何、任何人都無法刪除該物件。






== 我是否仍能管理舊有的法規遵循貯體？

S3物件鎖定功能取代先前StorageGRID 版本的Compliance功能。如果您使用StorageGRID 舊版的《不規則》建立了相容的儲存桶、您可以繼續管理這些儲存桶的設定、但是您無法再建立新的相容儲存桶。有關說明，請參閱https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"^]。
