---
permalink: admin/admin-group-permissions.html 
sidebar: sidebar 
keywords: admin group permissions 
summary: 建立管理使用者群組時、您可以選取一或多個權限來控制對Grid Manager特定功能的存取。然後、您可以將每個使用者指派給一或多個這些管理群組、以決定使用者可以執行哪些工作。 
---
= 管理群組權限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立管理使用者群組時、您可以選取一或多個權限來控制對Grid Manager特定功能的存取。然後、您可以將每個使用者指派給一或多個這些管理群組、以決定使用者可以執行哪些工作。

您必須為每個群組指派至少一項權限、否則屬於該群組的使用者將無法登入Grid Manager或Grid Management API。

根據預設、任何屬於至少擁有一項權限之群組的使用者、都可以執行下列工作：

* 登入Grid Manager
* 檢視儀表板
* 檢視節點頁面
* 檢視目前和已解決的警示
* 變更自己的密碼（僅限本機使用者）
* 檢視「組態與維護」頁面上提供的特定資訊




== 權限與存取模式之間的互動

對於所有權限、群組的「*存取模式*」設定會決定使用者是否可以變更設定及執行作業、或是只能檢視相關的設定與功能。如果使用者屬於多個群組、且任何群組設定為*唯讀*、則使用者將擁有所有選取設定和功能的唯讀存取權。

下列各節將說明您在建立或編輯管理群組時可以指派的權限。任何未明確提及的功能都需要*根存取*權限。



== root存取權

此權限可讓您存取所有網格管理功能。



== 變更租戶根密碼

此權限可讓您存取「租戶」頁面上的*變更root密碼*選項、讓您控制誰可以變更租戶本機root使用者的密碼。啟用S3金鑰匯入功能時、此權限也可用於移轉S3金鑰。沒有此權限的使用者無法看到 * 變更 root 密碼 * 選項。


NOTE: 若要授予「租戶」頁面的存取權（包含*變更root密碼*選項）、請同時指派*租戶帳戶*權限。



== 網格拓撲頁面組態

此權限可讓您存取「*支援*>*工具*>*網格拓撲*」頁面上的「組態」索引標籤。


NOTE: Grid 拓撲頁面已過時、將在未來版本中移除。



== ILM

此權限可讓您存取下列* ILM *功能表選項：

* 規則
* 原則
* 原則標籤
* 儲存資源池
* 儲存等級
* 區域
* 物件中繼資料查詢



NOTE: 使用者必須擁有*其他網格組態*和*網格拓撲頁面組態*權限、才能管理儲存等級。



== 維護

使用者必須擁有維護權限、才能使用下列選項：

* *組態*>*存取控制*：
+
** 網格密碼


* *組態*>*網路*：
+
** S3 端點網域名稱


* *維護*>*工作*：
+
** 取消委任
** 擴充
** 物件存在檢查
** 恢復


* *維護*>*系統*：
+
** 恢復套件
** 軟體更新


* *支援*>*工具*：
+
** 記錄




沒有維護權限的使用者可以檢視但無法編輯這些頁面：

* *維護*>*網路*：
+
** DNS 伺服器
** 網格網路
** NTP 伺服器


* *維護*>*系統*：
+
** 授權


* *組態*>*網路*：
+
** S3 端點網域名稱


* *組態*>*安全性*：
+
** 憑證


* *組態*>*監控*：
+
** 稽核與syslog伺服器






== 管理警示

此權限可讓您存取管理警示的選項。使用者必須擁有此權限、才能管理靜音、警示通知及警示規則。



== 度量查詢

此權限可讓您存取：

* * 支援 * > * 工具 * > * 指標 * 頁面
* 使用 Grid Management API 的 * Metrics * 區段來自訂 Prometheus 指標查詢
* 包含計量的 Grid Manager 儀表板卡




== 物件中繼資料查詢

此權限可讓您存取「* ILM *>*物件中繼資料查詢*」頁面。



== 其他網格組態

此權限可讓您存取其他網格組態選項。


TIP: 若要查看這些額外選項、使用者也必須具有* Grid拓撲頁面組態*權限。

* * ILM *：
+
** 儲存等級


* *組態*>*系統*：
* * 支援 * > * 其他 * ：
+
** 連結成本






== 儲存應用裝置管理員

此權限提供：

* 透過 Grid Manager 存取儲存設備上的 E 系列 SANtricity 系統管理員。
* 可在支援這些作業的應用裝置的「管理磁碟機」索引標籤上執行疑難排解和維護工作。




== 租戶帳戶

此權限可讓您：

* 存取租戶頁面、您可以在其中建立、編輯及移除租戶帳戶
* 檢視現有的流量分類原則
* 檢視包含租戶詳細資料的 Grid Manager 儀表板卡

