---
permalink: admin/benefits-of-active-idle-and-concurrent-http-connections.html 
sidebar: sidebar 
keywords: active http connection benefits, idle http connection benefits, concurrent http connection benefits 
summary: 如何設定HTTP連線、可能會影響StorageGRID 到整個系統的效能。組態會因HTTP連線為作用中或閒置狀態、或是您同時有多個連線而有所不同。 
---
= 作用中、閒置及並行HTTP連線的優點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如何設定HTTP連線、可能會影響StorageGRID 到整個系統的效能。組態會因HTTP連線為作用中或閒置狀態、或是您同時有多個連線而有所不同。

您可以找出下列類型HTTP連線的效能優勢：

* 閒置HTTP連線
* 作用中HTTP連線
* 並行HTTP連線




== 保持閒置HTTP連線開啟的優點

即使用戶端應用程式閒置、您仍應保持HTTP連線開啟、以允許用戶端應用程式透過開放式連線執行後續交易。根據系統測量與整合體驗、您應將閒置的HTTP連線保持開啟狀態最長10分鐘。可能會自動關閉持續開啟和閒置超過10分鐘的HTTP連線。StorageGRID

開放式和閒置的HTTP連線提供下列優點：

* 縮短延遲時間、從StorageGRID 由整個過程中、由整個過程中的資訊系統判斷它必須執行HTTP交易到StorageGRID 整個系統能夠執行交易的時間
+
縮短延遲是主要優勢、尤其是在建立TCP/IP和TLS連線所需的時間內。

* 使用先前執行的傳輸來初始化TCP/IP慢速啟動演算法、藉此提高資料傳輸率
* 即時通知多種故障情況、可中斷用戶端應用程式與StorageGRID 該系統之間的連線


判斷閒置連線開啟的時間長度、是在與現有連線相關的慢速啟動優點與內部系統資源連線的理想分配之間取得平衡。



== 作用中HTTP連線的優點

對於直接連線至儲存節點的連線、即使 HTTP 連線持續執行交易、您仍應將作用中 HTTP 連線的持續時間限制為最多 10 分鐘。

判斷連線應保持開啟的最長時間、是在連線持續性的優點與連線至內部系統資源的理想分配之間取得平衡。

對於用戶端連線至儲存節點、限制作用中的 HTTP 連線有下列優點：

* 在StorageGRID 整個支援過程中實現最佳負載平衡。
+
隨著時間推移、隨著負載平衡需求的變更、HTTP連線可能不再是最佳狀態。當用戶端應用程式為每筆交易建立獨立的HTTP連線時、系統會執行最佳負載平衡、但這會使持續連線所帶來的更多寶貴成果喪失價值。

* 允許用戶端應用程式將HTTP交易導向具有可用空間的LDR服務。
* 可啟動維護程序。
+
部分維護程序只會在所有進行中的HTTP連線完成後才會開始。



對於連接到負載平衡器服務的用戶端連線、限制開放連線的持續時間、有助於讓部分維護程序立即啟動。如果用戶端連線的持續時間不受限制、則自動終止作用中連線可能需要幾分鐘的時間。



== 並行HTTP連線的優點

您應該StorageGRID 將多個TCP/IP連線保持開放狀態、以允許平行處理、進而提升效能。最佳的平行連線數量取決於各種因素。

並行HTTP連線提供下列優點：

* 縮短延遲時間
+
交易可以立即開始、而非等待其他交易完成。

* 提高處理量
+
此系統可執行平行交易、並提高集合交易處理量。StorageGRID



用戶端應用程式應建立多個HTTP連線。當用戶端應用程式必須執行交易時、它可以選取並立即使用任何目前未處理交易的已建立連線。

在StorageGRID 效能開始降級之前、每個支援系統的拓撲在並行交易和連線方面都有不同的尖峰處理量。尖峰處理量取決於運算資源、網路資源、儲存資源和WAN連結等因素。此外、伺服器和服務的數量、StorageGRID 以及支援哪些應用程式、也是因素。

支援多種用戶端應用程式的系統。StorageGRID當您決定用戶端應用程式所使用的並行連線數目上限時、請謹記這一點。如果用戶端應用程式包含多個軟體實體、每個實體都會建立StorageGRID 與該系統的連線、您應該新增整個實體之間的所有連線。在下列情況下、您可能必須調整並行連線的最大數量：

* 此系統的拓撲會影響系統可支援的並行交易和連線數量上限。StorageGRID
* 在StorageGRID 頻寬有限的網路上與該系統互動的用戶端應用程式、可能必須降低並行度、以確保在合理的時間內完成個別交易。
* 當許多用戶端應用程式共用StorageGRID 該系統時、您可能必須減少並行處理的程度、以避免超出系統限制。




== 分隔HTTP連線集區以進行讀取和寫入作業

您可以使用不同的HTTP連線集區進行讀取和寫入作業、並控制每個集區的使用量。獨立的HTTP連線集區可讓您更有效地控制交易並平衡負載。

用戶端應用程式可建立擷取主導（讀取）或儲存主導（寫入）的負載。有了個別的HTTP連線集區、即可針對讀寫交易調整每個集區的專屬容量、以處理讀寫交易。
