---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 網格中的每個節點都有一個節點控制台密碼，您可以使用該密碼登入該節點。預設情況下，每個節點都有一個唯一的密碼。您可以將每個密碼變更為新的唯一密碼，也可以將每個節點的密碼變更為使用全域密碼。密碼儲存在恢復包中。 
---
= 變更節點主控台密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網格中的每個節點都有一個節點控制台密碼，您可以使用該密碼登入該節點。預設情況下，每個節點都有一個唯一的密碼。您可以將每個密碼變更為新的唯一密碼，也可以將每個節點的密碼變更為使用全域密碼。密碼儲存在恢復包中。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:admin-group-permissions.html["維護或根存取權限"]。
* 您有目前的資源配置通關密碼。


.關於這項工作
您可以使用節點控制台密碼透過 SSH 以「管理員」身分登入節點，或透過 VM/實體控制台連線以 root 使用者身分登入。您可以使用下列選項之一變更節點控制台密碼：

* 自動對每個節點應用隨機密碼
* 指定一個全域密碼並將其應用於所有節點
* 指定並將唯一密碼套用至一個或多個節點


密碼儲存在更新的 `Passwords.txt`恢復包中的檔案。密碼列在檔案的密碼列中。


NOTE: 這link:../admin/change-ssh-access-passwords.html["SSH 訪問密碼"]用於節點間通訊的 SSH 金鑰與節點控制台密碼是分開的。此程序不會變更 SSH 存取密碼。



== 存取精靈

.步驟
. 選擇*設定* > *存取控制* > *電網密碼*。
. 在 * 變更節點主控台密碼 * 下、選取 * 進行變更 * 。




== [[download-curric]] 下載目前的恢復套件

在變更節點控制台密碼之前，請下載目前的復原包。如果任何節點的密碼變更過程失敗，您可以使用此檔案中的密碼。

.步驟
. 輸入您網格的資源配置密碼。
. 選擇*下載恢復套件*。
. 複製復原包文件(`.zip`）到兩個安全、可靠且獨立的位置。
+

CAUTION: 復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。

. 選擇*繼續*。




== 提供新密碼

. 選擇您想要使用的密碼變更方法。
+
** *自動*： StorageGRID會自動為所有節點指派一個新的隨機控制台密碼。
** *自訂*：您提供控制台密碼。




[role="tabbed-block"]
====
.自動的
--
. 選擇*繼續*。


--
.自訂
--
. 選取下列其中一項：
+
** *全域控制台密碼*：對所有節點套用相同的控制台密碼。
** *唯一的控制台密碼*：在一個或多個節點上套用不同的密碼。


. 如果您選擇了*全域控制台密碼*，請輸入您想要用於所有節點的密碼。
. 如果選擇了“唯一控制台密碼”，請為一個或多個節點輸入唯一密碼。
. 選擇*繼續*。


--
====


== 完成密碼修改

. 當確認對話方塊出現時，如果您準備好讓StorageGRID開始變更節點控制台密碼，請選擇 *是*。
+

NOTE: 您無法在程序啟動後取消此程序。

+
StorageGRID產生一個包含新密碼的新復原包。

. 當新的恢復包準備好後，選擇*下載新的恢復包*並保存恢復包。
. 開啟 `.zip`檔案。
. 確認您可以存取包含新節點主控台密碼的內容、包括 `Passwords.txt`檔案。
. 複製新的復原包文件(`.zip`）到兩個安全、可靠且獨立的地點。
+

CAUTION: 不要覆蓋舊的恢復包。

+
您必須保護復原文件，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。

. 選取核取方塊表示您已下載新的復原套件並驗證了內容。
. 選擇*繼續*。
+
StorageGRID更新每個節點的密碼。

+
如果更新過程中出現錯誤，進度條會列出密碼變更失敗的節點數。系統將自動在密碼變更失敗的任何節點上重試該過程。如果該過程結束時某些節點仍未更改密碼，則會出現「重試」按鈕。

. 如果一或多個節點的密碼更新失敗：
+
.. 檢閱表中所列的錯誤訊息。
.. 解決問題。
.. 選擇*重試*。
+

NOTE: 重試只會變更先前密碼變更嘗試期間失敗之節點上的節點主控台密碼。



. 當進度條顯示沒有剩餘更新時，選擇*完成*。
. 更改所有節點的節點控制台密碼後，刪除<<download-current,您下載的第一個復原包>>。

