---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 網格中的每個節點都有唯一的節點主控台密碼、您必須登入節點。請使用下列步驟變更網格中每個節點的節點主控台密碼。密碼儲存在恢復套件中。 
---
= 變更節點主控台密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網格中的每個節點都有唯一的節點主控台密碼、您必須登入節點。請使用這些步驟來變更網格中每個節點的每個唯一節點主控台密碼。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:admin-group-permissions.html["維護或根存取權限"]。
* 您有目前的資源配置通關密碼。


.關於這項工作
使用節點主控台密碼、以「 admin 」身分使用 SSH 登入節點、或以 VM/ 實體主控台連線的 root 使用者身分登入。變更節點主控台密碼程序會為網格中的每個節點建立新密碼、並將密碼儲存在恢復套件的更新 `Passwords.txt`檔案中。密碼會列在Passwords.txt檔案的「Password（密碼）」欄中。


NOTE: SSH金鑰有個別的SSH存取密碼、用於節點之間的通訊。此程序不會變更 SSH 存取密碼。



== 存取精靈

.步驟
. 選擇*組態*>*存取控制*>*網格密碼*。
. 在 * 變更節點主控台密碼 * 下、選取 * 進行變更 * 。




== 輸入資源配置通關密碼

.步驟
. 輸入您網格的資源配置密碼。
. 選擇*繼續*。




== [[download-curric]] 下載目前的恢復套件

變更節點主控台密碼之前、請先下載目前的恢復套件。如果任何節點的密碼變更程序失敗、您可以使用此檔案中的密碼。

.步驟
. 選擇*下載恢復套件*。
. 將恢復軟件包文件複製(`.zip`到兩個安全且獨立的位置。
+

CAUTION: 必須保護恢復套件檔案、因為其中包含可用於從StorageGRID 該系統取得資料的加密金鑰和密碼。

. 選擇*繼續*。
. 當確認對話方塊出現時、如果您已準備好開始變更節點主控台密碼、請選取 * 是 * 。
+
您無法在程序啟動後取消此程序。





== 變更節點主控台密碼

當節點主控台密碼程序啟動時、會產生包含新密碼的新恢復套件。然後、每個節點上的密碼都會更新。

.步驟
. 等待產生新的恢復套件、可能需要幾分鐘的時間。
. 選擇*下載新的恢復套件*。
. 下載完成時：
+
.. 開啟 `.zip`檔案。
.. 確認您可以存取包含新節點主控台密碼的內容、包括 `Passwords.txt`檔案。
.. 將新的恢復軟件包文件複製(`.zip`到兩個安全且獨立的位置。
+

CAUTION: 請勿覆寫舊的恢復套件。

+
必須保護恢復套件檔案、因為其中包含可用於從StorageGRID 該系統取得資料的加密金鑰和密碼。



. 選取核取方塊、表示您已下載新的恢復套件並驗證內容。
. 選取 * 變更節點主控台密碼 * 、並等待所有節點以新密碼更新。這可能需要幾分鐘的時間。
+
如果變更所有節點的密碼、會出現綠色的成功橫幅。前往下一步。

+
如果在更新程序期間發生錯誤、則會出現橫幅訊息、列出無法變更密碼的節點數量。系統會在任何無法變更密碼的節點上、自動重試此程序。如果程序結束時、部分節點仍未變更密碼、則會出現*重試*按鈕。

+
如果一或多個節點的密碼更新失敗：

+
.. 檢閱表中所列的錯誤訊息。
.. 解決問題。
.. 選擇*重試*。
+

NOTE: 重試只會變更先前密碼變更嘗試期間失敗之節點上的節點主控台密碼。



. 變更所有節點的節點主控台密碼後<<download-current,您下載的第一個恢復套件>>、請刪除。
. 您也可以使用*恢復套件*連結下載新的恢復套件的其他複本。

