---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 網格中的每個節點都有節點主控台密碼，您可以使用該密碼登入節點。根據預設，每個節點都有唯一的密碼。您可以將每個密碼變更為新的唯一密碼，也可以變更每個節點的密碼，以使用通用密碼。密碼會儲存在恢復套件中。 
---
= 變更節點主控台密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網格中的每個節點都有節點主控台密碼，您可以使用該密碼登入節點。根據預設，每個節點都有唯一的密碼。您可以將每個密碼變更為新的唯一密碼，也可以變更每個節點的密碼，以使用通用密碼。密碼會儲存在恢復套件中。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:admin-group-permissions.html["維護或根存取權限"]。
* 您有目前的資源配置通關密碼。


.關於這項工作
您可以使用節點主控台密碼，以「 admin 」身分使用 SSH 登入節點，或以 VM/ 實體主控台連線的 root 使用者身分登入。您可以使用下列其中一個選項來變更節點主控台密碼：

* 自動將隨機密碼套用至每個節點
* 指定一個通用密碼並套用至所有節點
* 指定唯一密碼並套用至一或多個節點


密碼會儲存在恢復套件的更新檔案中 `Passwords.txt`。密碼會列在檔案的密碼欄中。


NOTE: link:../admin/change-ssh-access-passwords.html["SSH 存取密碼"]用於節點之間通訊的 SSH 金鑰與節點主控台密碼是分開的。此程序不會變更 SSH 存取密碼。



== 存取精靈

.步驟
. 選擇*組態*>*存取控制*>*網格密碼*。
. 在 * 變更節點主控台密碼 * 下、選取 * 進行變更 * 。




== [[download-curric]] 下載目前的恢復套件

變更節點主控台密碼之前、請先下載目前的恢復套件。如果任何節點的密碼變更程序失敗、您可以使用此檔案中的密碼。

.步驟
. 輸入您網格的資源配置密碼。
. 選擇*下載恢復套件*。
. 將恢復軟件包文件複製(`.zip`到兩個安全且獨立的位置。
+

CAUTION: 恢復套件檔案必須受到保護、因為它包含可用於從 StorageGRID 系統取得資料的加密金鑰和密碼。

. 選擇*繼續*。




== 提供新密碼

. 選取您要使用的密碼變更方法。
+
** * 自動 * ： StorageGRID 會自動將新的隨機主控台密碼指派給所有節點。
** * 自訂 * ：您提供主控台密碼。




[role="tabbed-block"]
====
.自動
--
. 選擇*繼續*。


--
.自訂
--
. 選取下列其中一項：
+
** * 通用主控台密碼 * ：將相同的主控台密碼套用至所有節點。
** * 唯一主控台密碼 * ：在一或多個節點上套用不同的密碼。


. 如果您選取 * 全域主控台密碼 * ，請輸入您要用於所有節點的密碼。
. 如果您選取 * 唯一主控台密碼 * ，請輸入一個或多個節點的唯一密碼。
. 選擇*繼續*。


--
====


== 完成密碼變更

. 當確認對話方塊出現時，如果您已準備好讓 StorageGRID 開始變更節點主控台密碼，請選取 * 是 * 。
+

NOTE: 您無法在程序啟動後取消此程序。

+
StorageGRID 會產生包含新密碼的新恢復套件。

. 當新的恢復套件準備就緒時，請選取 * 下載新的恢復套件 * 並儲存恢復套件。
. 開啟 `.zip`檔案。
. 確認您可以存取包含新節點主控台密碼的內容、包括 `Passwords.txt`檔案。
. 將新的恢復軟件包文件複製(`.zip`到兩個安全且獨立的位置。
+

CAUTION: 請勿覆寫舊的恢復套件。

+
您必須保護還原檔案的安全，因為它包含可用於從 StorageGRID 系統取得資料的加密金鑰和密碼。

. 選取核取方塊，表示您已下載新的還原套件並驗證內容。
. 選擇*繼續*。
+
StorageGRID 會更新每個節點的密碼。

+
如果在更新程序期間發生錯誤，進度列會列出無法變更密碼的節點數。系統會在任何無法變更密碼的節點上、自動重試此程序。如果程序結束時、部分節點仍未變更密碼、則會出現*重試*按鈕。

. 如果一或多個節點的密碼更新失敗：
+
.. 檢閱表中所列的錯誤訊息。
.. 解決問題。
.. 選擇*重試*。
+

NOTE: 重試只會變更先前密碼變更嘗試期間失敗之節點上的節點主控台密碼。



. 當進度列顯示沒有剩餘的更新時，請選取 * 完成 * 。
. 變更所有節點的節點主控台密碼後<<download-current,您下載的第一個恢復套件>>、請刪除。

