---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 變更管理節點的 SSH 存取密碼也會更新網格中每個節點的唯一內部 SSH 金鑰集。主要管理節點使用這些 SSH 金鑰、使用安全、無密碼驗證來存取節點。 
---
= 變更管理節點的 SSH 存取密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
變更管理節點的 SSH 存取密碼也會更新網格中每個節點的唯一內部 SSH 金鑰集。主要管理節點使用這些 SSH 金鑰、使用安全、無密碼驗證來存取節點。

使用 SSH 金鑰、以 VM 或實體主控台連線上的 root 使用者身分或登入節點 `admin`。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:admin-group-permissions.html["維護或根存取權限"]。
* 您有目前的資源配置通關密碼。


.關於這項工作
管理節點的新存取密碼和每個節點的新內部金鑰儲存在 `Passwords.txt`恢復包中的檔案。密鑰列在該文件中的密碼列中。

SSH金鑰有個別的SSH存取密碼、用於節點之間的通訊。此程序不會變更這些項目。



== 存取精靈

.步驟
. 選擇*設定* > *存取控制* > *電網密碼*。
. 在 * 變更 SSH 金鑰 * 下、選取 * 進行變更 * 。




== [[download-curric]] 下載目前的恢復套件

在變更 SSH 存取金鑰之前，請下載目前的復原包。如果任何節點的金鑰變更過程失敗，您可以使用此文件中的金鑰。

.步驟
. 輸入您網格的資源配置密碼。
. 選擇*下載恢復套件*。
. 複製復原包文件(`.zip`）到兩個安全、可靠且獨立的位置。
+

CAUTION: 復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。

. 選擇*繼續*。
. 當確認對話方塊出現時、如果您已準備好開始變更 SSH 存取金鑰、請選取 * 是 * 。
+

CAUTION: 您無法在程序啟動後取消此程序。





== 變更 SSH 存取金鑰

當變更 SSH 存取金鑰程序開始時，將產生一個包含新金鑰的新復原包。然後，在每個節點上更新金鑰。

.步驟
. 等待新的恢復包生成，這可能需要幾分鐘。
. 當「下載新的復原包」按鈕啟用時，選擇「*下載新的復原包*」並儲存新的復原包文件(`.zip`）到兩個安全、可靠且獨立的地點。
. 下載完成時：
+
.. 開啟 `.zip`檔案。
.. 確認您可以存取包含新 SSH 存取金鑰的內容、包括 `Passwords.txt`檔案。
.. 複製新的復原包文件(`.zip`）到兩個安全、可靠且獨立的地點。
+

CAUTION: 不要覆蓋舊的恢復包。

+
復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。



. 等待每個節點上的金鑰更新、可能需要幾分鐘的時間。
+
如果所有節點的金鑰都已變更、就會出現綠色成功橫幅。

+
如果在更新過程中發生錯誤、橫幅訊息會列出無法變更其金鑰的節點數。系統會在任何無法變更其金鑰的節點上、自動重試該程序。如果程序結束時、有些節點仍沒有變更金鑰、則會出現 * 重試 * 按鈕。

+
如果一個或多個節點的金鑰更新失敗：

+
.. 檢閱表中所列的錯誤訊息。
.. 解決問題。
.. 選擇*重試*。
+
重試只會變更先前金鑰變更嘗試失敗的節點上的 SSH 存取金鑰。



. 在所有節點的 SSH 存取金鑰變更後，刪除<<download-current,您下載的第一個復原包>>。
. 或者，選擇「*維護*」>「*系統*」>「*復原包*」下載新復原包的附加副本。

