---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: 如果您想要依儲存區、租戶、IP子網路或負載平衡器端點來監控及選擇性地限制網路流量、請建立流量分類原則。您也可以根據頻寬、並行要求數或要求率、來設定原則限制。 
---
= 建立流量分類原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要監控流量分類原則、並選擇性地根據貯體、貯體 regex 、 CIDR 、負載平衡器端點或租戶來限制網路流量、則可以建立流量分類原則。您也可以根據頻寬、並行要求數或要求率、來設定原則限制。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:admin-group-permissions.html["root 存取權限"]。
* 您已建立任何想要比對的負載平衡器端點。
* 您已建立任何想要比對的租戶。


.步驟
. 選擇*配置* > *網路* > *流量分類*。
. 選擇* Create *（建立*）。
. 輸入原則的名稱和說明（選用）、然後選取 * 繼續 * 。
+
例如、請說明此流量分類原則的適用範圍及限制。

. 選取 * 新增規則 * 並指定下列詳細資料、以建立原則的一或多個相符規則。您建立的任何原則都應該至少有一個相符的規則。選擇*繼續*。
+
[cols="1a,3a"]
|===
| 欄位 | 說明 


 a| 
類型
 a| 
選取符合規則所套用的流量類型。流量類型包括貯體、貯體 regex 、 CIDR 、負載平衡器端點和租戶。



 a| 
符合值
 a| 
輸入符合所選類型的值。

** 貯體：輸入一個或多個貯體名稱。
** 貯體 regex ：輸入一個或多個用於與一組貯體名稱相符的規則運算式。
+
規則運算式未鎖定。使用 ^ 錨點來比對貯體名稱的開頭、並使用 $ 錨點來比對名稱的結尾。規則運算式比對支援 PCRE （ Perl 相容規則運算式）語法子集。

** CIDR ：以 CIDR 表示法輸入一個或多個符合所需子網路的 IPv4 子網路。
** 負載平衡器端點：選取端點名稱。這些是您在上定義的負載平衡器端點link:../admin/configuring-load-balancer-endpoints.html["設定負載平衡器端點"]。
** 租戶：租戶比對使用存取金鑰 ID 。如果要求不包含存取金鑰 ID （例如匿名存取）、則會使用存取的貯體所有權來決定租戶。




 a| 
反轉比對
 a| 
如果您想要比對所有網路流量（除了 _ 流量與剛定義的類型和比對值一致）、請選取 * 反轉比對 * 核取方塊。否則、請保留核取方塊的核取方塊。

例如、如果您想要將此原則套用至負載平衡器端點以外的所有端點、請指定要排除的負載平衡器端點、然後選取 * 逆向比對 * 。

對於包含多個資料處理者的原則、其中至少有一個是反向資料處理者、請注意不要建立符合所有要求的原則。

|===
. 您也可以選擇 * 新增限制 * 、然後選取下列詳細資料、以新增一或多個限制、以控制與規則相符的網路流量。
+

NOTE: StorageGRID 會收集指標、即使您沒有新增任何限制、也能瞭解流量趨勢。

+
[cols="1a,3a"]
|===
| 欄位 | 說明 


 a| 
類型
 a| 
您要套用至規則所對應網路流量的限制類型。例如、您可以限制頻寬或要求率。

* 注意 * ：您可以建立原則來限制彙總頻寬或限制每個要求的頻寬。不過、 StorageGRID 無法同時限制這兩種頻寬類型。當使用 Aggregate 頻寬時、無法使用每個要求的頻寬。相反地、當每個要求的頻寬正在使用中時、就無法使用集合頻寬。Aggregate頻寬限制可能會對不受限制的流量造成額外的次要效能影響。

在頻寬限制方面StorageGRID 、餐廳會套用最符合限制類型的原則。例如、如果您的原則只限制一個方向的流量、則相反方向的流量將不受限制、即使有流量符合具有頻寬限制的其他原則。StorageGRID 以下列順序實作頻寬限制的「最佳」比對：

** 確切IP位址（/32遮罩）
** 確切的儲存區名稱
** 鏟斗回收系統
** 租戶
** 端點
** 非精確的CIDR相符項目（非/32）
** 反比對




 a| 
適用於
 a| 
此限制是否適用於用戶端讀取要求（ GET 或 HEAD ）或寫入要求（ PUT 、 POST 或 DELETE ）。



 a| 
價值
 a| 
根據您選擇的單位、網路流量將受限於的值。例如、輸入 10 並選取 MIB/s 、以防止符合此規則的網路流量超過 10 MIB/s

* 附註 * ：視單位設定而定、可用的單位為二進位（例如 GiB ）或十進位（例如 GB ）。若要變更單位設定、請選取 Grid Manager 右上角的使用者下拉式清單、然後選取 * 使用者偏好設定 * 。



 a| 
單位
 a| 
描述您輸入值的單位。

|===
+
例如，如果您想要為 SLA 層建立 4 GB/s 的頻寬限制，請建立兩個聚合頻寬限制：GET/HEAD 為 4 GB/s，PUT/POST/DELETE 為 4 GB/s。

. 選擇*繼續*。
. 閱讀並檢閱流量分類原則。使用 * 上一頁 * 按鈕返回並視需要進行變更。當您對原則感到滿意時、請選取 * 儲存並繼續 * 。
+
S3 用戶端流量現在會根據流量分類原則進行處理。



.完成後
link:viewing-network-traffic-metrics.html["檢視網路流量指標"]驗證原則是否強制執行您預期的流量限制。
