---
permalink: admin/grid-federation-compare-cgr-to-cloudmirror.html 
sidebar: sidebar 
keywords: cross-grid replication, cloudmirror replication 
summary: 開始使用網格同盟時、請檢閱跨網格複寫與 StorageGRID CloudMirror 複寫服務之間的相似點和差異。 
---
= 比較跨網格複寫和 CloudMirror 複寫
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
開始使用網格同盟時，請檢閱與之間的相似點和差異link:grid-federation-what-is-cross-grid-replication.html["跨網格複寫"]link:../tenant/understanding-cloudmirror-replication-service.html["CloudMirror複寫服務StorageGRID"]。

[cols="1a,3a,3a"]
|===
|  | 跨網格複寫 | CloudMirror複寫服務 


 a| 
主要目的為何？
 a| 
一個 StorageGRID 系統可做為災難恢復系統。貯體中的物件可在網格之間以一個或兩個方向複寫。
 a| 
可讓租戶自動將物件從 StorageGRID （來源）的貯體複寫到外部 S3 貯體（目的地）。

CloudMirror複寫可在獨立的S3基礎架構中建立物件的獨立複本。這份不受影響的複本並未作為備份、但通常會在雲端中進一步處理。



 a| 
如何設定？
 a| 
. 設定兩個網格之間的網格同盟連線。
. 新增自動複製到其他網格的租戶帳戶。
. 新增新的租戶群組和使用者、這些群組和使用者也會被複製。
. 在每個網格上建立對應的儲存格、並可在一個或兩個方向進行跨網格複寫。

 a| 
. 租戶使用者使用租戶管理程式或S3 API定義CloudMirror端點（IP位址、認證等）來設定CloudMirror複寫。
. 該租戶帳戶擁有的任何貯體都可以設定為指向 CloudMirror 端點。




 a| 
誰負責設定？
 a| 
* 網格管理員會設定連線和租戶。
* 租戶使用者可設定群組、使用者、金鑰和貯體。

 a| 
一般而言、租戶使用者。



 a| 
目的地為何？
 a| 
網格聯合連線中其他 StorageGRID 系統上對應且相同的 S3 儲存貯體。
 a| 
* 任何相容的 S3 基礎架構（包括 Amazon S3 ）。
* Google Cloud Platform（GCP）




 a| 
是否需要物件版本設定？
 a| 
是的、來源和目的地貯體都必須啟用物件版本設定。
 a| 
否、 CloudMirror 複寫支援來源和目的地上的任何未版本控制和版本控制的貯體組合。



 a| 
什麼原因會將物件移至目的地？
 a| 
物件新增至已啟用跨網格複寫的儲存區時、會自動複寫。
 a| 
將物件新增至已設定 CloudMirror 端點的儲存區時、物件會自動複寫。除非經過修改、否則不會複寫在使用 CloudMirror 端點設定儲存區之前存在於來源儲存區中的物件。



 a| 
物件如何複寫？
 a| 
跨網格複寫會建立版本控制的物件、並將版本 ID 從來源貯體複寫到目的地貯體。如此一來、就能在兩個網格上維護版本順序。
 a| 
CloudMirror 複寫不需要啟用版本控制的儲存區、因此 CloudMirror 只能維護網站內金鑰的訂購。對於不同站台的物件要求、我們無法保證會維持訂購。



 a| 
如果物件無法複寫該怎麼辦？
 a| 
物件會排入佇列進行複寫、但受中繼資料儲存限制規範。
 a| 
物件會排入佇列進行複寫、但必須遵守平台服務限制（請參閱link:manage-platform-services-for-tenants.html["使用平台服務的建議"]）。



 a| 
物件的系統中繼資料是否已複寫？
 a| 
是的、當物件複寫到其他網格時、也會複寫其系統中繼資料。兩個網格上的中繼資料將相同。
 a| 
否、當物件複寫到外部儲存區時、系統中繼資料會更新。中繼資料會因位置而異、視擷取時間和 S3 基礎架構的行為而定。



 a| 
如何擷取物件？
 a| 
應用程式可向任一網格上的儲存格提出要求、以擷取或讀取物件。
 a| 
應用程式可以向 StorageGRID 或 S3 目的地提出要求、以擷取或讀取物件。例如、假設您使用CloudMirror複寫將物件鏡射到合作夥伴組織。合作夥伴可以使用自己的應用程式、直接從S3目的地讀取或更新物件。不需要使用此功能。StorageGRID



 a| 
如果刪除物件會發生什麼情況？
 a| 
* 包含版本 ID 的刪除要求絕不會複寫到目的地網格。
* 刪除不包含版本 ID 的要求、將刪除標記新增至來源貯體、可選擇性地複寫至目的地網格。
* 如果只針對一個方向設定跨網格複寫、則可刪除目的地儲存區中的物件、而不會影響來源。

 a| 
結果會因來源和目的地儲存區的版本設定狀態而異（不需要相同）：

* 如果兩個儲存區都已版本化、則刪除要求會在兩個位置新增刪除標記。
* 如果只有來源貯體已版本化、則刪除要求會將刪除標記新增至來源、但不會新增至目的地。
* 如果兩個貯體都沒有版本化、則刪除要求會從來源中刪除物件、而非從目的地刪除物件。


同樣地、也可以刪除目的地儲存區中的物件、而不會影響來源。

|===