---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: QoS, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: 流量分類原則可讓您識別及監控不同類型的網路流量。這些原則有助於限制和監控流量、以提升您的服務品質（ QoS ）產品。 
---
= 什麼是流量分類原則？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
流量分類原則可讓您識別及監控不同類型的網路流量。這些原則有助於限制和監控流量、以提升您的服務品質（ QoS ）產品。

流量分類原則會套用至StorageGRID 閘道節點和管理節點的「動態負載平衡器」服務上的端點。若要建立流量分類原則、您必須已經建立負載平衡器端點。



== 符合的規則

每個流量分類原則都包含一或多個相符的規則、用以識別與下列一或多個實體相關的網路流量：

* 桶
* 子網路
* 租戶
* 負載平衡器端點


此功能可根據規則的目標、監控符合原則中任何規則的流量。StorageGRID符合原則任何規則的任何流量都會由該原則處理。相反地、您可以設定規則以符合指定實體以外的所有流量。



== 流量限制

您也可以選擇將下列限制類型新增至原則：

* Aggregate 頻寬
* 每個要求的頻寬
* 並行要求
* 要求率


限制值是以每個負載平衡器為基礎強制執行。如果流量同時分散於多個負載平衡器、則總最大傳輸率是您指定的速率限制的倍數。


NOTE: 您可以建立原則來限制Aggregate頻寬或限制每個要求的頻寬。不過、 StorageGRID 無法同時限制這兩種頻寬類型。Aggregate頻寬限制可能會對不受限制的流量造成額外的次要效能影響。

針對Aggregate或每個要求頻寬限制、要求會以您設定的速率傳入或傳出。由於支援的速度只能達到一種、因此根據matcher類型、最符合的原則就是強制執行的速度。StorageGRID此要求所使用的頻寬、並不會與其他包含 Aggregate 頻寬限制原則的較不明確的相符原則相較。對於所有其他限制類型、用戶端要求會延遲250毫秒、並針對超過任何相符原則限制的要求、收到503個慢速回應。

在Grid Manager中、您可以檢視交通路況圖表、並驗證原則是否強制實施您預期的流量限制。



== 將流量分類原則與SLA搭配使用

您可以將流量分類原則與容量限制和資料保護搭配使用、以強制執行服務層級協議（SLA）、以提供容量、資料保護和效能的詳細資訊。

以下範例顯示SLA的三層。您可以建立流量分類原則、以達成每個SLA層級的效能目標。

[cols="1a,1a,1a,1a,1a"]
|===
| 服務層級 | 容量 | 資料保護 | 允許的最大效能 | 成本 


 a| 
金級
 a| 
允許1 PB儲存容量
 a| 
3 複製 ILM 規則
 a| 
每秒 25 K 個要求

每秒 5 Gb （ 40 Gbps ）頻寬
 a| 
每月$$



 a| 
銀級
 a| 
允許 250 TB 儲存容量
 a| 
2 複製 ILM 規則
 a| 
每秒 10 萬次申請

1.25 GB/ 秒（ 10 Gbps ）頻寬
 a| 
每月$



 a| 
銅級
 a| 
允許 100 TB 儲存容量
 a| 
2 複製 ILM 規則
 a| 
每秒 5 K 個要求

每秒 1 Gb （ 8 Gbps ）頻寬
 a| 
每月$

|===