---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 租戶帳戶可讓您使用簡易儲存服務（ S3 ） REST API 來儲存及擷取 StorageGRID 系統中的物件。 
---
= 什麼是租戶帳戶？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租戶帳戶可讓您使用簡易儲存服務（ S3 ） REST API 來儲存及擷取 StorageGRID 系統中的物件。


TIP: Swift 詳細資料已從此文件網站版本中移除。請參閱。 https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8 ：管理租戶"^]

身為網格管理員、您可以建立和管理 S3 用戶端用來儲存和擷取物件的租戶帳戶。

每個租戶帳戶都有同盟或本機群組、使用者、 S3 貯體和物件。

租戶帳戶可用來分隔不同實體所儲存的物件。例如、多個租戶帳戶可用於下列任一使用案例：

* *企業使用案例：*如果您是在StorageGRID 企業應用程式中管理一套功能完善的系統、您可能會想要將網格的物件儲存區由組織中的不同部門加以隔離。在此案例中、您可以為行銷部門、客戶支援部門、人力資源部門等建立租戶帳戶。
+

NOTE: 如果您使用 S3 用戶端傳輸協定、則可以使用 S3 儲存區和儲存區原則來分隔企業各部門之間的物件。您不需要使用租戶帳戶。如需詳細資訊、請參閱實作說明link:../s3/bucket-and-group-access-policies.html["S3 貯體和貯體原則"]。

* *服務供應商使用案例：*如果您以StorageGRID 服務供應商的身份管理一個支援系統、則可以將網格的物件儲存區、由將儲存設備租賃至網格的不同實體來分隔。在這種情況下、您會為公司A、公司B、公司C等建立租戶帳戶。


如需更多資訊、請參閱 link:../tenant/index.html["使用租戶帳戶"]。



== 如何建立租戶帳戶？

使用 Grid Manager 建立租戶帳戶。建立租戶帳戶時、請指定下列資訊：

* 基本資訊、包括租戶名稱、用戶端類型（ S3 ）和選用的儲存配額。
* 租戶帳戶的權限、例如租戶帳戶是否可以使用 S3 平台服務、設定自己的身分識別來源、使用 S3 Select 或使用網格同盟連線。
* 租戶的初始根存取權、取決於 StorageGRID 系統是使用本機群組和使用者、身分識別聯盟或單一登入（ SSO ）。


此外、如果 S3 租戶帳戶需要符合法規要求、您可以為 StorageGRID 系統啟用 S3 物件鎖定設定。啟用S3物件鎖定時、所有S3租戶帳戶都能建立及管理相容的儲存區。



== 租戶管理程式的用途為何？

建立租戶帳戶之後、租戶使用者可以登入租戶管理員、以執行下列工作：

* 設定身分識別聯盟（除非身分識別來源與網格共用）
* 管理群組和使用者
* 使用網格同盟進行帳戶複製和跨網格複寫
* 管理S3存取金鑰
* 建立及管理 S3 儲存區
* 使用 S3 平台服務
* 使用S3 Select
* 監控儲存使用量



TIP: 雖然 S3 租戶使用者可以使用 Tenant Manager 來建立和管理 S3 存取金鑰和貯體、但他們必須使用 S3 用戶端應用程式來擷取和管理物件。如需詳細資訊、請參閱 link:../s3/index.html["使用S3 REST API"] 。
