---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: 若要儲存或擷取物件、 S3 用戶端應用程式會連線到負載平衡器服務（包含在所有管理節點和閘道節點上）、或是連接到所有儲存節點上的本機分配路由器（ LDR ）服務。 
---
= 摘要：用於用戶端連線的IP位址和連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要儲存或擷取物件、 S3 用戶端應用程式會連線到負載平衡器服務（包含在所有管理節點和閘道節點上）、或是連接到所有儲存節點上的本機分配路由器（ LDR ）服務。

用戶端應用程式可以使用網格節點的 IP 位址和該節點上服務的連接埠號碼、來連線至 StorageGRID 。您也可以建立高可用度（ HA ）負載平衡節點群組、以提供使用虛擬 IP （ VIP ）位址的高可用度連線。如果您想要使用完整網域名稱（ FQDN ）而非 IP 或 VIP 位址連線至 StorageGRID 、您可以設定 DNS 項目。

下表摘要說明用戶端連線StorageGRID 至靜態的不同方式、以及每種連線類型所使用的IP位址和連接埠。如果您已經建立負載平衡器端點和高可用度（ HA ）群組、請參閱<<何處可以找到 IP 位址>>如何在 Grid Manager 中找到這些值。

[cols="1a,1a,1a,1a"]
|===
| 連線位置 | 用戶端連線的服務 | IP 位址 | 連接埠 


 a| 
HA 群組
 a| 
負載平衡器
 a| 
HA群組的虛擬IP位址
 a| 
指派給負載平衡器端點的連接埠



 a| 
管理節點
 a| 
負載平衡器
 a| 
管理節點的IP位址
 a| 
指派給負載平衡器端點的連接埠



 a| 
閘道節點
 a| 
負載平衡器
 a| 
閘道節點的IP位址
 a| 
指派給負載平衡器端點的連接埠



 a| 
儲存節點
 a| 
LdR
 a| 
儲存節點的IP位址
 a| 
預設S3連接埠：

* HTTPS ： 18082
* HTTP ： 18084


|===


== URL 範例

若要將用戶端應用程式連線至 HA 群組的閘道節點負載平衡器端點、請使用如下所示的 URL 結構：

`https://_VIP-of-HA-group:LB-endpoint-port_`

例如、如果 HA 群組的虛擬 IP 位址為 192.0.2.5 、而負載平衡器端點的連接埠號碼為 10443 、則應用程式可以使用下列 URL 連線至 StorageGRID ：

`\https://192.0.2.5:10443`



== 何處可以找到 IP 位址

. 使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
. 若要尋找網格節點的IP位址：
+
.. 選擇*節點*。
.. 選取您要連線的管理節點、閘道節點或儲存節點。
.. 選擇* Overview（概述）*選項卡。
.. 在「節點資訊」區段中、記下節點的IP位址。
.. 選取*顯示更多*以檢視IPv6位址和介面對應。
+
您可以從用戶端應用程式建立連線至清單中的任何IP位址：

+
*** * eth0：* Grid Network
*** * eth1：*管理網路（選用）
*** * eth2：*用戶端網路（選用）
+

NOTE: 如果您正在檢視管理節點或閘道節點、且該節點是高可用度群組中的作用中節點、則HA群組的虛擬IP位址會顯示在eth2上。





. 若要尋找高可用度群組的虛擬IP位址：
+
.. 選擇*組態*>*網路*>*高可用度群組*。
.. 在表中、記下HA群組的虛擬IP位址。


. 若要尋找負載平衡器端點的連接埠號碼：
+
.. 選擇*組態*>*網路*>*負載平衡器端點*。
.. 記下您要使用的端點連接埠編號。
+

NOTE: 如果連接埠號碼為 80 或 443 、則端點只能在 Gateway 節點上設定、因為這些連接埠是保留在管理節點上。所有其他連接埠都在閘道節點和管理節點上設定。

.. 從表格中選取端點名稱。
.. 確認 * 用戶端類型 * （ S3 ）符合將使用端點的用戶端應用程式。



