---
permalink: admin/viewing-network-traffic-metrics.html 
sidebar: sidebar 
keywords: network traffic, traffic classification policy, monitor traffic 
summary: 您可以從「流量分類原則」頁面檢視可用的圖表、以監控網路流量。 
---
= 檢視網路流量指標
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「流量分類原則」頁面檢視可用的圖表、以監控網路流量。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:admin-group-permissions.html["root 存取權或 Tenant 帳戶權限"]。


.關於這項工作
對於任何現有的流量分類原則、您可以檢視負載平衡器服務的計量、以判斷原則是否成功限制網路中的流量。圖表中的資料可協助您判斷是否需要調整原則。

即使流量分類原則未設定任何限制、也會收集指標、圖表也會提供實用資訊、協助您瞭解流量趨勢。

.步驟
. 選擇*組態*>*網路*>*流量分類*。
+
此時會顯示「流量分類原則」頁面、並在表格中列出現有的原則。

. 選取您要檢視其度量的流量分類原則名稱。
. 選取 * 指標 * 索引標籤。
+
此時會出現流量分類原則圖表。這些圖表只會顯示符合所選原則之流量的度量。

+
頁面中包含下列圖表。

+
** 要求速率：此圖表提供所有負載平衡器所處理之此原則的頻寬量。收到的資料包括所有要求的要求標頭、以及包含實體資料的回應的實體資料大小。「已傳送」包含所有要求的回應標頭、以及回應中包含實體資料之要求的回應實體資料大小。
+

NOTE: 當要求完成時、此圖表只會顯示頻寬使用量。對於慢速或大型物件要求、實際的即時頻寬可能與此圖表中報告的值不同。

** 錯誤回應率：此圖表提供與此原則相符的要求將錯誤（ HTTP 狀態代碼 >=400 ）傳回用戶端的大約速率。
** 平均要求持續時間（非錯誤）：此圖表提供符合此原則之成功要求的平均持續時間。
** 原則頻寬使用量：此圖表提供所有負載平衡器所處理之符合此原則的頻寬量。收到的資料包括所有要求的要求標頭、以及包含實體資料的回應的實體資料大小。「已傳送」包含所有要求的回應標頭、以及回應中包含實體資料之要求的回應實體資料大小。


. 將游標放在折線圖上、即可在圖表的特定部分上看到值的快顯視窗。
. 選取 Metrics 標題下方的 * Grafana Dashboard * 、即可檢視原則的所有圖形。除了 * 指標 * 索引標籤中的四個圖形之外、您還可以檢視另外兩個圖形：
+
** 依物件大小寫入要求率：符合此原則的放置 / 張貼 / 刪除要求的速率。個別儲存格上的定位會顯示每秒的速率。懸停檢視中顯示的速率會被截斷為整數數、當貯體中有非零要求時、可能會報告 0 。
** 依物件大小讀取要求率：符合此原則的 GET / HEAD 要求率。個別儲存格上的定位會顯示每秒的速率。懸停檢視中顯示的速率會被截斷為整數數、當貯體中有非零要求時、可能會報告 0 。


. 或者、也可以從*支援*功能表存取圖表。
+
.. 選取*支援*>*工具*>*指標*。
.. 從 *Grafana* 區段中選取 * 交通分類政策 * 。
.. 從頁面左上角的功能表中選取原則。
.. 將游標放在圖形上方、即可看到快顯視窗、其中顯示樣本的日期和時間、彙總至計數的物件大小、以及該期間內每秒的要求數。
+
流量分類原則會以其ID來識別。原則 ID 會列在「流量分類原則」頁面上。



. 分析圖表、判斷原則限制流量的頻率、以及是否需要調整原則。

