---
permalink: s3/deprecated-get-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated GET compliance requests 
summary: Get Bucket法規遵循要求已過時。不過、您可以繼續使用此要求來判斷現有舊版相容儲存區目前有效的法規遵循設定。 
---
= 已過時：Get Bucket Compliance要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Get Bucket法規遵循要求已過時。不過、您可以繼續使用此要求來判斷現有舊版相容儲存區目前有效的法規遵循設定。

[NOTE]
====
先前版本的不支援《支援不符合要求》功能、現已由S3物件鎖定取代。StorageGRID StorageGRID如需詳細資訊、請參閱下列內容：

* link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"^]


====
您必須具有S3：GetBucketCompliance權限、或是帳戶root、才能完成此作業。



== 申請範例

此範例要求可讓您決定名為的貯體的符合性設定 `mybucket`。

[listing, subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 回應範例

在回應 XML 中、 `<SGCompliance>`列出有效的符合性設定。此回應範例顯示儲存區的法規遵循設定、其中每個物件將保留一年（525600分鐘）、從物件擷取到網格開始算起。此庫位目前沒有合法持有。每個物件將在一年後自動刪除。

[listing, subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
[cols="1a,2a"]
|===
| 名稱 | 說明 


 a| 
RetentionPeriodMinutes
 a| 
新增至此儲存區之物件的保留期間長度（以分鐘為單位）。保留期間是從物件擷取至網格時開始。



 a| 
LegalHold
 a| 
* 是：此儲存庫目前處於合法持有狀態。除非取消合法保留、否則無法刪除此貯體中的物件、即使保留期間已過期。
* 假：此庫位目前未合法持有。此儲存區中的物件可在保留期間到期時刪除。




 a| 
自動刪除
 a| 
* 是：此儲存區中的物件會在保留期間到期時自動刪除、除非儲存區處於合法持有狀態。
* 否：保留期間到期時、此儲存區中的物件不會自動刪除。如果需要刪除這些物件、您必須手動刪除這些物件。


|===


== 錯誤回應

如果建立的貯體不符合標準、則回應的 HTTP 狀態代碼為、 S3 錯誤代碼 `XNoSuchBucketCompliance`為 `404 Not Found`。
