---
permalink: s3/deprecated-put-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT deprecated compliance requests 
summary: 「放入時段」法規遵循要求已過時。不過、您可以繼續使用此要求來修改現有舊版相容桶的法規遵循設定。 
---
= StorageGRID 中已棄用的 PUT Bucket 合規性要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「放入時段」法規遵循要求已過時。不過、您可以繼續使用此要求來修改現有舊版相容桶的法規遵循設定。例如、您可以將現有的貯體置於合法持有狀態、或是延長保留期間。

[NOTE]
====
先前版本的不支援《支援不符合要求》功能、現已由S3物件鎖定取代。StorageGRID StorageGRID如需詳細資訊、請參閱下列內容：

* link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"^]


====
您必須具有S3：PuttBucketCompliance權限、或是帳戶root、才能完成此作業。

在發出「放入庫位」法規遵循要求時、您必須為法規遵循設定的每個欄位指定一個值。



== 申請範例

此範例要求會修改名為的貯體的符合性設定 `mybucket`。在此範例中、從物件擷取到網格開始、中的物件 `mybucket`現在會保留兩年（ 1 、 051,200 分鐘）、而不是一年。此庫位沒有合法持有。每個物件將在兩年後自動刪除。

[listing, subs="specialcharacters,quotes"]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization name_
Host: _host_
Content-Length: 152

<SGCompliance>
  <RetentionPeriodMinutes>1051200</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
[cols="1a,2a"]
|===
| 名稱 | 說明 


 a| 
RetentionPeriodMinutes
 a| 
新增至此儲存區之物件的保留期間長度（以分鐘為單位）。保留期間是從物件擷取至網格時開始。

* 重要 * 為 RetentionPeriodMinutes 指定新值時、您必須指定一個值、該值等於或大於該貯體目前的保留期間。設定貯體保留期間之後、您就無法減少該值、只能增加該值。



 a| 
LegalHold
 a| 
* 是：此儲存庫目前處於合法持有狀態。除非取消合法保留、否則無法刪除此貯體中的物件、即使保留期間已過期。
* 假：此庫位目前未合法持有。此儲存區中的物件可在保留期間到期時刪除。




 a| 
自動刪除
 a| 
* 是：此儲存區中的物件會在保留期間到期時自動刪除、除非儲存區處於合法持有狀態。
* 否：保留期間到期時、此儲存區中的物件不會自動刪除。如果需要刪除這些物件、您必須手動刪除這些物件。


|===


== 法規遵循設定的一致性

當您更新S3儲存區的法規遵循設定、並提出「置放儲存區法規遵循」要求時StorageGRID 、即可嘗試更新整個網格的儲存區中繼資料。根據預設、 StorageGRID 會使用 * 強式全域 * 一致性來保證所有資料中心站台和所有包含儲存區中繼資料的儲存節點、對於變更的法規遵循設定、都具有寫入後讀取一致性。

如果 StorageGRID 因為某個站台的資料中心站台或多個儲存節點無法使用而無法達到 * 強式全域 * 一致性、則回應的 HTTP 狀態代碼為 `503 Service Unavailable.`

如果您收到此回應、則必須聯絡網格管理員、以確保所需的儲存服務能夠儘快提供。如果網格管理員無法在每個網站上提供足夠的儲存節點、技術支援可能會強制使用 *Strong-site* 一致性、引導您重試失敗的要求。


CAUTION: 除非技術支援人員指示您遵守、否則切勿強迫 * 強式站台 * 一致性、除非您瞭解使用此層級的潛在後果。

當一致性降至 * 強式站台 * 時、 StorageGRID 保證更新的法規遵循設定只會對站台內的用戶端要求具有讀寫後一致性。這表示StorageGRID 在所有站台和儲存節點都可用之前、此儲存區的設定可能會暫時有多個不一致的設定。不一致的設定可能會導致非預期和非預期的行為。例如、如果您將貯體置於合法保留之下、而您強制降低一致性、則貯體先前的法規遵循設定（即合法保留）可能會繼續在某些資料中心站台生效。因此、您認為合法保留的物件、可能會在保留期間到期時遭到刪除、使用者或自動刪除（如果已啟用）。

若要強制使用 *Strong-site* 一致性、請重新發出 Put Bucket 符合性要求、並加入 `Consistency-Control` HTTP 要求標頭、如下所示：

[listing]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Consistency-Control: strong-site
----


== 錯誤回應

* 如果儲存區不是為了符合法規要求而建立、則回應的 HTTP 狀態代碼為 `404 Not Found`。
* 如果在要求中小於貯體目前的保留期間、則 `RetentionPeriodMinutes` HTTP 狀態代碼為 `400 Bad Request`。


.相關資訊
link:deprecated-put-bucket-request-modifications-for-compliance.html["已過時：將資源桶要求修改以符合法規要求"]
