---
permalink: s3/initiate-multipart-upload.html 
sidebar: sidebar 
keywords: initiate multipart upload, CreateMultipartUpload, upload ID 
summary: CreateMultipartupload 作業會啟動物件的多部分上傳、並傳回上傳 ID 。 
---
= 建立多個部分上傳
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CreateMultpartupload （先前命名為「 Initiate Multifart Upload 」（起始多重部分上傳））作業會啟動物件的多重部分上傳、並傳回上傳 ID 。

 `x-amz-storage-class`支援要求標頭。提交的值 `x-amz-storage-class`會影響 StorageGRID 在擷取期間保護物件資料的方式、而不會影響儲存在 StorageGRID 系統中的物件持續複本數量（由 ILM 決定）。

如果匹配已擷取物件的 ILM 規則使用 Strict link:../ilm/data-protection-options-for-ingest.html["擷取選項"]、則 `x-amz-storage-class`標頭不會生效。

下列值可用於 `x-amz-storage-class`：

* `STANDARD`（預設）
+
** * 雙重認可 * ：如果 ILM 規則指定「雙重認可擷取」選項、則只要物件擷取第二個物件複本、就會建立並發佈至不同的儲存節點（雙重認可）。評估 ILM 時、 StorageGRID 會判斷這些初始過渡複本是否符合規則中的放置指示。如果沒有、則可能需要在不同位置製作新的物件複本、而且可能需要刪除初始過渡複本。
** *Balanced * ：如果 ILM 規則指定 Balanced 選項、而 StorageGRID 無法立即製作規則中指定的所有複本、 StorageGRID 會在不同的儲存節點上製作兩個臨時複本。
+
如果 StorageGRID 可以立即建立 ILM 規則中指定的所有物件複本（同步放置）、則 `x-amz-storage-class`標頭不會生效。



* `REDUCED_REDUNDANCY`
+
** * 雙重認可 * ：如果 ILM 規則指定雙重認可選項、 StorageGRID 會在擷取物件時（單一認可）建立單一的臨時複本。
** *Balanced * ：如果 ILM 規則指定 Balanced 選項、則 StorageGRID 只會在系統無法立即製作規則中指定的所有複本時、才製作單一的臨時複本。如果能夠執行同步放置、則此標頭不會有任何影響。StorageGRID `REDUCED_REDUNDANCY`當符合物件的 ILM 規則建立單一複寫複本時、最好使用此選項。在這種情況下、使用 `REDUCED_REDUNDANCY`可避免在每次擷取作業中不必要地建立和刪除額外的物件複本。


+
在其他情況下不建議使用此 `REDUCED_REDUNDANCY`選項。 `REDUCED_REDUNDANCY`增加擷取期間物件資料遺失的風險。例如、如果單一複本一開始儲存在無法進行ILM評估的儲存節點上、則可能會遺失資料。




CAUTION: 在任何時間段只複寫一個複本、會使資料面臨永久遺失的風險。如果只有一個物件複寫複本存在、則當儲存節點故障或發生重大錯誤時、該物件就會遺失。在升級等維護程序期間、您也會暫時失去物件的存取權。

指定 `REDUCED_REDUNDANCY`僅會影響首次擷取物件時所建立的複本數量。它不會影響使用中 ILM 原則評估物件時所製作的物件複本數量、也不會導致資料儲存在 StorageGRID 系統中較低的備援層級。


NOTE: 如果您在啟用 S3 物件鎖定的情況下、將物件擷取至貯體、則會忽略此 `REDUCED_REDUNDANCY`選項。如果您正在將物件擷取至舊版的「符合標準」貯體、 `REDUCED_REDUNDANCY`則選項會傳回錯誤。執行「雙重承諾」的程序時、務必確保符合法規遵循要求。StorageGRID



== 支援的要求標頭

支援下列要求標頭：

* `Content-Type`
* `x-amz-checksum-algorithm`
+
目前僅支援的 SHA256 值 `x-amz-checksum-algorithm`。

* `x-amz-meta-`，然後是包含使用者定義中繼資料的名稱值配對
+
為使用者定義的中繼資料指定名稱值配對時、請使用以下一般格式：

+
[listing]
----
x-amz-meta-_name_: `value`
----
+
如果您要使用 * 使用者定義的建立時間 * 選項做為 ILM 規則的參考時間、則必須使用 `creation-time`做為物件建立時所記錄的中繼資料名稱。例如：

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
的值 `creation-time`會從 1970 年 1 月 1 日起計算為秒數。

+

NOTE: 如果您要將物件新增至已啟用舊版規範的儲存區、則不允許新增 `creation-time`為使用者定義的中繼資料。將傳回錯誤。

* S3物件鎖定要求標頭：
+
** `x-amz-object-lock-mode`
** `x-amz-object-lock-retain-until-date`
** `x-amz-object-lock-legal-hold`
+
如果提出的要求沒有這些標頭、則會使用儲存庫預設保留設定來計算物件版本的保留日期。

+
link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]



* SSe要求標頭：
+
** `x-amz-server-side-encryption`
** `x-amz-server-side-encryption-customer-key-MD5`
** `x-amz-server-side-encryption-customer-key`
** `x-amz-server-side-encryption-customer-algorithm`
+
<<要求伺服器端加密的標頭>>



+

NOTE: 有關 StorageGRID 如何處理 UTF-8 字元的資訊、請參閱link:put-object.html["PuttObject"]。





== 要求伺服器端加密的標頭

您可以使用下列要求標頭、以伺服器端加密來加密多部份物件。「SSE」和「SSE-C」選項互不相關。

* *SSE * ：如果您想使用由 StorageGRID 管理的唯一金鑰來加密物件、請在 CreateMultpartUpload 要求中使用下列標頭。請勿在任何上傳組件要求中指定此標頭。
+
** `x-amz-server-side-encryption`


* *SSE-C* ：如果您想要使用您提供和管理的唯一金鑰來加密物件、請在 CreateMultpartUpload 要求（以及每個後續的 UploadPart 要求）中使用這三個標頭。
+
** `x-amz-server-side-encryption-customer-algorithm`：指定 `AES256`。
** `x-amz-server-side-encryption-customer-key`：指定新物件的加密金鑰。
** `x-amz-server-side-encryption-customer-key-MD5`：指定新對象加密密鑰的 MD5 摘要。





CAUTION: 您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前，請先檢閱的考量事項link:using-server-side-encryption.html["使用伺服器端加密"]。



== 不支援的要求標頭

不支援下列要求標頭：

* `x-amz-website-redirect-location`
+
 `x-amz-website-redirect-location`報頭返回 `XNotImplemented`。





== 版本管理

多部分上傳包含不同的作業、可用於初始化上傳、列出上傳內容、上傳零件、組裝上傳的零件、以及完成上傳。執行「 CompleteMultpartUpload 」（ CompleteMultpartUpload ）作業時、即會建立物件（並在適用的情況下進行版本控制）。
