---
permalink: s3/operations-on-buckets.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: StorageGRID 系統最多可為每個 S3 租戶帳戶支援 5 、 000 個貯體。 
---
= 在貯體上作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 系統最多可為每個 S3 租戶帳戶支援 5 、 000 個貯體。

每個網格最多可有 100,000 個貯體。

若要支援 5 、 000 個貯體、網格中的每個儲存節點至少必須有 64 GB 的 RAM 。

貯體名稱限制遵循 AWS 美國標準地區限制、但您應進一步將它們限制在 DNS 命名慣例、以支援 S3 虛擬託管式要求。

如需詳細資訊、請參閱下列內容：

* https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html["Amazon Simple Storage Service 使用者指南：貯體配額、限制和限制"^]
* link:../admin/configuring-s3-api-endpoint-domain-names.html["設定 S3 端點網域名稱"]


ListObjects （ Get Bucket ）和 ListObjectVerions （ Get Bucket 物件版本）作業支援 StorageGRID link:consistency.html["一致性值"]。

您可以檢查是否為個別的儲存區啟用或停用上次存取時間的更新。請參閱。 link:get-bucket-last-access-time-request.html["取得時段上次存取時間"]

下表說明StorageGRID 了為什麼由Ss哪些 人執行S3 REST API貯體作業。若要執行上述任何作業、必須為帳戶提供必要的存取認證資料。

[cols="1a,3a"]
|===
| 營運 | 實作 


 a| 
建立庫位
 a| 
建立新的貯體。建立貯體後、您就成為了貯體的擁有者。

* 庫位名稱必須符合下列規則：
+
** 必須在各個StorageGRID 方面都是獨一無二的（不只是租戶帳戶內的獨特功能）。
** 必須符合DNS規範。
** 必須包含至少 3 個字元、不得超過 63 個字元。
** 可以是一或多個標籤的系列、相鄰的標籤以句點分隔。每個標籤都必須以英文字母或數字開頭和結尾、而且只能使用英文字母、數字和連字號。
** 不得看起來像是文字格式的IP位址。
** 不應在虛擬託管樣式要求中使用期間。期間會導致伺服器萬用字元憑證驗證發生問題。


* 根據預設、會在區域中建立貯 `us-east-1`體；不過、您可以使用 `LocationConstraint`要求主體中的 request 元素來指定不同的區域。使用該元素時 `LocationConstraint`、您必須指定使用 Grid Manager 或 Grid Management API 定義的確切區域名稱。如果您不知道應該使用的地區名稱、請聯絡您的系統管理員。
+
* 附註 * ：如果您的 CreateBucket 要求使用的區域尚未在 StorageGRID 中定義、則會發生錯誤。

* 您可以加入 `x-amz-bucket-object-lock-enabled`要求標頭、以建立啟用 S3 物件鎖定的貯體。請參閱。 link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]
+
建立儲存區時、您必須啟用S3物件鎖定。建立貯體後、您無法新增或停用 S3 物件鎖定。S3物件鎖定需要儲存區版本管理、這會在您建立儲存區時自動啟用。





 a| 
刪除Bucket
 a| 
刪除貯體。



 a| 
刪除 BucketCors
 a| 
刪除貯體的 CORS 組態。



 a| 
刪除 BucketEncryption
 a| 
刪除儲存區中的預設加密。現有的加密物件會保持加密狀態、但新增至儲存庫的任何新物件都不會加密。



 a| 
刪除 BucketLifecycle
 a| 
從貯體刪除生命週期組態。請參閱。 link:create-s3-lifecycle-configuration.html["建立S3生命週期組態"]



 a| 
刪除BucketPolicy
 a| 
刪除附加至貯體的原則。



 a| 
刪除 BucketReplication
 a| 
刪除附加至貯體的複寫組態。



 a| 
刪除 Bucketagging
 a| 
使用 `tagging`子資源從貯體中移除所有標記。

* 注意 * ：如果為此貯體設定非預設的 ILM 原則標籤、則會有一個 `NTAP-SG-ILM-BUCKET-TAG`已指派值的貯體標籤。如果有貯體標記、請勿發出刪除標記要求 `NTAP-SG-ILM-BUCKET-TAG`。相反地、只使用標記及其指派的值發出 PuttBucketTagged 要求 `NTAP-SG-ILM-BUCKET-TAG`、即可從貯體中移除所有其他標記。請勿修改或移除 `NTAP-SG-ILM-BUCKET-TAG`貯體標籤。



 a| 
GetBucketAcl
 a| 
傳回正面回應、以及貯體擁有者的 ID 、 DisplayName 和權限、表示擁有者擁有該貯體的完整存取權。



 a| 
GetBucketCors
 a| 
傳回 `cors`貯體的組態。



 a| 
GetBucketEncryption
 a| 
傳回儲存區的預設加密組態。



 a| 
GetBucketLifecycleConfiguration

（先前命名的 Get Bucket 生命週期）
 a| 
傳回貯體的生命週期組態。請參閱。 link:create-s3-lifecycle-configuration.html["建立S3生命週期組態"]



 a| 
GetBucketLocation
 a| 
傳回使用 CreateBucket 要求中的元素所設定的區域 `LocationConstraint`。如果貯體的區域為 `us-east-1`、則會傳回該區域的空字串。



 a| 
GetBucketNotificationConfiguration

（先前命名的 Get Bucket 通知）
 a| 
傳回附加至貯體的通知組態。



 a| 
GetBucketPolicy
 a| 
傳回附加至貯體的原則。



 a| 
GetBucketReplication
 a| 
傳回附加至貯體的複寫組態。



 a| 
GetBucketTagging
 a| 
使用 `tagging`子資源傳回貯體的所有標記。

* 注意 * ：如果為此貯體設定非預設的 ILM 原則標籤、則會有一個 `NTAP-SG-ILM-BUCKET-TAG`已指派值的貯體標籤。請勿修改或移除此標記。



 a| 
GetBucketVersion
 a| 
此實作使用 `versioning`子資源傳回貯體的版本設定狀態。

* _ 空白 _ ：版本設定從未啟用（儲存庫「未版本化」）
* 已啟用：已啟用版本管理
* 已暫停：先前已啟用版本管理、並已暫停




 a| 
GetObjectLockConfiguration
 a| 
如果已設定、則會傳回儲存區預設保留模式和預設保留期間。

請參閱。 link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]



 a| 
標題庫
 a| 
決定貯體是否存在、且您有存取權限。

此作業會傳回：

* `x-ntap-sg-bucket-id`： UUID 格式的儲存區 UUID 。
* `x-ntap-sg-trace-id`：關聯請求的唯一跟蹤 ID 。




 a| 
ListObjects 和 ListObjectsV2

（先前命名的 GET Bucket ）
 a| 
傳回貯體中的部分或全部物件（最多 1 、 000 個物件）。物件的儲存類別可以有兩個值、即使物件是使用儲存類別選項擷取 `REDUCED_REDUNDANCY`：

* `STANDARD`，表示物件儲存在由儲存節點組成的儲存資源池中。
* `GLACIER`、表示物件已移至 Cloud Storage Pool 指定的外部儲存區。


如果貯體包含大量具有相同首碼的刪除金鑰、回應可能會包含一些不包含金鑰的金鑰 `CommonPrefixes`。



 a| 
ListObjectVerions

（先前命名的 Get Bucket 物件版本）
 a| 
在貯體上具有讀取存取權、將此作業與子資源一起使用會 `versions`列出貯體中所有物件版本的中繼資料。



 a| 
PuttBucketCors
 a| 
設定貯體的 CORS 組態、以便該貯體能夠處理跨來源要求。跨來源資源共用（CORS）是一種安全機制、可讓單一網域中的用戶端Web應用程式存取不同網域中的資源。例如、假設您使用名為的 S3 儲存區 `images`來儲存圖形。透過設定貯體的 CORS 組態 `images`、您可以允許該貯體中的影像顯示在網站上 `+http://www.example.com+`。



 a| 
PuttBucketEncryption
 a| 
設定現有儲存區的預設加密狀態。啟用桶層級加密時、任何新增至桶的新物件都會加密。StorageGRID支援使用StorageGRID管理的金鑰進行伺服器端加密。指定伺服器端加密組態規則時，請將參數設定 `SSEAlgorithm`為 `AES256`，而不要使用 `KMSMasterKeyID`參數。

如果物件上傳要求已指定加密（亦即、如果要求包含要求標頭）、則會忽略貯體預設加密組態 `x-amz-server-side-encryption-*`。



 a| 
PuttBucketLifecycleConfiguration

（先前命名的 Put Bucket 生命週期）
 a| 
為貯體建立新的生命週期組態、或取代現有的生命週期組態。在生命週期組態中、支援多達1、000個生命週期規則。StorageGRID每個規則可包含下列XML元素：

* 到期（天數、日期、 ExpiredObjectDeleteMarker ）
* 非目前版本到期（ NewerNoncurrentVerions 、 NoncurrentDays ）
* 篩選器（前置、標記）
* 狀態
* ID


不支援下列動作：StorageGRID

* AbortIncompleteMultiPart上 傳
* 移轉


請參閱。 link:create-s3-lifecycle-configuration.html["建立S3生命週期組態"]若要瞭解貯體生命週期中的到期動作如何與 ILM 放置指示互動link:../ilm/how-ilm-operates-throughout-objects-life.html["ILM如何在整個物件生命週期內運作"]、請參閱。

*附註*：鏟斗生命週期組態可搭配已啟用S3物件鎖定的鏟斗使用、但舊型符合標準的鏟斗不支援鏟斗生命週期組態。



 a| 
PutBucketNotificationConfiguration

（先前命名的 Put Bucket 通知）
 a| 
使用要求主體中的通知組態 XML 來設定貯體通知。您應該瞭解下列實作詳細資料：

* StorageGRID 支援 Amazon Simple Notification Service （ Amazon SNS ）主題， Kafka 主題或 Webhook 端點作為目的地。不支援 Simple Queue Service （ SQS ）或 AWS Lambda 端點。
* 通知的目的地必須指定為StorageGRID 一個端點的URN。端點可以使用租戶管理程式或租戶管理API來建立。
+
端點必須存在、通知組態才能成功。如果端點不存在， `400 Bad Request`則會傳回錯誤代碼 `InvalidArgument`。

* 您無法設定下列事件類型的通知。這些事件類型*不支援*。
+
** `s3:ReducedRedundancyLostObject`
** `s3:ObjectRestore:Completed`


* 從 StorageGRID 傳送的事件通知使用標準 JSON 格式、但不包含某些金鑰、也不為其他金鑰使用特定值、如下表所示：
+
** *事件來源*
+
`sgws:s3`

** * awsRegion *
+
不含

** * X-amz-id-2*
+
不含

** * arn*
+
`urn:sgws:s3:::bucket_name`







 a| 
PuttBucketPolicy
 a| 
設定附加至貯體的原則。請參閱。 link:bucket-and-group-access-policies.html["使用貯體和群組存取原則"]



 a| 
PutBucketReplication
 a| 
使用要求主體中提供的複寫組態 XML 來設定link:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror 複寫"]貯體。對於CloudMirror複寫、您應該瞭解下列實作詳細資料：

* 僅支援複寫組態的V1。StorageGRID這表示 StorageGRID 不支援將元素用於規則、也不支援 `Filter`刪除物件版本的 V1 慣例。如需詳細資訊、請參閱 https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-add-config.html["Amazon Simple Storage Service 使用者指南：複寫組態"^]。
* 儲存區複寫可在版本控制或未版本控制的儲存區上進行設定。
* 您可以在複寫組態XML的每個規則中指定不同的目的地儲存區。來源儲存區可複寫至多個目的地儲存區。
* 目的地貯體必須指定為StorageGRID 租戶管理程式或租戶管理API中指定的非功能性端點的URN。請參閱。 link:../tenant/configuring-cloudmirror-replication.html["設定CloudMirror複寫"]
+
複寫組態必須存在端點才能成功。如果端點不存在、則要求會以失敗的方式失敗 `400 Bad Request`。錯誤訊息指出： `Unable to save the replication policy. The specified endpoint URN does not exist: _URN_.`

* 您不需要在組態 XML 中指定 `Role`。此值不供StorageGRID Some使用、如果提交、將會忽略此值。
* 如果您省略組態 XML 中的儲存類別、則 StorageGRID 預設會使用 `STANDARD`儲存類別。
* 如果您從來源儲存區刪除物件、或是刪除來源儲存區本身、跨區域複寫行為如下：
+
** 如果您在物件或貯體複寫之前刪除該物件或貯體、則不會複寫該物件 / 貯體、也不會通知您。
** 如果您在複寫物件或儲存區之後將其刪除、StorageGRID 則針對跨區域複寫的V1、執行標準Amazon S3刪除行為。






 a| 
PuttBucketTagging
 a| 
使用 `tagging`子資源來新增或更新貯體的一組標記。新增庫位標記時、請注意下列限制：

* 支援每個儲存區最多50個標籤的支援功能包括：StorageGRID
* 與庫位關聯的標記必須具有唯一的標記金鑰。標籤金鑰長度最多可達128個UNICODE字元。
* 標記值長度最多可達256個UNICODE字元。
* 金鑰和值區分大小寫。


* 注意 * ：如果為此貯體設定非預設的 ILM 原則標籤、則會有一個 `NTAP-SG-ILM-BUCKET-TAG`已指派值的貯體標籤。請確定 `NTAP-SG-ILM-BUCKET-TAG`貯體標籤已包含在所有 PuttBucketTagged 要求的指派值中。請勿修改或移除此標記。

* 附註 * ：此作業將覆寫貯體已有的任何目前標籤。如果集合中遺漏任何現有標記、則會移除該貯體的這些標記。



 a| 
PuttBucketVersion
 a| 
使用 `versioning`子資源來設定現有儲存區的版本設定狀態。您可以使用下列其中一個值來設定版本設定狀態：

* 已啟用：啟用儲存區中物件的版本管理。新增至儲存庫的所有物件都會收到唯一的版本ID。
* 暫停：停用儲存區中物件的版本設定。添加到桶中的所有對象都將接收版本 ID `null`。




 a| 
PutObjectLockConfiguration
 a| 
設定或移除貯體預設保留模式和預設保留期間。

如果修改了預設保留期間、現有物件版本的保留截止日期將維持不變、且不會使用新的預設保留期間重新計算。

如需詳細資訊、請參閱link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]。

|===