---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: 上傳 Part 作業會上傳物件的多部分上傳中的某個零件。 
---
= 上傳零件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
上傳 Part 作業會上傳物件的多部分上傳中的某個零件。



== 支援的要求標頭

支援下列要求標頭：

* `x-amz-checksum-sha256`
* `Content-Length`
* `Content-MD5`




== 要求伺服器端加密的標頭

如果您為 CreateMultpartUpload 要求指定了 SSE-C 加密、則每個 UploadPart 要求中也必須包含下列要求標頭：

* `x-amz-server-side-encryption-customer-algorithm`：指定 `AES256`。
* `x-amz-server-side-encryption-customer-key`：指定您在 CreateMultpartUpload 要求中提供的相同加密金鑰。
* `x-amz-server-side-encryption-customer-key-MD5`：指定您在 CreateMultpartUpload 要求中提供的相同 MD5 摘要。



CAUTION: 您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前，請先檢閱中的考量事項link:using-server-side-encryption.html["使用伺服器端加密"]。

如果您在 CreateMultipartUpload 要求期間指定了 SHA-256 Checksum 、則每個 UploadPart 要求中也必須包含下列要求標頭：

* `x-amz-checksum-sha256`：指定此零件的 SHA-256 總和檢查碼。




== 不支援的要求標頭

不支援下列要求標頭：

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`




== 版本管理

多部分上傳包含不同的作業、可用於初始化上傳、列出上傳內容、上傳零件、組裝上傳的零件、以及完成上傳。執行「 CompleteMultpartUpload 」（ CompleteMultpartUpload ）作業時、即會建立物件（並在適用的情況下進行版本控制）。
