---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: MIB 檔案包含有關網格中節點的受管理資源和服務內容的定義和資訊。您可以存取定義 StorageGRID 物件和通知的 MIB 檔案。這些檔案可用於監控您的網格。 
---
= 存取 MIB 檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MIB 檔案包含有關網格中節點的受管理資源和服務內容的定義和資訊。您可以存取定義 StorageGRID 物件和通知的 MIB 檔案。這些檔案可用於監控您的網格。

如需 SNMP 和 MIB 檔案的詳細資訊、請參閱link:using-snmp-monitoring.html["使用SNMP監控"]。



== 存取 MIB 檔案

請依照下列步驟存取 MIB 檔案。

.步驟
. 選擇*設定* > *監控* > *SNMP 代理程式*。
. 在 SNMP 代理程式頁面上、選取您要下載的檔案：
+
** *NetApp-STORAGEGRID-MIB.txt* ：定義可在所有管理節點上存取的警示表和通知（陷阱）。
** *ES-NetApp-06-MIB.mIB* ：定義 E 系列應用裝置的物件和通知。
** *MIB_1_10.zip* ：定義具有 BMC 介面的應用裝置物件和通知。
+

TIP: 您也可以在任何 StorageGRID 節點上的下列位置存取 MIB 檔案： `/usr/share/snmp/mibs`



. 若要從 MIB 檔案擷取 StorageGRID OID ：
+
.. 取得 StorageGRID MIB 根目錄的 OID ：
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
結果： `.1.3.6.1.4.1.789.28669` (`28669`永遠是 StorageGRID 的 oID ）

.. 在整個樹狀結構中的 StorageGRID OID （ `paste`用於連接線）：
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`

+

TIP: 此 `snmptranslate`命令有許多選項可用於探索 MIB 。此命令可在任何 StorageGRID 節點上使用。







== MIB 檔案內容

所有物件都位於 StorageGRID OID 之下。

[cols="1a,1a,2a"]
|===
| 物件名稱 | 物件 ID （ OID ） | 說明 


| .iso.org.dod.internet 。+ 私有企業。+ NetApp.storagegrid | 1.3.6.1.4.1.789.28669  a| 
NetApp StorageGRID 實體的 MIB 模組。

|===


== MIB 物件

[cols="1a,1a,1a,1a,1a,2a"]
|===
| 物件名稱 | 物件 ID （ OID ） | 類型 | 使用權 | MIB 模組 | 說明 


| activeAlertCount | 1.3.6.1.4.1.+ 789.28669.1.3  a| 
Integer32
 a| 
只讀
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
activeAlertTable 中作用中警示的數量。



| activeAlertTable | 1.3.6.1.4.1.+ 789.28669.1.4  a| 
ActiveAlertEntry 的序列
 a| 
不可訪問
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
StorageGRID 中作用中警示的表格。



| 活動警報條目 | .1.3.6.1.4.1.  + 789.28669.1.4.1  a| 
順序
 a| 
不可訪問
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
單一StorageGRID警報，按警報 ID 索引。



| activeAlertId | 1.3.6.1.4.1.+ 789.28669.1.4.1.1  a| 
八位元位元組串
 a| 
只讀
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
警示的 ID 。僅在目前的一組作用中警示中是唯一的。



| activeAlertName | 1.3.6.1.4.1.+ 789.28669.1.4.1.2  a| 
八位元位元組串
 a| 
只讀
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
警示的名稱。



| activeAlertInstance | 1.3.6.1.4.1.+ 789.28669.1.4.1.3  a| 
八位元位元組串
 a| 
只讀
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
產生警示的實體名稱、通常是節點名稱。



| 行動警示嚴重性 | 1.3.6.1.4.1.+ 789.28669.1.4.1.4  a| 
八位元位元組串
 a| 
只讀
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
警示的嚴重性。



| activeAlertStartTime | 1.3.6.1.4.1.+ 789.28669.1.4.1.5  a| 
日期和時間
 a| 
只讀
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
觸發警報的時間。

|===