---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: 您可以擷取 StorageGRID 記錄檔和系統資料，包括組態資料，並將其傳送給技術支援部門。 
---
= 收集記錄檔和系統資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以擷取 StorageGRID 記錄檔和系統資料，包括組態資料，並將其傳送給技術支援部門。

.開始之前
* 您可以使用登入主要管理節點上的 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有 link:../admin/admin-group-permissions.html["特定存取權限"]。
* 您有資源配置通關密碼。


.關於這項工作
使用 Grid Manager link:logs-files-reference.html["記錄檔"]，在您選取的期間內，從任何網格節點收集，系統資料和組態資料。資料會收集並歸檔在檔案中 `.tar.gz`，然後下載到您的本機電腦，或傳送到技術支援部門。

您也可以變更稽核記錄的目的地、並將稽核資訊傳送至外部syslog伺服器。設定外部syslog伺服器時、仍會繼續產生及儲存稽核記錄的本機記錄。請參閱。 link:../monitor/configure-audit-messages.html["設定稽核訊息和外部 Syslog 伺服器"]

.步驟
. 選擇*支援*>*工具*>*記錄*。隨即顯示節點表。
. 選取您要收集記錄檔的網格節點。
+
您可以依節點名稱，站台和節點類型排序。「站台」和「節點」類型欄包含篩選條件，可依個別站台和節點類型進行選取。

. 選擇*繼續*。
. 選取要包含在記錄檔中的資料日期和時間範圍。
+
如果您選取一個非常長的時間段、或是從大型網格中的所有節點收集記錄、則記錄歸檔可能變得太大、無法儲存在節點上、或太大、無法收集到主要管理節點下載。如果發生這兩種情況，請以較小的資料集重新啟動記錄收集。

. 選取您要收集的記錄類型。
+
** * 應用程式記錄 * ：技術支援最常用於疑難排解的應用程式專屬記錄。收集的記錄是可用應用程式記錄的子集。
** * 稽核記錄 * ：包含在正常系統作業期間所產生稽核訊息的記錄。
** * 網路追蹤 * ：用於網路偵錯的記錄檔。
** * Prometheus 資料庫 * ：所有節點上服務的時間系列指標。


. 您也可以選擇使用 *Notes* 文字方塊來輸入您正在收集之記錄檔的備註。
+
您可以使用這些附註、提供有關問題的技術支援資訊、以提示您收集記錄檔。您的筆記會新增至名為的檔案 `info.txt`、以及其他有關記錄檔集合的資訊。 `info.txt`檔案會儲存在記錄檔歸檔套件中。

. 在 * 資源配置複雜密碼 * 文字方塊中，輸入 StorageGRID 系統的資源配置複雜密碼。
. 選取 * 收集記錄 * 。
+
您可以使用「記錄」頁面來監控每個網格節點的記錄檔集合進度。

+
如果您收到記錄大小的錯誤訊息、請嘗試收集較短時間內的記錄、或是收集較少節點的記錄。

. 如果記錄收集失敗：
+
** 如果出現「記錄收集失敗」訊息，您可以重試記錄收集或完成工作階段，而無需重試。
** 如果出現「記錄集合部分失敗」訊息，您可以重試記錄集合，完成工作階段，下載部分記錄檔，或將部分記錄檔傳送至 AutoSupport 。


. 記錄檔收集完成時：
+
** 選取 * 下載 * 以下載 `.tar.gz`檔案。
** 選取 * 傳送至 AutoSupport * ，將檔案傳送至 `.tar.gz`技術支援。
+
此 `.tar.gz`檔案包含所有網格節點中的所有記錄檔，其中記錄集合成功。合併的 `.tar.gz`檔案包含每個網格節點的一個記錄檔歸檔。

+
AutoSupport 套件的主旨是 `USER_TRIGGERED_SUPPORT_BUNDLE`。



. 選擇*完成*。
+

CAUTION:  `.tar.gz`當您選取 * 完成 * 時，檔案會被刪除。請務必先下載或傳送檔案。


