---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: 您可以檢索StorageGRID日誌檔案和系統資料（包括設定資料），並將其傳送給技術支援。 
---
= 收集記錄檔和系統資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢索StorageGRID日誌檔案和系統資料（包括設定資料），並將其傳送給技術支援。

.開始之前
* 您已使用任意管理節點登入網格管理器link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有 link:../admin/admin-group-permissions.html["特定存取權限"]。
* 您有資源配置通關密碼。


.關於這項工作
使用網格管理器來收集link:logs-files-reference.html["記錄檔"]、系統資料和來自任何網格節點的您選擇的時間段的配置資料。資料被收集並歸檔在 `.tar.gz`然後您可以將其下載到本機電腦或傳送給技術支援。

或者，您可以變更稽核日誌的目標並將稽核資訊傳送至外部系統日誌伺服器。當設定外部系統日誌伺服器時，將繼續產生和儲存稽核記錄的本機日誌。看link:../monitor/configure-log-management.html["設定日誌管理和外部系統日誌伺服器"] 。

.步驟
. 選擇*支援* > *工具* > *日誌收集*。顯示節點表。
. 選取您要收集記錄檔的網格節點。
+
您可以按節點名稱、網站和節點類型進行排序。站點和節點類型列包含按單一站點和節點類型選擇的篩選器。

. 選擇*繼續*。
. 選擇要包含在日誌檔案中的資料的日期和時間範圍。
+
如果您選擇很長的時間段或從大型網格中的所有節點收集日誌，則日誌存檔可能會變得太大而無法儲存在節點上，或者太大而無法由管理節點收集進行下載。如果發生任何一種情況，請使用較小的資料集重新開始日誌收集。

. 選取您要收集的記錄類型。
+
** *應用程式日誌*：技術支援最常用於故障排除的應用程式特定日誌。收集的日誌是可用應用程式日誌的子集。
** *稽核日誌*：包含系統正常運作期間產生的稽核訊息的日誌。
** *網路追蹤*：用於網路偵錯的日誌。
** *Prometheus 資料庫*：來自所有節點上的服務的時間序列指標。


. 或者，使用 *Notes* 文字方塊輸入有關您正在收集的日誌檔案的註解。
+
您可以使用這些附註、提供有關問題的技術支援資訊、以提示您收集記錄檔。您的筆記會新增至名為的檔案 `info.txt`、以及其他有關記錄檔集合的資訊。 `info.txt`檔案會儲存在記錄檔歸檔套件中。

. 在 *Provisioning passphrase* 文字方塊中，輸入StorageGRID系統的設定密碼。
. 選擇*收集日誌*。
+
您可以使用日誌收集頁面來監控每個網格節點的日誌檔案收集進度。

+
如果您收到記錄大小的錯誤訊息、請嘗試收集較短時間內的記錄、或是收集較少節點的記錄。

. 如果日誌收集失敗：
+
** 如果出現「日誌收集失敗」訊息，您可以重試日誌收集或完成會話而無需重試。
** 如果出現「日誌收集部分失敗」訊息，您可以重試日誌收集、完成會話、下載部分日誌檔案或將部分日誌檔案傳送至AutoSupport。


. 當日誌檔案收集完成：
+
** 選擇*下載*下載 `.tar.gz`文件。
** 選擇“發送至AutoSupport”以發送 `.tar.gz`文件發送給技術支援。
+
這 `.tar.gz`檔案包含所有成功收集日誌的網格節點的所有日誌檔案。合併後的 `.tar.gz`檔案包含每個網格節點的一個日誌檔案存檔。

+
AutoSupport軟體套件的主題是 `USER_TRIGGERED_SUPPORT_BUNDLE`。



. 選擇*完成*。
+

CAUTION: 這 `.tar.gz`當您選擇*完成*時，檔案將被刪除。請確保您先下載或傳送該檔案。


