---
permalink: monitor/configuring-snmp-agent.html 
sidebar: sidebar 
keywords: snmp agent, mib, trap, inform 
summary: 您可以將 StorageGRID SNMP 代理程式設定為使用協力廠商 SNMP 管理系統來進行唯讀 MIB 存取和通知。 
---
= 設定SNMP代理程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將 StorageGRID SNMP 代理程式設定為使用協力廠商 SNMP 管理系統來進行唯讀 MIB 存取和通知。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:../admin/admin-group-permissions.html["root 存取權限"]。


.關於這項工作
StorageGRID SNMP 代理程式支援 SNMPv1 、 SNMPv2c 和 SNMPv3 。您可以為代理程式設定一或多個版本。對於 SNMPv3 、僅支援使用者安全模式（ USM ）驗證。

網格中的所有節點都使用相同的 SNMP 組態。



== 指定基本組態

首先、請啟用 StorageGRID SMNP 代理程式、並提供基本資訊。

.步驟
. 選擇*設定* > *監控* > *SNMP 代理程式*。
+
此時將顯示 SNMP 代理程式頁面。

. 若要在所有網格節點上啟用 SNMP 代理程式、請選取 * 啟用 SNMP* 核取方塊。
. 在「基本組態」區段中輸入下列資訊。
+
[cols="1a,2a"]
|===
| 欄位 | 說明 


 a| 
系統聯絡人
 a| 
選用。StorageGRID 系統的主要聯絡人、會以系統聯絡人的形式在 SNMP 訊息中傳回。

系統聯絡人通常是電子郵件地址。此值適用於 StorageGRID 系統中的所有節點。* 系統連絡人 * 最多可有 255 個字元。



 a| 
系統位置
 a| 
選用。StorageGRID 系統的位置、會以 sysLocation 的形式在 SNMP 訊息中傳回。

系統位置可以是任何有助於識別 StorageGRID 系統所在位置的資訊。例如、您可以使用設施的街道地址。此值適用於 StorageGRID 系統中的所有節點。* 系統位置 * 最多可有 255 個字元。



 a| 
啟用 SNMP 代理程式通知
 a| 
** 如果選取此選項、 StorageGRID SNMP 代理程式會傳送設陷和通知通知。
** 如果未選取、則 SNMP 代理程式支援唯讀 MIB 存取、但不會傳送任何 SNMP 通知。




 a| 
啟用驗證陷阱
 a| 
如果選取此選項、 StorageGRID SNMP 代理程式會在收到驗證不正確的通訊協定訊息時傳送驗證陷阱。

|===




== 輸入社群字串

如果您使用 SNMPv1 或 SNMPv2c 、請填寫社群字串一節。

當管理系統查詢StorageGRID 到這個功能時、它會傳送一個社群字串。如果社群字串符合此處指定的其中一個值、SNMP代理程式會傳送回應給管理系統。

.步驟
. 對於 * 唯讀社群 * 、可選擇性地輸入社群字串、以允許對 IPv4 和 IPv6 代理程式位址進行唯讀 MIB 存取。
+

TIP: 為了確保 StorageGRID 系統的安全性、請勿使用「 public 」作為社群字串。如果將此欄位保留空白、 SNMP 代理程式會使用 StorageGRID 系統的網格 ID 做為社群字串。

+
每個社群字串最多可以有 32 個字元、而且不能包含空白字元。

. 選取 * 新增其他社群字串 * 以新增其他字串。
+
最多允許五個字串。





== [[SELECT （選取） TRAP_DESTIN] ：建立設陷目的地

使用「其他組態」區段中的「設陷目的地」索引標籤、可定義 StorageGRID 設陷或通知通知通知的一個或多個目的地。當您啟用 SNMP 代理程式並選取 * 儲存 * 時、 StorageGRID 會在觸發警示時、將通知傳送至每個定義的目的地。也會針對支援的MIB-II實體（例如ifdown和coldStart）傳送標準通知。

.步驟
. 在 * 預設設陷社群 * 欄位中、選擇性地輸入您要用於 SNMPv1 或 SNMPv2 設陷目的地的預設社群字串。
+
根據需要、您可以在定義特定陷阱目的地時、提供不同的（「自訂」）社群字串。

+
* 預設設陷社群 * 最多可有 32 個字元、且不可包含空格字元。

. 若要新增設陷目的地、請選取 * 建立 * 。
. 選取要用於此設陷目的地的 SNMP 版本。
. 針對您選取的版本填寫「建立設陷目的地」表單。
+
[role="tabbed-block"]
====
.SNMPv1
--
如果您選取的是 SNMPv1 版本、請填寫這些欄位。

[cols="1a,2a"]
|===
| 欄位 | 說明 


 a| 
類型
 a| 
必須是 SNMPv1 的陷阱。



 a| 
主機
 a| 
用於接收陷阱的 IPv4 或 IPv6 位址或完整網域名稱（ FQDN ）。



 a| 
連接埠
 a| 
使用 162 、這是 SNMP 設陷的標準連接埠、除非您必須使用其他值。



 a| 
傳輸協定
 a| 
除非您需要使用 TCP 、否則請使用標準 SNMP 設陷傳輸協定的 UDP 。



 a| 
社群字串
 a| 
如果指定了預設陷阱社群、請使用該陷阱社群、或為此陷阱目的地輸入自訂社群字串。

自訂社群字串最多可以有 32 個字元、而且不能包含空格。

|===
--
.SNMPv2c
--
如果您選取的是 SNMPv2c 版本、請填寫這些欄位。

[cols="1a,2a"]
|===
| 欄位 | 說明 


 a| 
類型
 a| 
目的地將用於陷阱還是通知。



 a| 
主機
 a| 
接收陷阱的 IPv4 或 IPv6 位址或 FQDN 。



 a| 
連接埠
 a| 
使用 162 、這是 SNMP 設陷的標準連接埠、除非您必須使用其他值。



 a| 
傳輸協定
 a| 
除非您需要使用 TCP 、否則請使用標準 SNMP 設陷傳輸協定的 UDP 。



 a| 
社群字串
 a| 
如果指定了預設陷阱社群、請使用該陷阱社群、或為此陷阱目的地輸入自訂社群字串。

自訂社群字串最多可以有 32 個字元、而且不能包含空格。

|===
--
.SNMPv3
--
如果您選取的是 SNMPv3 版本、請填寫這些欄位。

[cols="1a,2a"]
|===
| 欄位 | 說明 


 a| 
類型
 a| 
目的地將用於陷阱還是通知。



 a| 
主機
 a| 
接收陷阱的 IPv4 或 IPv6 位址或 FQDN 。



 a| 
連接埠
 a| 
使用 162 、這是 SNMP 設陷的標準連接埠、除非您必須使用其他值。



 a| 
傳輸協定
 a| 
除非您需要使用 TCP 、否則請使用標準 SNMP 設陷傳輸協定的 UDP 。



 a| 
USM使用者
 a| 
將用於驗證的 USM 使用者。

** 如果您選取* Trap *、則只會顯示沒有授權引擎ID的USM使用者。
** 如果您選取* INFUS*、則只會顯示具有驗證引擎ID的USM使用者。
** 如果沒有顯示使用者：
+
... 建立並儲存設陷目的地。
... 前往<<create-usm-users,建立 USM 使用者>>並建立使用者。
... 返回「設陷目的地」標籤、從表格中選取儲存的目的地、然後選取 * 編輯 * 。
... 選取使用者。




|===
--
====
. 選擇* Create *（建立*）。
+
陷阱目的地隨即建立並新增至表格。





== 建立代理程式位址

或者、您也可以使用「其他組態」區段中的「值機員位址」標籤來指定一或多個「接聽位址」。這些是 SNMP 代理程式可以接收查詢的 StorageGRID 位址。

如果您未設定代理程式位址、則所有 StorageGRID 網路上的預設聆聽位址為 UDP 連接埠 161 。

.步驟
. 選擇* Create *（建立*）。
. 輸入下列資訊。
+
[cols="1a,2a"]
|===
| 欄位 | 說明 


 a| 
網際網路傳輸協定
 a| 
此位址是使用 IPv4 還是 IPv6 。

依預設、SNMP使用的是IPV4。



 a| 
傳輸傳輸傳輸協定
 a| 
此位址是使用 UDP 還是 TCP 。

依預設、SNMP使用的是udp。



 a| 
StorageGRID 網路
 a| 
代理程式將接聽的 StorageGRID 網路。

** 網格、管理和用戶端網路： SNMP 代理程式會在所有三個網路上接聽查詢。
** 網格網路
** 管理網路
** 用戶端網路
+
* 注意 * ：如果您使用 Client Network 取得不安全的資料、並為 Client Network 建立代理程式位址、請注意、 SNMP 流量也不安全。





 a| 
連接埠
 a| 
（可選） SNMP 代理應偵聽的端口號。

SNMP代理程式的預設udp連接埠為161、但您可以輸入任何未使用的連接埠號碼。

* 注意 * ：儲存 SNMP 代理程式時、 StorageGRID 會自動開啟內部防火牆上的代理程式位址連接埠。您必須確保任何外部防火牆都允許存取這些連接埠。

|===
. 選擇* Create *（建立*）。
+
代理程式位址隨即建立並新增至表格。





== [[create-USM-us者 ]] 建立 USM 使用者

如果您使用的是 SNMPv3 、請使用「其他組態」區段中的 USM 使用者索引標籤、定義授權查詢 MIB 或接收設陷並通知的 USM 使用者。


NOTE: 對於 SNMPv3 _trap_ 目的地，建議為每個管理節點建立一個 USM 使用者。如果每個管理節點都沒有 USM 用戶，當主管理節點發生故障時，您的管理系統可能會停止接收通知。


NOTE: SNMPv3 通知目的地必須有具有引擎 ID 的使用者。SNMPv3 _trap 目的地無法擁有具有引擎 ID 的使用者。

如果您只使用 SNMPv1 或 SNMPv2c 、則不適用這些步驟。

.步驟
. 選擇* Create *（建立*）。
. 輸入下列資訊。
+
[cols="1a,2a"]
|===
| 欄位 | 說明 


 a| 
使用者名稱
 a| 
此 USM 使用者的唯一名稱。

使用者名稱最多可以有 32 個字元、而且不能包含空格字元。建立使用者後、無法變更使用者名稱。



 a| 
唯讀 MIB 存取
 a| 
如果選取此選項、則此使用者應擁有 MIB 的唯讀存取權。



 a| 
授權引擎 ID
 a| 
如果此使用者將用於通知目的地、則為此使用者的授權引擎 ID 。

輸入 10 至 64 個十六進位字元（ 5 至 32 位元組）、不含空格。此值是 USM 使用者所需的、將會在陷阱目的地中選取以通知。將在陷阱目的地中選取的 USM 使用者不允許使用此值。

* 注意 * ：如果您選取 * 唯讀 MIB 存取 * 、則不會顯示此欄位、因為擁有唯讀 MIB 存取權的 USM 使用者無法擁有引擎 ID 。



 a| 
安全性層級
 a| 
USM 使用者的安全層級：

** *驗證權限*：此使用者與驗證和隱私權（加密）通訊。您必須指定驗證傳輸協定和密碼、以及隱私權傳輸協定和密碼。
** *驗證NoPrimv*：此使用者可與驗證通訊、且無隱私權（無加密）。您必須指定驗證傳輸協定和密碼。




 a| 
驗證傳輸協定
 a| 
請務必設定為 SHA 、這是唯一支援的傳輸協定（ HMAC-SHA-96 ）。



 a| 
密碼
 a| 
此使用者將用於驗證的密碼。



 a| 
隱私權傳輸協定
 a| 
僅當您選擇 *authPrimv* 並始終設置爲 AES 時顯示，這是唯一支持的隱私協議。



 a| 
密碼
 a| 
僅當您選擇了 *authPrimv* 時才顯示。此使用者將用於隱私的密碼。

|===
. 選擇* Create *（建立*）。
+
系統會建立USM使用者並將其新增至表格。

. 完成 SNMP 代理程式組態後、請選取 * 儲存 * 。
+
新的SNMP代理程式組態會變成作用中狀態。


