---
permalink: monitor/monitoring-information-lifecycle-management.html 
sidebar: sidebar 
keywords: lifecycle management, lifecycle, monitoring, ILM, information lifecycle management 
summary: 資訊生命週期管理（ILM）系統可為儲存在網格上的所有物件提供資料管理功能。您必須監控 ILM 作業、以瞭解網格是否能處理目前負載、或是否需要更多資源。 
---
= 監控資訊生命週期管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資訊生命週期管理（ILM）系統可為儲存在網格上的所有物件提供資料管理。您必須監控 ILM 作業、以瞭解網格是否能處理目前負載、或是否需要更多資源。

.關於這項工作
StorageGRID 系統會套用主動式 ILM 原則來管理物件。ILM 原則和相關的 ILM 規則決定製作多少份複本、建立的複本類型、放置複本的位置、以及每份複本的保留時間長度。

物件擷取和其他物件相關活動可能會超過 StorageGRID 評估 ILM 的速度、導致系統將無法即時完成 ILM 放置指示的物件排入佇列。您應該監控 StorageGRID 是否與用戶端動作保持一致。



== 使用 Grid Manager 儀表板索引標籤

.步驟
使用 Grid Manager 儀表板上的 ILM 索引標籤來監控 ILM 作業：

. 登入Grid Manager。
. 從儀表板選取 ILM 索引標籤、並記下 ILM 佇列（物件）卡和 ILM 評估率卡上的值。
+
儀表板上的 ILM 佇列（物件）卡可能會暫時尖峰。但是如果佇列持續增加且永不減少、則網格需要更多資源才能有效運作：增加儲存節點、或是 ILM 原則將物件置於遠端位置、則需要更多網路頻寬。





== 使用節點頁面

.步驟
此外、請使用 * 節點 * 頁面調查 ILM 佇列：


NOTE: 在未來的 StorageGRID 版本中、 * 節點 * 頁面上的圖表將會取代為對應的儀表板卡。

. 選擇*節點*。
. 選擇*網格名稱_*>* ILM *。
. 將游標放在 ILM 佇列圖形上、即可在指定時間點查看下列屬性的值：
+
** *排入佇列的物件（來自用戶端作業）*：因為用戶端作業（例如擷取）而等待ILM評估的物件總數。
** *排入佇列的物件（來自所有作業）*：等待ILM評估的物件總數。
** *掃描速率（物件數/秒）*：網格中的物件在ILM中掃描並排入佇列的速率。
** *評估率（物件數/秒）*：根據網格中的ILM原則評估物件的目前速度。


. 在「ILM佇列」區段中、查看下列屬性。
+

NOTE: ILM 佇列區段僅適用於網格。此資訊不會顯示在站台或儲存節點的ILM索引標籤上。

+
** * 掃描週期 - 預估 * ：完成所有物件完整 ILM 掃描的預估時間。
+

NOTE: 完整掃描並不保證ILM已套用至所有物件。

** * 嘗試的修復 * ：已嘗試複寫資料的物件修復作業總數。每次儲存節點嘗試修復高風險物件時、此計數就會遞增。如果網格忙碌、高風險的ILM修復會優先處理。
+

NOTE: 如果在修復之後複寫失敗、相同的物件修復可能會再次遞增。



+
當您正在監控儲存節點磁碟區恢復的進度時、這些屬性會很有用。如果嘗試的維修次數已停止增加、且已完成完整掃描、則可能已完成維修。


