---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: 如果您使用負載平衡器來管理用戶端與StorageGRID VMware的連線、則應先設定系統、然後在進行任何組態變更或執行擴充之後、監控負載平衡作業。 
---
= 監控負載平衡作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用負載平衡器來管理用戶端與StorageGRID VMware的連線、則應先設定系統、然後在進行任何組態變更或執行擴充之後、監控負載平衡作業。

.關於這項工作
您可以使用管理節點或閘道節點上的負載平衡器服務、或外部協力廠商負載平衡器、將用戶端要求分散到多個儲存節點上。

設定負載平衡之後、您應該確認物件擷取和擷取作業在儲存節點之間平均分散。平均分散的要求可確保StorageGRID 在負載下、不影響到客戶要求的回應能力、並有助於維持用戶端效能。

如果您在主動備份模式中設定了閘道節點或管理節點的高可用度（HA）群組、則群組中只有一個節點會主動散佈用戶端要求。

如需更多資訊、請參閱 link:../admin/configuring-client-connections.html["設定 S3 用戶端連線"]。

.步驟
. 如果 S3 用戶端使用負載平衡器服務進行連線、請檢查管理節點或閘道節點是否正在依您預期的方式主動分配流量：
+
.. 選擇*節點*。
.. 選取閘道節點或管理節點。
.. 在 * 概述 * 標籤上、檢查節點介面是否位於 HA 群組中、以及節點介面是否具有「主要」角色。
+
具有「主要」角色的節點和不在 HA 群組中的節點應主動將要求發佈給用戶端。

.. 對於每個應該主動分配用戶端要求的節點，請選取link:viewing-load-balancer-tab.html["負載平衡器索引標籤"]。
.. 檢閱上週的負載平衡器要求流量圖表、確保節點已主動散佈要求。
+
主動備份HA群組中的節點可能會不時扮演備份角色。在此期間、節點不會散佈用戶端要求。

.. 檢閱上週負載平衡器傳入要求率圖表、以檢閱節點的物件處理量。
.. 對StorageGRID 整個系統中的每個管理節點或閘道節點重複這些步驟。
.. 或者、您也可以使用流量分類原則來檢視負載平衡器服務所提供流量的更詳細分析。


. 請確認這些要求平均分散到儲存節點。
+
.. 選擇「*儲存節點_*」>「* LdR*」>「* HTTP *」。
.. 檢閱*目前建立的傳入工作階段數目*。
.. 針對網格中的每個儲存節點重複上述步驟。
+
所有儲存節點之間的工作階段數量應大致相同。




