---
permalink: monitor/updating-snmp-agent.html 
sidebar: sidebar 
keywords: how to update the SNMP agent 
summary: 您可以停用 SNMP 通知、更新社群字串、或新增或移除代理程式位址、 USM 使用者和設陷目的地。 
---
= 更新SNMP代理程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以停用 SNMP 通知、更新社群字串、或新增或移除代理程式位址、 USM 使用者和設陷目的地。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:../admin/admin-group-permissions.html["root 存取權限"]。


.關於這項工作
如需 SNMP 代理程式頁面上每個欄位的詳細資訊、請參閱link:configuring-snmp-agent.html["設定SNMP代理程式"]。您必須在頁面底部選取 * 儲存 * 、以提交您在每個標籤上所做的任何變更。

.步驟
. 選擇*設定* > *監控* > *SNMP 代理程式*。
+
此時將顯示 SNMP 代理程式頁面。

. 若要停用所有網格節點上的 SNMP 代理程式、請清除 * 啟用 SNMP* 核取方塊、然後選取 * 儲存 * 。
+
如果重新啟用 SNMP 代理程式、則會保留任何先前的 SNMP 組態設定。

. 您也可以選擇更新基本組態區段中的資訊：
+
.. 視需要更新 * 系統聯絡人 * 和 * 系統位置 * 。
.. 或者、選取或清除 * 啟用 SNMP 代理程式通知 * 核取方塊、以控制 StorageGRID SNMP 代理程式是否傳送陷阱和通知通知。
+
清除此核取方塊時、 SNMP 代理程式支援唯讀 MIB 存取、但不會傳送 SNMP 通知。

.. 或者、選取或清除 * 啟用驗證設陷 * 核取方塊、以控制 StorageGRID SNMP 代理程式是否在收到驗證不當的傳輸協定訊息時傳送驗證設陷。


. 如果您使用 SNMPv1 或 SNMPv2c 、請選擇性地在社群字串區段中更新或新增 * 唯讀社群 * 。
. 若要更新設陷目的地、請選取「其他組態」區段中的「設陷目的地」索引標籤。
+
使用此索引標籤可定義 StorageGRID 設陷或通知通知的一或多個目的地。當您啟用 SNMP 代理程式並選取 * 儲存 * 時、 StorageGRID 會在觸發警示時、將通知傳送至每個定義的目的地。也會針對支援的MIB-II實體（例如ifdown和coldStart）傳送標準通知。

+
如需輸入內容的詳細資訊，請參閱link:../monitor/configuring-snmp-agent.html#create-trap-destinations["建立設陷目的地"]。

+
** 您也可以更新或移除預設的設陷社群。
+
如果您移除預設的陷阱社群、則必須先確定任何現有的陷阱目的地都使用自訂社群字串。

** 若要新增設陷目的地、請選取 * 建立 * 。
** 若要編輯設陷目的地、請選取選項按鈕、然後選取 * 編輯 * 。
** 若要移除設陷目的地、請選取選項按鈕、然後選取 * 移除 * 。
** 若要提交變更、請選取頁面底部的 * 儲存 * 。


. 若要更新代理程式位址、請選取「其他組態」區段中的「代理程式位址」標籤。
+
使用此索引標籤可指定一或多個「聆聽地址」。這些是 SNMP 代理程式可以接收查詢的 StorageGRID 位址。

+
如需輸入內容的詳細資訊，請參閱link:../monitor/configuring-snmp-agent.html#create-agent-addresses["建立代理程式位址"]。

+
** 若要新增代理程式位址、請選取 * 建立 * 。
** 若要編輯值機員地址、請選取選項按鈕、然後選取 * 編輯 * 。
** 若要移除代理程式位址、請選取選項按鈕、然後選取 * 移除 * 。
** 若要提交變更、請選取頁面底部的 * 儲存 * 。


. 若要更新 USM 使用者、請選取「其他組態」區段中的 USM 使用者標籤。
+
使用此索引標籤可定義有權查詢mib或接收陷阱和通知的USM使用者。

+
如需輸入內容的詳細資訊，請參閱link:../monitor/configuring-snmp-agent.html#create-usm-users["建立 USM 使用者"]。

+
** 若要新增 USM 使用者、請選取 * 建立 * 。
** 若要編輯 USM 使用者、請選取選項按鈕、然後選取 * 編輯 * 。
+
無法變更現有 USM 使用者的使用者名稱。如果您需要變更使用者名稱、則必須移除使用者並建立新的使用者名稱。

+

NOTE: 如果您新增或移除使用者的授權引擎 ID 、且目前已為目的地選取該使用者、則必須編輯或移除目的地。否則、當您儲存SNMP代理程式組態時、就會發生驗證錯誤。

** 若要移除 USM 使用者、請選取選項按鈕、然後選取 * 移除 * 。
+

NOTE: 如果您移除的使用者目前已選取作為設陷目的地、您必須編輯或移除目的地。否則、當您儲存SNMP代理程式組態時、就會發生驗證錯誤。

** 若要提交變更、請選取頁面底部的 * 儲存 * 。


. 更新 SNMP 代理程式組態後、請選取 * 儲存 * 。

