---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: 在解除委任儲存節點之前、請考慮是否可以改為複製節點。然後、如果您決定取消委任節點、請檢閱 StorageGRID 在取消委任程序期間如何管理物件和中繼資料。 
---
= 解除委任儲存節點的考量事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在解除委任儲存節點之前、請考慮是否可以改為複製節點。然後、如果您決定取消委任節點、請檢閱 StorageGRID 在取消委任程序期間如何管理物件和中繼資料。



== 何時要複製節點而非將其停用

如果您想要以較新或較大的應用裝置來取代較舊的應用裝置儲存節點、請考慮複製應用裝置節點、而不要在擴充中新增新應用裝置、然後將舊應用裝置汰換。

設備節點複製功能可讓您在同一個 StorageGRID 站台上、使用相容的應用裝置輕鬆更換現有的應用裝置節點。複製程序會將所有資料傳輸到新應用裝置、將新應用裝置放置在服務中、並將舊應用裝置保留在預先安裝狀態。

如果需要：

* 請更換已達到使用壽命的產品。
* 升級現有節點、充分利用改良的應用裝置技術。
* 增加網格儲存容量、而不需變更StorageGRID 您的一套系統中的儲存節點數量。
* 改善儲存效率、例如變更 RAID 模式。


如需詳細資訊、請參閱 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["應用裝置節點複製"^]。



== 連線儲存節點的考量事項

檢閱解除委任連線儲存節點的考量事項。

* 在單一取消委任節點程序中、您不應取消委任超過10個儲存節點。
* 系統必須始終包含足夠的儲存節點來滿足操作要求，包括link:understanding-adc-service-quorum.html["ADC 仲裁"]和活動的link:reviewing-ilm-policy-and-storage-configuration.html["ILM原則"]。若要滿足此限制、您可能需要在擴充作業中新增儲存節點、才能取消委任現有的儲存節點。
+
在包含僅軟體中繼資料節點的網格中取消委任儲存節點時、請務必謹慎。如果您取消委任所有設定為儲存物件和中繼資料的節點、則儲存物件的能力會從網格中移除。如需僅中繼資料儲存節點的詳細資訊、請參閱link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存節點類型"]。

* 移除儲存節點時、會透過網路傳輸大量的物件資料。雖然這些傳輸不應影響正常的系統作業、但它們可能會影響 StorageGRID 系統所使用的網路頻寬總量。
* 與儲存節點解除委任相關的工作優先順序低於正常系統作業相關的工作。這表示汰換不會干擾StorageGRID 正常的非功能性系統作業、也不需要排定系統閒置一段時間。由於汰換是在背景執行、因此很難預估完成程序所需的時間。一般而言、當系統處於靜止狀態時、或一次只移除一個儲存節點時、汰換作業會更快完成。
* 取消委任儲存節點可能需要數天或數週的時間。請據此規劃此程序。雖然取消委任程序的設計不會影響系統作業、但它可能會限制其他程序。一般而言、移除網格節點之前、您應該先執行任何計畫性的系統升級或擴充。
* 如果您需要在移除儲存節點時執行其他維護程序、則可以在其他程序完成後繼續執行link:pausing-and-resuming-decommission-process-for-storage-nodes.html["暫停取消委任程序"]。
+

NOTE: 只有在達到ILM評估或銷毀編碼資料解除委任階段時、才會啟用*暫停*按鈕；不過、ILM評估（資料移轉）仍會在背景中繼續執行。

* 當取消委任工作正在執行時、您無法在任何網格節點上執行資料修復作業。
* 在解除委任儲存節點時、您不應對 ILM 原則進行任何變更。
* 若要永久且安全地移除資料、您必須在解除委任程序完成後、清除儲存節點的磁碟機。




== 中斷連線儲存節點的考量事項

檢閱解除委任中斷連線的儲存節點的考量事項。

* 除非您確定無法將中斷連線的節點上線或還原、否則請勿將其取消委任。
+

CAUTION: 如果您認為可能可以從節點恢復物件資料、請勿執行此程序。請聯絡技術支援部門、以判斷是否可以恢復節點。

* 當您取消委任中斷連線的儲存節點時、 StorageGRID 會使用來自其他儲存節點的資料來重建中斷連線節點上的物件資料和中繼資料。
* 如果您取消委任多個中斷連線的儲存節點、可能會導致資料遺失。如果沒有足夠的物件複本、銷毀編碼的片段或物件中繼資料可供使用、系統可能無法重建資料。當在網格中停用儲存節點時、若只有軟體型中繼資料節點、則停用所有設定為同時儲存物件和中繼資料的節點、會從網格中移除所有物件儲存。如需僅中繼資料儲存節點的詳細資訊、請參閱link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存節點類型"]。
+

CAUTION: 如果您有多個無法恢復的已中斷連線儲存節點、請聯絡技術支援部門、以決定最佳的行動方針。

* 當您取消委任已中斷連線的儲存節點時、StorageGRID 在解除委任程序結束時、即可開始執行資料修復工作。這些工作會嘗試重建儲存在中斷連線節點上的物件資料和中繼資料。
* 當您取消委任已中斷連線的儲存節點時、取消委任程序相對較快完成。不過、資料修復工作可能需要數天或數週的時間才能執行、而且不會受到取消委任程序的監控。您必須手動監控這些工作、並視需要重新啟動。請參閱。 link:checking-data-repair-jobs.html["檢查資料修復工作"]
* 如果您取消委任包含物件唯一複本的已中斷連線儲存節點、該物件將會遺失。只有在目前連線的儲存節點上至少有一個複寫複本或有足夠的銷毀編碼片段存在時、資料修復工作才能重建及還原物件。

