---
permalink: maintain/how-site-recovery-is-performed-by-technical-support.html 
sidebar: sidebar 
keywords: storagegrid, site recovery, technical support, tech support 
summary: 如果整個StorageGRID 站台故障或多個儲存節點故障、您必須聯絡技術支援部門。技術支援人員將評估您的情況、擬定恢復計畫、然後以符合業務目標的方式還原故障節點或站台、最佳化恢復時間、並防止不必要的資料遺失。 
---
= 技術支援如何恢復網站
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果整個StorageGRID 站台故障或多個儲存節點故障、您必須聯絡技術支援部門。技術支援人員將評估您的情況、擬定恢復計畫、然後以符合業務目標的方式還原故障節點或站台、最佳化恢復時間、並防止不必要的資料遺失。


CAUTION: 站台恢復只能由技術支援執行。

支援各種故障的支援能力強、您可以自行成功執行許多恢復與維護程序。StorageGRID不過、很難建立簡單、通用的站台還原程序、因為詳細步驟取決於您特定情況的因素。例如：

* *您的業務目標*：StorageGRID 在完全失去一個景點之後、您應該評估如何最有效地達成您的業務目標。例如、您要就地重建遺失的站台嗎？您想要在StorageGRID 新位置更換遺失的景點嗎？每位客戶的情況都不同、您的恢復計畫必須針對您的優先事項而設計。
* * 故障的確切性質 * ：在開始站台恢復之前、請確定故障站台上的任何節點是否完整、或任何儲存節點是否包含可恢復的物件。如果您重新建置包含有效資料的節點或儲存磁碟區、可能會發生不必要的資料遺失。
* * 主動式 ILM 原則 * ：網格中物件複本的數量、類型和位置是由主動式 ILM 原則所控制。ILM 原則的細節可能會影響可恢復資料的數量、以及還原所需的特定技術。
+

CAUTION: 如果站台只包含物件的複本、且站台遺失、則物件會遺失。

* * 貯體（或容器）一致性 * ：套用至貯體（或容器）的一致性、會影響 StorageGRID 在告知用戶端物件擷取成功之前、是否將物件中繼資料完全複寫至所有節點和站台。如果一致性值允許最終一致性、則部分物件中繼資料可能會在站台故障中遺失。這可能會影響可恢復資料的數量、並可能影響恢復程序的詳細資料。
* * 最近變更的記錄 * ：還原程序的詳細資料可能會受到影響、因為故障發生時是否有任何維護程序正在進行、或是您的 ILM 原則是否有任何最近的變更。技術支援人員必須先評估網格的最新歷史記錄及目前狀況、然後才能開始站台恢復。



CAUTION: 站台恢復只能由技術支援執行。

這是技術支援用於恢復故障站台的程序總覽：

. 技術支援：
+
.. 詳細評估故障。
.. 與您一起檢視您的業務目標。
.. 針對您的情況、擬定專屬的恢復計畫。


. 如果主管理節點發生故障、技術支援會將其恢復。
. 技術支援會依照以下概述、恢復所有儲存節點：
+
.. 視需要更換儲存節點硬體或虛擬機器。
.. 將物件中繼資料還原至故障站台。
.. 將物件資料還原至恢復的儲存節點。
+

CAUTION: 如果使用單一故障儲存節點的恢復程序、就會發生資料遺失。

+

NOTE: 當整個站台發生故障時、技術支援會使用特殊命令來成功還原物件和物件中繼資料。



. 技術支援可恢復其他故障節點。
+
物件中繼資料和資料恢復後、技術支援會使用標準程序來恢復故障的閘道節點或非主要管理節點。



.相關資訊
link:site-decommissioning.html["站台取消委任"]
