---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 您必須瞭StorageGRID 解套用修補程式時、您的整個系統將會受到什麼影響。 
---
= 套用熱修復程式時、系統受到的影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須瞭StorageGRID 解套用修補程式時、您的整個系統將會受到什麼影響。



== StorageGRID Hotfix 不中斷營運

StorageGRID 系統可在整個 Hotfix 程序中、從用戶端應用程式擷取及擷取資料。如果您將所有類型相同的節點都核准給 Hotfix （例如儲存節點）、則節點會一次關閉一個節點、因此當某種類型的所有網格節點或所有網格節點都無法使用時、就不會有任何時間。

為了確保持續可用、請確保 ILM 原則包含指定儲存每個物件多個複本的規則。您也必須確定所有外部 S3 用戶端都已設定為傳送要求至下列其中一項：

* 高可用度（ HA ）群組虛擬 IP 位址
* 高可用度協力廠商負載平衡器
* 每個用戶端有多個閘道節點
* 每個用戶端有多個儲存節點




== 用戶端應用程式可能會遭遇短期中斷

整個修復程序過程中、支援從用戶端應用程式擷取和擷取資料；不過、如果修復程式需要重新啟動這些節點上的服務、則個別閘道節點或儲存節點的用戶端連線可能會暫時中斷。StorageGRID在修復程序完成後、連線功能將會恢復、而服務會在個別節點上恢復。

如果連線中斷時間很短、您可能需要排定停機時間、才能套用修補程式。您可以使用選擇性核准來排程特定節點的更新時間。


NOTE: 您可以使用多個閘道和高可用度（HA）群組、在修復程序程序期間提供自動容錯移轉功能。請參閱的說明link:../admin/configure-high-availability-group.html["設定高可用度群組"]。



== 可能會觸發警示和SNMP通知

當服務重新啟動時、StorageGRID 以及當作業系統以混合版本環境運作時（某些執行舊版的網格節點、而其他節點則已升級至更新版本）、可能會觸發警示和SNMP通知。一般而言、這些警示和通知會在修復程式完成時清除。



== 組態變更受到限制

將修補程式套用StorageGRID 至

* 在將 Hotfix 套用至所有節點之前、請勿變更任何網格組態（例如、指定網格網路子網路或核准擱置的網格節點）。
* 在將 Hotfix 套用至所有節點之前、請勿更新 ILM 組態。

