---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: '您可以從命令列使用指令碼來監控修復工作的狀態 `repair-data`。' 
---
= 監控修復資料工作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從命令列使用指令碼來監控修復工作的狀態 `repair-data`。

這些工作包括您手動起始的工作、或是 StorageGRID 在取消委任程序中自動起始的工作。


NOTE: 如果您正在執行 Volume 還原工作、請改為執行link:../maintain/restoring-volume.html["在 Grid Manager 中監控這些工作的進度並檢視其歷史記錄"]。

根據您是使用 * 複寫資料 * 、 * 刪除編碼（ EC ）資料 * 或兩者來監控工作的狀態 `repair-data`。

[role="tabbed-block"]
====
.複寫資料
--
* 若要取得複寫修復的估計完成百分比、請將選項新增 `show-replicated-repair-status`至 repair 資料命令。
+
`repair-data show-replicated-repair-status`

* 若要判斷維修是否完成：
+
.. 選擇*節點*>*要修復的儲存節點*>* ILM *。
.. 檢閱「評估」區段中的屬性。當修復完成時、「*等待-全部*」屬性會指出0個物件。


* 若要更詳細地監控維修：
+
.. 選擇*節點*。
.. 選擇*網格名稱_*>* ILM *。
.. 將游標放在 ILM 佇列圖形上方，即可查看 *Scan Rate （ objects/sec ） * 屬性的值，這是網格中物件的掃描速率，以及 ILM 的佇列速率。
.. 在「 ILM 佇列」區段中，查看下列屬性：
+
*** * 掃描週期 - 預估 * ：完成所有物件完整 ILM 掃描的預估時間。
+
完整掃描並不保證 ILM 已套用至所有物件。

*** * 嘗試的修復 * ：已嘗試複寫資料的物件修復作業總數。每次儲存節點嘗試修復高風險物件時、此計數就會遞增。如果網格忙碌、高風險的ILM修復會優先處理。
+
如果在修復之後複寫失敗、相同的物件修復可能會再次遞增。+ 當您監控儲存節點磁碟區恢復的進度時，這些屬性可能很有用。如果嘗試的維修次數已停止增加，且已完成完整掃描，則可能已完成修復。



.. 或者，提交和 `storagegrid_ilm_repairs_attempted`的 Prometheus 查詢 `storagegrid_ilm_scan_period_estimated_minutes`。




--
.銷毀編碼（ EC ）資料
--
若要監控銷毀編碼資料的修復、然後重試任何可能失敗的要求：

. 判斷銷毀編碼資料修復的狀態：
+
** 選取* support*>* Tools *>* Metrics *以檢視目前工作的預估完成時間和完成百分比。然後在Grafana區段中選取* EC Overview *。請參閱* Grid EC工作預估完成時間*和* Grid EC工作百分比已完成*儀表板。
** 使用此命令查看特定作業的狀態 `repair-data`：
+
`repair-data show-ec-repair-status --repair-id repair ID`

** 使用此命令列出所有修復：
+
`repair-data show-ec-repair-status`

+
輸出會列出所有先前和目前正在執行的修復的資訊、包括 `repair ID`。



. 如果輸出顯示修復作業失敗、請使用 `--repair-id`選項重試修復。
+
此命令會使用修復ID 6949309319275667690、重試失敗的節點修復：

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
此命令會使用修復ID 6949309319275667690重試失敗的Volume修復：

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====