---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: 您可以將 ADC 服務移至同一站台上的另一個儲存節點。 
---
= 移動 ADC 服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將 ADC 服務移至同一站台上的另一個儲存節點。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有 link:admin-group-permissions.html["維護或根存取權限"]。
* 來源節點包含 ADC 服務。
* 目標節點不包含 ADC 服務。
* 目標節點可以是純中繼資料節點，也可以是結合的（中繼資料和物件資料）節點。
* 來源節點和目標節點位於同一個站台上。


.關於這項工作
當您想要：

* 取消委任包含 ADC 服務的儲存節點
* 將 ADC 節點轉換為僅限資料的節點
* 新增節點以執行與 ADC 相關的工作


當您想要取消委任儲存節點或link:../maintain/convert-to-data-only-node.html["將儲存節點轉換為純資料節點"]時，首先您可能需要使用移動 ADC 程序。您必須確保link:../maintain/understanding-adc-service-quorum.html["ADC 仲裁仍保持不變"]。

此程序會將 ADC ， IDNT ， ACCT 和 RSM 服務從同一個儲存節點移至同一個站台上的另一個儲存節點。RSM 和 ACCT 服務需視 ADC 服務而定，因此會在 ADC 服務移動時自動移動。

.步驟
. 記錄來源和目標節點的節點 ID 。
+
在 Grid Management API 中，來源節點 ID 稱為 `sourceNodeId`。目標節點 ID 稱為 `targetNodeId`。

. 從 Grid Manager 頂端選取說明圖示、然後選取 * API 文件 * 。
. 選取 * 前往私有 API 文件 * 。
. 選取 `POST /private/move-adc/start`作業。如需詳細資訊、請參閱 link:../admin/using-grid-management-api.html#issue-api-requests["發出API要求"] 。
+
在程序期間，每個節點都會重新開機。

. 您可以使用 `GET /private/move-adc`監控程序。如果發生錯誤，請選取 `POST /private/move-adc/retry`以重試程序。
. link:../maintain/downloading-recovery-package.html["下載恢復套件"]完成此程序後。

