---
permalink: maintain/rebooting-grid-node-from-grid-manager.html 
sidebar: sidebar 
keywords: reboot grid node, tasks tab 
summary: 您可以從「節點」頁面上的「工作」索引標籤、重新啟動個別的網格節點。 
---
= 從「工作」標籤重新啟動網格節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「節點」頁面上的「工作」索引標籤、重新啟動個別的網格節點。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:../admin/admin-group-permissions.html["維護或根存取權限"]。
* 您有資源配置通關密碼。
* 如果您要重新啟動主要管理節點或任何儲存節點、您已檢閱下列考量事項：
+
** 當您重新啟動主要管理節點時、瀏覽器會暫時失去對 Grid Manager 的存取權。
** 如果您在指定站台重新啟動兩個以上的儲存節點、則在重新開機期間可能無法存取某些物件。如果任何 ILM 規則使用 *Dual Commit * 擷取選項（或規則指定 *Balanced * 、無法立即建立所有必要複本）、就可能發生此問題。在這種情況下、 StorageGRID 會將新擷取的物件提交至同一個站台上的兩個儲存節點、並於稍後評估 ILM 。
** 為了確保您可以在儲存節點重新開機時存取所有物件、請先停止在站台上擷取物件約一小時、再重新啟動節點。




.關於這項工作
StorageGRID 重新開機網格節點時、會在節點上發出 `reboot`命令、導致節點關機並重新啟動。所有服務都會自動重新啟動。

* 重新啟動 VMware 節點會重新啟動虛擬機器。
* 重新啟動 Linux 節點會重新啟動容器。
* 重新啟動 StorageGRID 應用裝置節點會重新啟動運算控制器。



TIP: 如果您需要重新啟動多個節點、可以使用link:../maintain/rolling-reboot-procedure.html["循環重新開機程序"]。

.步驟
. 選擇*節點*。
. 選取您要重新開機的網格節點。
. 選取*工作*索引標籤。
. 選擇*重新開機*。
+
隨即顯示確認對話方塊。如果您要重新開機主管理節點、確認對話方塊會提醒您、當服務停止時、瀏覽器與Grid Manager的連線將會暫時中斷。

. 輸入資源配置通關密碼、然後選取*確定*。
. 等待節點重新開機。
+
服務可能需要一些時間才能關機。

+
當節點重新開機時、節點頁面上的節點會出現灰色（管理性關閉）圖示。當所有服務重新啟動、且節點已成功連線至網格時、「節點」頁面應會顯示正常狀態（節點名稱左側沒有圖示）、表示沒有作用中警示、且節點已連線至網格。


