---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: 您可以視需要變更整個 Grid Manager 、每個站台及每個節點的顯示名稱。您可以在需要時安全地更新顯示名稱。 
---
= 請使用重新命名程序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以視需要變更整個網格管理程式、每個網站及每個節點的顯示名稱。您可以在需要時安全地更新顯示名稱。



== 什麼是重新命名程序？

一開始安裝 StorageGRID 時、您會為網格、每個站台及每個節點指定一個名稱。這些初始名稱稱為 _ 系統名稱 _ 、這些名稱最初會顯示在整個 StorageGRID 中。

內部 StorageGRID 作業需要系統名稱、因此無法變更。不過、您可以使用重新命名程序、為網格、每個站台及每個節點定義新的 _ 顯示名稱 _ 。這些顯示名稱會出現在不同的 StorageGRID 位置、而非（或在某些情況下、除了）基礎系統名稱。

使用重新命名程序來修正打字錯誤、實作不同的命名慣例、或表示站台及其所有節點已重新定位。與系統名稱不同、顯示名稱可在必要時更新、而不會影響 StorageGRID 作業。



== 系統名稱和顯示名稱出現在何處？

下表摘要說明系統名稱和顯示名稱在 StorageGRID 使用者介面和 StorageGRID 檔案中的顯示位置。

[cols="1a,1a,3a"]
|===
| 位置 | 系統名稱 | 顯示名稱 


 a| 
Grid Manager 頁面
 a| 
除非項目已重新命名、否則會顯示
 a| 
如果項目已重新命名、則會在下列位置顯示、而非顯示系統名稱：

* 儀表板
* 節點頁面
* 高可用度群組、負載平衡器端點、 VLAN 介面、金鑰管理伺服器、網格密碼、 和防火牆控制
* 警示
* 儲存資源池定義
* 物件中繼資料查詢頁面
* 與維護程序相關的頁面、包括升級、 Hotfix 、 SANtricity OS 升級、取消委任、 擴充、恢復和物件存在檢查
* 支援頁面（記錄和診斷）
* 單一登入頁面、位於管理節點詳細資料表格中的管理節點主機名稱旁




 a| 
*節點* > 節點的 *概覽* 選項卡
 a| 
永遠顯示
 a| 
只有在項目重新命名時才會顯示



 a| 
* 節點健全狀況 * API
 a| 
一律歸還
 a| 
只有在項目重新命名時才傳回



 a| 
使用 SSH 存取節點時提示
 a| 
除非項目已重新命名、否則會顯示為主要名稱：

`admin@SYSTEM-NAME: ~ $`

項目重新命名時會包含在括弧中：

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
項目重新命名時顯示為主要名稱：

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`復原包中的文件
 a| 
顯示為 `Server Name`
 a| 
顯示為 `Display Name`



 a| 
`/etc/hosts`所有節點上的檔案

例如：

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
一律顯示在第二欄中
 a| 
項目重新命名時、會顯示在第四欄



 a| 
`topology-display-names.json`，包含在 AutoSupport 資料中
 a| 
不含
 a| 
除非項目已重新命名、否則為空白；否則、會將網格、站台和節點 ID 對應至其顯示名稱。

|===


== 顯示名稱需求

使用此程序之前、請先檢閱顯示名稱的需求。



=== 節點的顯示名稱

節點的顯示名稱必須遵循下列規則：

* 在 StorageGRID 系統中必須是唯一的。
* 不得與 StorageGRID 系統中任何其他項目的系統名稱相同。
* 必須包含至少 1 個字元、不得超過 32 個字元。
* 可以包含數字、連字號（ - ）、大寫和小寫字母。
* 可以以字母或數字開頭或結尾、但不能以連字號開頭或結尾。
* 不能全部都是數字。
* 不區分大小寫。例如 `DC1-ADM`、和 `dc1-adm`被視為重複項目。


您可以使用先前由不同節點使用的顯示名稱來重新命名節點、只要重新命名不會產生重複的顯示名稱或系統名稱即可。



=== 顯示網格和網站的名稱

網格和網站的顯示名稱遵循相同的規則、但這些例外情況除外：

* 可以包含空格。
* 可以包含以下特殊字元： `= - _ : , . @ !`
* 可以以特殊字元開始和結束、包括連字號。
* 可以是所有數字或特殊字元。




== 顯示名稱最佳實務做法

如果您打算重新命名多個項目、請在使用此程序之前記錄一般的命名方案。請準備一套系統、確保名稱獨一無二、一致且易於理解、一目瞭然。

您可以使用任何符合組織需求的命名慣例。請考慮以下基本建議、說明應包含哪些內容：

* * 站台指標 * ：如果您有多個站台、請在每個節點名稱中新增站台代碼。
* * 節點類型 * ：節點名稱通常表示節點的類型。您可以使用、 `adm`和 `gw`（儲存節點、管理節點和閘道節點）等縮寫 `s`。
* * 節點編號 * ：如果站台包含多種特定類型的節點、請在每個節點的名稱中新增唯一編號。


請三思、再將特定詳細資料新增至可能隨著時間而改變的名稱。例如、請勿在節點名稱中包含 IP 位址、因為這些位址可以變更。同樣地、如果您移動設備或升級硬體、機架位置或設備型號也可能會有所變更。



=== 顯示名稱範例

假設您的 StorageGRID 系統有三個資料中心、每個資料中心都有不同類型的節點。您的顯示名稱可能與以下名稱一樣簡單：

* * 網格 * ： `StorageGRID Deployment`
* * 第一站 * ： `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* * 第二站 * ： `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* * 第三網站 * ： `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



