---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: 在恢復儲存節點的故障系統磁碟機之前、請先檢閱網格節點恢復的一般警告和注意事項、以及下列特定警告。 
---
= 儲存節點系統磁碟機恢復的警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在恢復儲存節點的故障系統磁碟機之前、請先檢閱一般link:warnings-and-considerations-for-grid-node-recovery.html["網格節點恢復的警告和注意事項"]和下列特定警告。

儲存節點有一個包含物件元資料的 Cassandra 資料庫。如果出現以下情況，則可能需要重建 Cassandra 資料庫：

* 儲存磁碟區發生故障並已復原。
* 系統磁碟機和一或多個儲存磁碟區故障並恢復。


當 Cassandra 重建時，系統使用來自其他儲存節點的資訊。如果 Cassandra 最近重建，Cassandra 資料可能在整個網格中尚不一致。如果太多儲存節點處於離線狀態：

* 某些 Cassandra 資料可能無法使用。
* 可能會發生資料遺失。



CAUTION: 如果多個儲存節點發生故障（或離線），請聯絡技術支援。不要執行以下恢復程序。可能會發生資料遺失。有關詳細信息，請參閱link:how-site-recovery-is-performed-by-technical-support.html["技術支援如何恢復網站"] 。


CAUTION: 如果此儲存節點處於唯讀維護模式、以允許另一個儲存節點擷取故障儲存磁碟區的物件、請先在儲存節點上恢復故障儲存磁碟區的磁碟區、然後再恢復此故障儲存節點。請參閱的說明link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["從系統磁碟機完好無損的儲存磁碟區故障中恢復"]。


CAUTION: 如果ILM規則設定為僅儲存一個複寫複本、且複本存在於故障的儲存磁碟區、您將無法恢復物件。
