---
permalink: maintain/starting-software-installation-on-services-appliance-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, services appliance, start software installation 
summary: 若要在服務應用裝置上安裝閘道節點或管理節點、請使用設備隨附的 StorageGRID 應用裝置安裝程式。 
---
= 在服務設備上啟動 StorageGRID 軟體安裝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在服務應用裝置上安裝閘道節點或管理節點、請使用設備隨附的 StorageGRID 應用裝置安裝程式。

.開始之前
* 此應用裝置安裝在機架中、連接至您的網路、並已開啟電源。
* 網路連結和 IP 位址是使用 StorageGRID 應用裝置安裝程式為應用裝置設定。
* 如果您要安裝 Gateway Node 或非主要 Admin Node，您需要知道以下任一 Admin Node 的 IP 位址：
+
** StorageGRID 網格的主要管理節點
** 如果存在非主要管理節點且該節點正用於恢復節點，則使用該非主要管理節點。


* 如果您使用非主要管理節點恢復節點（包括主要管理節點），則可以指定該管理節點的 IP 位址。
* StorageGRID 應用裝置安裝程式 IP 組態頁面上列出的所有網格網路子網路、都是在主要管理節點的網格網路子網路清單中定義。
+
請參閱。 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["硬體安裝快速入門"^]

* 您使用的是link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您已將其中一個 IP 位址指派給應用裝置。您可以使用管理網路、網格網路或用戶端網路的IP位址。
* 如果您安裝的是主管理節點、您可以StorageGRID 取得此版本的Ubuntu或DEBIANY安裝檔案。
+

NOTE: 製造過程中、服務應用裝置會預先載入最新版本StorageGRID 的支援軟體。如果預先載入的軟體版本與 StorageGRID 部署中使用的版本相符、則不需要安裝檔案。



.關於這項工作
若要在服務應用裝置上安裝 StorageGRID 軟體：

* 對於主要管理節點，您需要指定節點名稱，然後上傳適當的軟體套件（如有需要）。如果您要還原主要管理節點，且您的網格中存在非主要管理節點，您可以選擇使用非主要管理節點還原節點並指定該管理節點的 IP 位址，或使用您目前的組態安裝或還原節點。
* 對於非主要管理節點或閘道節點、您可以指定或確認主要管理節點的IP位址和節點名稱。
* 您可以開始安裝、並在磁碟區已設定且已安裝軟體時等待。
* 在整個過程中、安裝會暫停一段時間。若要繼續安裝、您必須登入Grid Manager、並將擱置節點設定為故障節點的替代節點。
* 設定節點之後、應用裝置安裝程序便會完成、應用裝置也會重新開機。


.步驟
. 開啟瀏覽器、然後輸入服務應用裝置的其中一個 IP 位址。
+
`https://_Controller_IP_:8443`

+
畫面會出現「the不再安裝StorageGRID 程式」首頁。

. 若要安裝主管理節點：
+
.. 在「此節點」區段的「*節點類型*」中、選取「*主要管理員*」。
.. 在「節點名稱」欄位中，輸入與要恢復的節點相同的名稱，然後選擇「儲存」。
.. 請從「安裝模式」部分提供的兩種模式中選擇適當的模式。您可以選擇「Install a node or recover this node using current configuration」方法，也可以選擇「Recover this node using a non-primary Admin Node」方法。
+
[role="tabbed-block"]
====
.目前組態方法
--
使用目前組態安裝節點或恢復此節點。

... 在「安裝」部分，檢查「目前狀態」下所列的軟體版本。如果準備安裝的軟體版本正確，請跳至 <<installation_section_step,安裝步驟>>。
... 如果需要上傳其他版本的軟體，請在「進階」選單下選擇「上傳 StorageGRID 軟體」。此時將顯示「上傳 StorageGRID 軟體」頁面。
... 選擇 *Browse* 以上傳 StorageGRID 軟體的 *Software package* 和 *Checksum file*。選取檔案後，將自動上傳。
... 選擇 *Home* 以返回 StorageGRID Appliance Installer 首頁。


--
.非主要管理節點方法
--
使用非主要管理節點恢復此節點。

... 在非主要管理節點 IP 欄位中，輸入要用於恢復的非主要管理節點的網格網路 IP 位址，然後選擇 *Save*。
... 如果準備安裝的軟體版本正確，請跳至<<installation_section_step,安裝步驟>>。


--
====


. 若要安裝網關節點或非主管理節點：
+
.. 在「此節點」區段的「*節點類型*」中、根據您要還原的節點類型、選取「*閘道*」或「*非主要管理員*」。
.. 在「節點名稱」欄位中，輸入與要恢復的節點相同的名稱，然後選擇「儲存」。
.. 在「主要管理節點連線」區段中、判斷是否需要指定主要管理節點的IP位址。
+
如果主管理節點或至少有一個已設定ADD_IP的其他網格節點存在於同一個子網路中、則可使用此解決方案安裝程式自動探索此IP位址。StorageGRID

.. 如果未顯示此 IP 位址或您需要變更它，請指定位址：


+
[cols="1a,2a"]
|===
| 選項 | 說明 


 a| 
手動輸入IP
 a| 
.. 清除 * 啟用管理節點探索 * 核取方塊。
.. 手動輸入IP位址。
.. 選擇*保存*。
.. 等待新 IP 位址的連線狀態變成「就緒」。




 a| 
自動探索所有連線的主要管理節點
 a| 
.. 選中 * 啓用管理節點發現 * 複選框。
.. 從探索到的IP位址清單中、選取要部署此服務應用裝置之網格的主要管理節點。
.. 選擇*保存*。
.. 等待新 IP 位址的連線狀態變成「就緒」。


|===
. [[installation_section_dete]]在「安裝」區段中、確認目前狀態為「準備好開始安裝節點名稱」、且已啟用「*開始安裝*」按鈕。
+
如果未啟用「*開始安裝*」按鈕，您可能需要變更網路設定或連接埠設定。請參閱您設備的維護說明。

. 從 StorageGRID 應用裝置安裝程式首頁，選取 * 開始安裝 *。
+
目前狀態變更為「Installation is in progress」，並顯示監控安裝頁面。

+

NOTE: 如果需要手動存取 Monitor 安裝頁面，請從功能表列中選擇 *Monitor installation*。


