---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: 從「取消委任網站」精靈的步驟 3 \ （修訂 ILM 原則 \ ）、您可以判斷該網站是否由任何 ILM 原則參照。 
---
= 步驟 3 ：修改 ILM 原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從「取消委任網站」精靈的步驟 3 （修訂 ILM 原則）開始、您可以判斷該網站是否由任何 ILM 原則參照。

.開始之前
您對如何操作有很好的瞭解link:../ilm/index.html["使用 ILM 管理物件"]。您熟悉建立儲存資源池和 ILM 規則、以及模擬和啟動 ILM 原則。

.關於這項工作
如果任何原則（作用中或非作用中）中有任何 ILM 規則參照該站台、 StorageGRID 就無法取消委任該站台。

如果任何 ILM 原則參照您要取消委任的網站、您必須移除或編輯這些原則、使其符合下列要求：

* 完全保護所有物件資料。
* 請勿參閱您即將停用的網站。
* 請勿使用參照網站的儲存資源池、或使用「所有網站」選項。
* 請勿使用參照網站的銷毀編碼設定檔。
* 請勿使用 StorageGRID 11.6 或更早版本安裝的「複製 2 份複本」規則。



CAUTION: 切勿建立單一複本ILM規則來因應網站移除作業。ILM規則只會在任何時間段建立一個複寫複本、使資料有永久遺失的風險。如果只有一個物件複寫複本存在、則當儲存節點故障或發生重大錯誤時、該物件就會遺失。在升級等維護程序期間、您也會暫時失去物件的存取權。


TIP: 如果您正在執行 _Connected 站台取消委任 _ 、則必須考慮 StorageGRID 應如何管理您要移除之站台上目前的物件資料。根據您的資料保護需求、新規則可以將現有的物件資料移至不同的站台、也可以刪除不再需要的任何額外物件複本。

如果您需要協助設計新原則、請聯絡技術支援部門。

.步驟
. 從步驟 3 （修訂 ILM 原則）中、判斷是否有任何 ILM 原則參照到您選取要取消委任的站台。
. 如果未列出策略，請選擇 *Next* 轉至link:step-4-remove-ilm-references.html["步驟4：移除ILM參考"]。
. 如果列出一或多個 _activity_ ILM 原則、請複製每個現有原則、或建立不參照所停用站台的新原則：
+
.. 在「原則名稱」欄中選取原則的連結。
+
原則的 ILM 原則詳細資料頁面會顯示在新的瀏覽器索引標籤中。「取消委任網站」頁面仍會在「其他」索引標籤上保持開啟狀態。

.. 視需要遵循以下準則和指示：
+
*** 使用 ILM 規則：
+
**** link:../ilm/creating-storage-pool.html["建立一個或多個儲存資源池"]這並不代表網站。
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["編輯或取代規則"]這是指網站。
+

NOTE: 請勿選取 * 製作 2 份複本 * 規則、因為該規則使用 * 所有儲存節點 * 儲存池、這是不允許的。



*** 使用 ILM 原則：
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["複製現有的 ILM 原則"] 或 link:../ilm/creating-ilm-policy.html["建立新的 ILM 原則"]。
**** 確保預設規則和其他規則不會參照網站。
+

CAUTION: 您必須確認ILM規則的順序正確。當原則啟動時、新物件和現有物件會依照列出的順序進行評估、從上方開始。





.. 擷取測試物件並模擬原則、以確保套用正確的規則。
+

CAUTION: ILM原則中的錯誤可能導致無法恢復的資料遺失。在啟動原則之前、請仔細檢閱並模擬原則、以確認其運作正常。

+

CAUTION: 當您啟動新的ILM原則時StorageGRID 、利用它來管理所有物件、包括現有物件和新擷取的物件。在啟動新的ILM原則之前、請先檢閱現有複寫和銷毀編碼物件放置位置的任何變更。變更現有物件的位置、可能會在評估和實作新放置位置時、導致暫時性資源問題。

.. 啟動新原則、並確保舊原則現在處於非作用中狀態。
+
如果您想要啟動多個原則，link:../ilm/creating-ilm-policy.html#activate-ilm-policy["請依照步驟建立 ILM 原則標籤"]。

+
如果您正在執行連線站台取消委任、StorageGRID 則只要啟動新的ILM原則、即可立即從所選站台移除物件資料。移動或刪除所有物件複本可能需要數週的時間。雖然您可以在站台上仍存在物件資料的情況下安全地啟動站台取消委任、但如果您允許在開始實際取消委任程序之前、從站台移除資料、則取消委任程序將會更快完成、並減少中斷和效能影響 （在精靈的步驟5中選取*開始取消委任*）。



. 針對每個 _inactive 原則、請先選取前述步驟所述的每個原則連結、以進行編輯或移除。
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["編輯原則"]因此它並不代表要停用的網站。
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["移除原則"]。


. 當您完成 ILM 規則和原則的變更時、步驟 3 （修訂 ILM 原則）中不應再列出原則。選擇*下一步*。
+
此時會出現步驟4（移除ILM參考）。


