---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: 如果在功能版本之間偵測到並解決軟體問題、您可能需要將修補程式套用StorageGRID 至您的無法修復的系統。 
---
= 修復程序StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在功能版本之間偵測到並解決軟體問題、您可能需要將修補程式套用StorageGRID 至您的無法修復的系統。

不含功能或修補程式版本、而可在其中進行軟體變更。StorageGRID未來版本也會包含相同的變更。此外、每個修補程式版本都包含功能或修補程式版本中所有先前修復程式的彙總。



== 套用修補程式的考量

當另一個維護程序正在執行時、您無法套用 StorageGRID Hotfix 。例如、在執行取消委任、擴充或還原程序時、您無法套用 Hotfix 。


NOTE: 如果節點或站台停用程序暫停、您可以安全地套用修補程式。此外、StorageGRID 您也可以在更新程序的最後階段套用修補程式。如需詳細資訊、請參閱升級StorageGRID 版的介紹。

在Grid Manager中上傳此修補程式之後、此修復程式會自動套用至主要管理節點。然後、您可以核准將此修補程式應用到StorageGRID 您的靜止系統的其餘節點。

如果某個熱修復無法套用至一或多個節點、則故障原因會出現在熱修復程序進度表的詳細資料欄中。您必須解決導致故障的任何問題、然後重試整個程序。先前成功應用此修復程序的節點將跳過後續應用程序。您可以安全地重試修復程序程序程序、重試次數不限、直到所有節點都更新完畢為止。必須在所有網格節點上成功安裝此修補程式、才能完成應用程式。

雖然網格節點是以新的修補程式版本更新、但是修復程式中的實際變更可能只會影響特定類型節點上的特定服務。例如、熱修復程式可能只會影響儲存節點上的LDR服務。



== 如何套用修補程式來進行還原和擴充

將修補程式套用至網格後、主管理節點會自動將相同的修補程式版本安裝至任何透過還原作業還原或新增至擴充中的節點。

不過、如果您需要恢復主管理節點、則必須手動安裝正確StorageGRID 的版本資訊、然後套用此修復程式。主管理節點的最終StorageGRID 版更新版本必須與網格中其他節點的版本相符。

下列範例說明如何在還原主要管理節點時套用修補程式：

. 假設網格使用StorageGRID 最新的修補程式執行的是更新版本的S11。_A.B_。「網格版本」為 11._A.B.y_ 。
. 主管理節點故障。
. 您可以使用StorageGRID 下列功能重新部署主管理節點：ES11._A.B_、然後執行恢復程序。
+

NOTE: 如需符合網格版本、您可以在部署節點時使用次要版本、而不需要先部署主要版本。

. 然後將修補程式11._A.B.y_套用至主要管理節點。


如需更多資訊、請參閱 link:configuring-replacement-primary-admin-node.html["設定替換的主要管理節點"]。
