---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: ADC 仲裁機制可確保每個站點至少保留一定數量的管理網域控制站 （ADC） 服務可用。StorageGRID 在必要時會自動在退役期間移動 ADC 服務。 
---
= 什麼是 StorageGRID ADC 仲裁？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ADC 仲裁機制可確保每個站點至少保留一定數量的管理網域控制站 （ADC） 服務可用。StorageGRID 在必要時會自動在退役期間移動 ADC 服務。

在某些儲存節點上找到的 ADC 服務可維護網格拓撲資訊、並為網格提供組態服務。這個支援系統要求每個站台及任何時間都能達到特定的ADC服務量。StorageGRID

如果移除節點會導致不再符合 ADC 仲裁、則無法取消委任儲存節點。為了在汰換期間滿足 ADC 仲裁、每個站台至少必須有三個儲存節點、才能使用 ADC 服務。如果站台有三個以上的儲存節點搭配 ADC 服務、則在汰換之後、這些節點中的大多數必須保持可用： `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: 在包含僅軟體中繼資料節點的網格中取消委任儲存節點時、請務必謹慎。如果您取消委任所有設定為儲存物件和中繼資料的節點、則儲存物件的能力會從網格中移除。如需僅中繼資料儲存節點的詳細資訊、請參閱link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存節點類型"]。

例如、假設某個站台目前包含六個具有 ADC 服務的儲存節點、而您想要取消委任三個儲存節點。由於必須達到ADC仲裁要求、您必須完成下列兩個取消委任程序：

* 在第一次取消委任程序中、您必須確保具有 ADC 服務的四個儲存節點仍然可用 `((0.5 * 6) + 1)`：。這表示您一開始只能取消委任兩個儲存節點。
* 在第二個退役過程中，您可以刪除第三個儲存節點，因為 ADC 仲裁現在只需要三個 ADC 服務保持可用： `((0.5 * 4) + 1)` 。


當您退役一個提供 ADC 服務的儲存節點時，如果退役會導致網站的 ADC 數量低於法定數量，StorageGRID 會自動將 ADC 服務遷移到同一網站上的另一個儲存節點。自動遷移的前提是網格中的所有節點都已連線，且同一網站上存在可接收該服務的非 ADC 儲存節點。退役程序會確保每個網站至少保留三個 ADC 儲存節點。例如，如果您在一個網站上退役四個或六個 ADC 節點，假設同一網站上存在可用的非 ADC 節點，則程序結束後仍會保留三個 ADC 儲存節點。

如果 ADC 服務無法自動遷移，您可以link:move-adc-service.html["手動移動 ADC 服務"]將其遷移到同一網站上的另一個儲存節點，或link:../expand/index.html["在擴充中新增一個新的儲存節點"]並指定該節點需要 ADC 服務。然後，您可以退役現有儲存節點，而不會影響仲裁。
