---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 如果停用後仍有太少的管理網域控制站（ ADA\ ）服務、您可能無法取消委任某個站台上的特定儲存節點。 
---
= 什麼是 ADC 仲裁？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果停用後仍有太少的管理網域控制站（ ADC ）服務、您可能無法取消委任某個站台上的特定儲存節點。

在某些儲存節點上找到的 ADC 服務可維護網格拓撲資訊、並為網格提供組態服務。這個支援系統要求每個站台及任何時間都能達到特定的ADC服務量。StorageGRID

如果移除節點會導致不再符合 ADC 仲裁、則無法取消委任儲存節點。為了在汰換期間滿足 ADC 仲裁、每個站台至少必須有三個儲存節點、才能使用 ADC 服務。如果站台有三個以上的儲存節點搭配 ADC 服務、則在汰換之後、這些節點中的大多數必須保持可用： `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: 在包含僅軟體中繼資料節點的網格中取消委任儲存節點時、請務必謹慎。如果您取消委任所有設定為儲存物件和中繼資料的節點、則儲存物件的能力會從網格中移除。如需僅中繼資料儲存節點的詳細資訊、請參閱link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存節點類型"]。

例如、假設某個站台目前包含六個具有 ADC 服務的儲存節點、而您想要取消委任三個儲存節點。由於必須達到ADC仲裁要求、您必須完成下列兩個取消委任程序：

* 在第一次取消委任程序中、您必須確保具有 ADC 服務的四個儲存節點仍然可用 `((0.5 * 6) + 1)`：。這表示您一開始只能取消委任兩個儲存節點。
* 在第二個取消委任程序中，您可以移除第三個儲存節點，因為現在 ADC 仲裁只需要三個 ADC 服務才能繼續使用 `((0.5 * 4) + 1)`：。


如果您需要取消委任儲存節點，您可以繼續滿足 ADC 仲裁需求，方法是link:../upgrade/changes-to-grid-management-api.html#new-private-endpoints-for-move-adc["將 ADC 服務移至相同站台上的另一個儲存節點"]在中新增儲存節點，並指定該節點link:../expand/index.html["擴充"]應該擁有 ADC 服務。然後，您可以取消委任現有的儲存節點，而不會影響仲裁。
