---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: 如果網格節點故障、您必須盡快恢復。開始之前、您必須檢閱所有節點還原的警告和考量事項。 
---
= 網格節點還原的警告與考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果網格節點故障、您必須盡快恢復。開始之前、您必須檢閱所有節點還原的警告和考量事項。


CAUTION: 由多個節點共同運作的分散式系統。StorageGRID請勿使用磁碟快照來還原網格節點。請參閱每種節點類型的恢復與維護程序。


NOTE: 如果整個StorageGRID站點發生故障，請聯絡技術支援。技術支援將與您合作制定並執行網站復原計劃，以最大限度地恢復資料量並滿足您的業務目標。請參閱link:how-site-recovery-is-performed-by-technical-support.html["技術支援如何恢復網站"] 。

儘快恢復故障網格節點的原因包括：

* 故障的網格節點可減少系統和物件資料的備援、讓您在其他節點故障時容易遭受永久性資料遺失的風險。
* 故障的網格節點可能會影響日常作業的效率。
* 故障的網格節點可能會降低監控系統作業的能力。
* 如果有嚴格的ILM規則、故障的網格節點可能會導致500個內部伺服器錯誤。
* 如果網格節點未立即恢復、恢復時間可能會增加。例如、可能需要先清除佇列、才能完成恢復。


請務必遵循所還原之特定類型網格節點的還原程序。主要或非主要管理節點、閘道節點、應用裝置節點和儲存節點的恢復程序各不相同。



== 恢復網格節點的先決條件

恢復網格節點時、會假設下列所有情況：

* 故障的實體或虛擬硬體已被更換及設定。
* 替換應用裝置上的 StorageGRID 應用裝置安裝程式版本與 StorageGRID 系統的軟體版本相符、如所述 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["驗StorageGRID 證並升級版本的應用程式"^]。
* 如果您正在還原主管理節點以外的網格節點，則正在復原的網格節點與管理復原程序的管理節點之間存在連線。
* 如果要恢復設備儲存節點，則必須在設備安裝期間指定與原始設備相同的儲存類型（組合、僅元資料或僅資料）。如果指定不同的儲存類型，復原將失敗，並且需要使用指定的正確儲存類型重新安裝裝置。




== 如果託管多個網格節點的伺服器故障、則節點恢復順序

如果託管多個網格節點的伺服器發生故障，您可以按任意順序還原節點。但是，如果發生故障的伺服器託管主管理節點，則必須先還原該節點。



== 恢復節點的IP位址

請勿嘗試使用目前指派給任何其他節點的 IP 位址來恢復節點。部署新節點時、請使用故障節點的目前IP位址或未使用的IP位址。

如果您使用新的IP位址來部署新節點、然後恢復該節點、新的IP位址將繼續用於恢復的節點。如果您想要回復到原始IP位址、請在恢復完成後使用變更IP工具。
