---
permalink: primer/nodes-and-services.html 
sidebar: sidebar 
keywords: services, grid nodes, primary admin, storage, gateway 
summary: 整個系統的基本建置區塊StorageGRID 是網格節點。節點包含服務、這些是軟體模組、可為網格節點提供一組功能。 
---
= 網格節點和服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
整個系統的基本建置區塊StorageGRID 是網格節點。節點包含服務、這些是軟體模組、可為網格節點提供一組功能。



== 網格節點類型

此系統使用四種網格節點：StorageGRID

管理節點:: 提供系統組態、監控及記錄等管理服務。當您登入Grid Manager時、即連線至管理節點。每個網格都必須有一個主要管理節點、而且可能有額外的非主要管理節點以供備援。您可以連線至任何管理節點、每個管理節點都會顯示StorageGRID 類似的畫面、顯示有關該系統的資訊。不過、維護程序必須使用主要管理節點來執行。
+
--
管理節點也可用於平衡 S3 用戶端流量的負載。

請參閱 link:what-admin-node-is.html["什麼是管理節點？"]

--
儲存節點:: 管理及儲存物件資料和中繼資料。StorageGRID 系統中的每個站台必須至少有三個儲存節點。
+
--
請參閱 link:what-storage-node-is.html["什麼是儲存節點？"]

--
閘道節點（選用）:: 提供負載平衡介面、讓用戶端應用程式可用來連線至 StorageGRID 。負載平衡器可將用戶端無縫導向至最佳儲存節點、使節點或甚至整個站台的故障透明化。
+
--
請參閱 link:what-gateway-node-is.html["什麼是閘道節點？"]

--




== 硬體和軟體節點

StorageGRID 節點可部署為 StorageGRID 應用裝置節點、或部署為軟體型節點。



=== 應用裝置節點StorageGRID

用作作業系統的各種硬體應用。StorageGRID StorageGRID有些應用裝置可做為儲存節點。其他應用裝置可做為管理節點或閘道節點。您可以將應用裝置節點與軟體型節點結合、或部署完全工程設計的全應用裝置網格、而這些網格不需依賴外部Hypervisor、儲存設備或運算硬體。

請參閱下列內容、瞭解可用的應用裝置：

* https://docs.netapp.com/us-en/storagegrid-appliances/["StorageGRID 應用裝置文件"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]




=== 軟體型節點

軟體型網格節點可部署為 VMware 虛擬機器、或部署於 Linux 主機上的容器引擎內。

* VMware vSphere 中的虛擬機器（ VM ）：請參閱link:../vmware/index.html["在 VMware 上安裝 StorageGRID"]。
* 在 Red Hat Enterprise Linux 的 Container 引擎中：請參閱link:../rhel/index.html["在 Red Hat Enterprise Linux 上安裝 StorageGRID"]。
* 在 Ubuntu 或 Debian 上的 Container 引擎中：請參閱link:../ubuntu/index.html["在 Ubuntu 或 Debian 上安裝 StorageGRID"]。


使用 https://imt.netapp.com/matrix/#welcome["NetApp互通性對照表工具IMT （不含）"^]確定支援的版本。

在新的軟體型儲存節點初始安裝期間link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存中繼資料"]、您可以指定它僅用於。



== 支援服務StorageGRID

以下是StorageGRID 完整的支援服務清單。

[cols="2a,3a,2a"]
|===
| 服務 | 說明 | 位置 


 a| 
帳戶服務轉發器
 a| 
提供介面、讓負載平衡器服務查詢遠端主機上的帳戶服務、並通知負載平衡器端點組態變更負載平衡器服務。
 a| 
管理節點和閘道節點上的負載平衡器服務



 a| 
ADC （管理網域控制器）
 a| 
維護拓撲資訊、提供驗證服務、並回應來自LMR和CMN服務的查詢。
 a| 
每個站台至少有三個儲存節點包含 ADC 服務



 a| 
AMS （稽核管理系統）
 a| 
監控所有已稽核的系統事件和交易、並將其記錄到文字記錄檔中。
 a| 
管理節點



 a| 
Cassandra Reaper
 a| 
自動修復物件中繼資料。
 a| 
儲存節點



 a| 
區塊服務
 a| 
管理銷毀編碼的資料和同位元檢查片段。
 a| 
儲存節點



 a| 
CMN （組態管理節點）
 a| 
管理全系統的組態和網格工作。每個網格都有一項 CMN 服務。
 a| 
主要管理節點



 a| 
DDS （分散式資料儲存區）
 a| 
與Cassandra資料庫介面、以管理物件中繼資料。
 a| 
儲存節點



 a| 
DMV （ Data Mover ）
 a| 
將資料移至雲端端點。
 a| 
儲存節點



 a| 
動態 IP （ dynip ）
 a| 
監控網格、以取得動態IP變更並更新本機組態。
 a| 
所有節點



 a| 
Grafana
 a| 
用於Grid Manager中的度量視覺化。
 a| 
管理節點



 a| 
高可用度
 a| 
在「高可用度群組」頁面上設定的節點上管理高可用度虛擬 IP 。此服務也稱為「保留服務」。
 a| 
管理和閘道節點



 a| 
身分識別（idnt）
 a| 
聯盟LDAP和Active Directory的使用者身分識別。
 a| 
使用 ADC 服務的儲存節點



 a| 
Lambda 仲裁者
 a| 
管理S3 Select SelectObjectContent要求。
 a| 
所有節點



 a| 
負載平衡器（ Nginx)
 a| 
提供從用戶端到儲存節點的 S3 流量負載平衡。您可以透過「負載平衡器端點組態」頁面來設定負載平衡器服務。這項服務也稱為「Ngine-GW」服務。
 a| 
管理和閘道節點



 a| 
LDR （本機配送路由器）
 a| 
管理網格內內容的儲存與傳輸。
 a| 
儲存節點



 a| 
MISCd 資訊服務控制精靈
 a| 
提供一個介面、用於查詢及管理其他節點上的服務、以及管理節點上的環境組態、例如查詢其他節點上執行的服務狀態。
 a| 
所有節點



 a| 
恩靈思
 a| 
做為各種網格服務（例如Prometheus和動態IP）的驗證與安全通訊機制、可透過HTTPS API與其他節點上的服務進行對話。
 a| 
所有節點



 a| 
恩靈思- GW
 a| 
為負載平衡器服務提供電源。
 a| 
管理和閘道節點



 a| 
NMS （網路管理系統）
 a| 
為透過Grid Manager顯示的監控、報告和組態選項提供電源。
 a| 
管理節點



 a| 
持續性
 a| 
管理根磁碟上需要在重新開機後持續存在的檔案。
 a| 
所有節點



 a| 
Prometheus
 a| 
從所有節點上的服務收集時間序列指標。
 a| 
管理節點



 a| 
RSM （複寫狀態機器）
 a| 
確保平台服務要求會傳送至各自的端點。
 a| 
使用 ADC 服務的儲存節點



 a| 
SSM （伺服器狀態監控器）
 a| 
監控硬體狀況、並向NMS服務報告。
 a| 
每個網格節點上都有一個執行個體



 a| 
追蹤收集器
 a| 
執行追蹤收集、以收集資訊供技術支援人員使用。追蹤收集器服務使用開放原始碼 Jaeger 軟體。
 a| 
管理節點

|===