---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: 儲存節點可管理及儲存物件資料和中繼資料。儲存節點包括在磁碟上儲存、移動、驗證及擷取物件資料和中繼資料所需的服務和程序。 
---
= 什麼是儲存節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存節點可管理及儲存物件資料和中繼資料。儲存節點包括在磁碟上儲存、移動、驗證及擷取物件資料和中繼資料所需的服務和程序。

StorageGRID 系統中的每個站台必須至少有三個儲存節點。



== 儲存節點類型

在安裝期間、您可以選取要安裝的儲存節點類型。這些類型適用於軟體型儲存節點、以及支援此功能的應用裝置型儲存節點：

* 結合資料與中繼資料儲存節點
* 純中繼資料儲存節點
* 純資料儲存節點


在下列情況下、您可以選取「儲存節點」類型：

* 初次安裝儲存節點時
* 在 StorageGRID 系統擴充期間新增儲存節點時



NOTE: 儲存節點安裝完成後、您無法變更類型。

資料與中繼資料儲存節點（組合）:: 根據預設、所有新的儲存節點都會同時儲存物件資料和中繼資料。這種類型的儲存節點稱為 _ 組合 _ 儲存節點。
純中繼資料儲存節點:: 如果您的網格儲存了大量的小物件、則只使用儲存節點來儲存中繼資料是很有意義的。安裝專用中繼資料容量可在大量小型物件所需的空間與這些物件的中繼資料所需空間之間取得更好的平衡。此外、在高效能應用裝置上託管的純中繼資料儲存節點也能提升效能。


安裝純中繼資料節點時、網格也必須包含資料儲存所需的最少節點數：

* 對於單一站台網格、請至少設定兩個組合或純資料儲存節點。
* 對於多站台網格、請至少設定一個組合儲存節點或僅限資料儲存節點（每個站台）。



NOTE: 雖然純中繼資料儲存節點包含且可處理 S3 用戶端要求、但 <<ldr-service,LDR 服務>>StorageGRID 效能可能不會提高。

純資料儲存節點:: 如果您的儲存節點具有不同的效能特性、則只使用儲存節點來處理資料可能是有意義的。例如、若要提高效能、您可以使用僅限資料的大容量旋轉磁碟儲存節點、以及僅限中繼資料的高效能儲存節點。


安裝純資料節點時、網格必須包含下列項目：

* 每個網格至少兩個組合或僅限資料的儲存節點
* 每個站台至少有一個組合儲存節點或僅限資料儲存節點 _
* 每個站台至少有三個組合儲存節點或純中繼資料儲存節點




== 儲存節點的主要服務

下表顯示儲存節點的主要服務、但此表並未列出所有節點服務。


NOTE: 有些服務（例如、ADC服務和RSM服務）通常只存在於每個站台的三個儲存節點上。

[cols="1a,3a"]
|===
| 服務 | 按鍵功能 


 a| 
帳戶（帳戶）
 a| 
管理租戶帳戶。



 a| 
管理網域控制器（ADC）
 a| 
維護拓撲和整個網格的組態。

* 附註 * ：純資料儲存節點不提供 ADC 服務。

.詳細資料
[%collapsible]
====
管理網域控制器（ADC）服務會驗證網格節點及其彼此的連線。ADC 服務至少託管在一個站台的三個儲存節點上。

ADC服務負責維護拓撲資訊、包括服務的位置和可用度。當網格節點需要來自另一個網格節點的資訊、或是由另一個網格節點執行的動作時、它會聯絡某個ADC服務、以尋找處理其要求的最佳網格節點。此外、 ADC 服務會保留 StorageGRID 部署組態套件的複本、讓任何網格節點都能擷取目前的組態資訊。

為了方便分散式和分散式作業、每個ADC服務都會將憑證、組態套件、服務和拓撲的相關資訊、與StorageGRID 其他的子系統中的ADC服務進行同步。

一般而言、所有網格節點都會維持至少一項ADC服務的連線。如此可確保網格節點永遠存取最新資訊。當網格節點連線時、它們會快取其他網格節點的憑證、即使 ADC 服務無法使用、系統仍能繼續使用已知網格節點運作。新的網格節點只能使用ADC服務建立連線。

每個網格節點的連線可讓ADC服務收集拓撲資訊。此網格節點資訊包括CPU負載、可用磁碟空間（如果有儲存設備）、支援的服務、以及網格節點的站台ID。其他服務則透過拓撲查詢、要求ADC服務提供拓撲資訊。ADC服務會回應每個查詢、並提供StorageGRID 從該系統接收到的最新資訊。

====


 a| 
Cassandra
 a| 
儲存及保護物件中繼資料。

* 附註 * ：純資料儲存節點不會主控 Cassandra 服務。



 a| 
Cassandra Reaper
 a| 
自動修復物件中繼資料。

* 附註 * ：純資料儲存節點不提供 Cassandra Reaper 服務。



 a| 
區塊
 a| 
管理銷毀編碼的資料和同位元檢查片段。



 a| 
資料移轉（DMV）
 a| 
將資料移至雲端儲存資源池。



 a| 
分散式資料儲存區（DDS）
 a| 
監控物件中繼資料儲存。

.詳細資料
[%collapsible]
====
每個儲存節點都包含分散式資料儲存區（ DDS ）服務。此服務會與 Cassandra 資料庫進行介面、以對儲存在 StorageGRID 系統中的物件中繼資料執行背景工作。

DDS 服務會追蹤寫入 StorageGRID 系統的物件總數、以及透過每個系統支援介面（ S3 ）擷取的物件總數。

====


 a| 
身分識別（idnt）
 a| 
聯盟LDAP和Active Directory的使用者身分識別。



 a| 
[[ldR-service]] 本機發佈路由器（ LDR ）
 a| 
處理物件儲存傳輸協定要求、並管理磁碟上的物件資料。

.詳細資料
[%collapsible]
====
每個 _ 組合 _ 、 _ 僅資料 _ 和 _ 僅中繼資料 _ 儲存節點都包含本機發佈路由器（ LDR ）服務。此服務可處理內容傳輸功能、包括資料儲存、路由和要求處理。LDR 服務可處理資料傳輸負載和資料傳輸功能、以完成 StorageGRID 系統的大部分工作。

LDR服務負責下列工作：

* 查詢
* 資訊生命週期管理（ILM）活動
* 物件刪除
* 物件資料儲存
* 從另一個LDR服務（儲存節點）傳輸物件資料
* 資料儲存管理
* S3 傳輸協定介面


LDR 服務也會將每個 S3 物件對應至其唯一 UUID 。

物件存放區:: LDR服務的基礎資料儲存區分為固定數量的物件存放區（也稱為儲存磁碟區）。每個物件存放區都是個別的掛載點。
+
--
儲存節點中的物件會以介於0000到002F之間的十六進位數字來識別、這稱為Volume ID。空間會保留在第一個物件存放區（Volume 0）中、以供Cassandra資料庫中的物件中繼資料使用；該磁碟區上的任何剩餘空間都會用於物件資料。所有其他物件存放區僅用於物件資料、包括複寫複本和銷毀編碼的片段。

為了確保複寫複本的空間使用率、會根據可用的儲存空間、將特定物件的物件資料儲存至單一物件存放區。物件儲存區填滿容量時、其餘物件儲存區會繼續儲存物件、直到儲存節點上沒有空間為止。

--
中繼資料保護:: 將物件中繼資料儲存在Cassandra資料庫中、該資料庫與LDR服務介面。StorageGRID
+
--
為了確保備援並保護資料免於遺失、每個站台都會保留三份物件中繼資料複本。此複寫無法設定、而且會自動執行。如需詳細資訊、請參閱 link:../admin/managing-object-metadata-storage.html["管理物件中繼資料儲存"]。

--


====


 a| 
複寫狀態機器（RSM）
 a| 
確保 S3 平台服務要求會傳送至各自的端點。



 a| 
伺服器狀態監視器（SSM）
 a| 
監控作業系統和基礎硬體。

|===