---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: StorageGRID, admin nodes 
summary: 管理節點提供系統組態、監控及記錄等管理服務。管理節點也可用於平衡 S3 用戶端流量的負載。每個網格都必須有一個主要管理節點、而且可能有任意數量的非主要管理節點來提供備援。 
---
= 什麼是 StorageGRID 管理節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理節點提供系統組態、監控及記錄等管理服務。管理節點也可用於平衡 S3 用戶端流量的負載。每個網格都必須有一個主要管理節點、而且可能有任意數量的非主要管理節點來提供備援。



== 主要和非主要管理節點之間的差異

當您登入網格管理器或租戶管理器時，您正在連線到管理節點。您可以連接到任何管理節點，每個管理節點都會顯示StorageGRID系統的類似視圖。但是，主管理節點比非主管理節點提供更多功能。例如，大多數維護程序必須從主管理節點執行。

下表摘要說明主要和非主要管理節點的功能。

[cols="2a,1a,1a"]
|===
| 功能 | 主要管理節點 | 非主要管理節點 


 a| 
包括<<ams,AMS>>服務
 a| 
是的
 a| 
是的



 a| 
包括<<cmn,CMN>>服務
 a| 
是的
 a| 
否



 a| 
包括<<nms,NMS>>服務
 a| 
是的
 a| 
是的



 a| 
包括<<prometheus,Prometheus>>服務
 a| 
是的
 a| 
是的



 a| 
包括<<ssm,超棒>>服務
 a| 
是的
 a| 
是的



 a| 
包括<<load-balancer,負載平衡器>>和<<high-availability,高可用度>>服務
 a| 
是的
 a| 
是的



 a| 
支援<<mgmt-api,管理應用程式介面>>（ mgmt-API ）
 a| 
是的
 a| 
是的



 a| 
可用於所有網路相關的維護工作、例如 IP 位址變更和更新 NTP 伺服器
 a| 
是的
 a| 
否



 a| 
可以下載恢復包
 a| 
是的
 a| 
是的



 a| 
可在儲存節點擴充後執行 EC 重新平衡
 a| 
是的
 a| 
否



 a| 
可用於磁碟區還原程序
 a| 
是的
 a| 
是的



 a| 
可從一或多個節點收集記錄檔和系統資料
 a| 
是的
 a| 
是的



 a| 
可以恢復儲存、網關和非主管理節點
 a| 
是的
 a| 
是的



 a| 
可以恢復主管理節點
 a| 
是的
 a| 
否



 a| 
傳送警示通知、 AutoSupport 套件和 SNMP 設陷並通知
 a| 
是的。用作<<preferred-sender,偏好的寄件者>>。
 a| 
是的。做為待命傳送者。

|===


== [[preferred-sender]] 偏好的寄件者管理節點

如果您的 StorageGRID 部署包含多個管理節點、則主要管理節點是警示通知、 AutoSupport 套件和 SNMP 設陷及通知的慣用寄件者。

在正常系統操作下，只有首選發送者發送通知。但是，所有其他管理節點都會監控首選發送者。如果偵測到問題，其他管理節點將充當備用發送者。

在以下情況下可能會發送多條通知：

* 如果管理節點彼此「中斷」、偏好的寄件者和待命寄件者都會嘗試傳送通知、而且可能會收到多份通知複本。
* 如果備用發送器偵測到首選發送器出現問題並開始發送通知，則首選發送器可能會重新獲得發送通知的能力。如果發生這種情況，可能會發送重複的通知。當備用發送器不再偵測到首選發送器上的錯誤時，它將停止發送通知。
+

NOTE: 測試 AutoSupport 套件時、所有管理節點都會傳送測試。測試警示通知時、您必須登入每個管理節點以驗證連線能力。





== 管理節點的主要服務

下表顯示管理節點的主要服務、但此表並未列出所有節點服務。

[cols="1a,2a"]
|===
| 服務 | 按鍵功能 


 a| 
[[AMS]] 稽核管理系統（ AMS ）
 a| 
追蹤系統活動和事件。



 a| 
[[CMN]] 組態管理節點（ CMN ）
 a| 
管理全系統組態。



 a| 
[[high-Availability ]] 高可用度
 a| 
管理管理節點和閘道節點群組的高可用度虛擬IP位址。

*附註：*此服務也可在閘道節點上找到。



 a| 
[[load-balancer]] 負載平衡器
 a| 
提供從用戶端到儲存節點的 S3 流量負載平衡。

*附註：*此服務也可在閘道節點上找到。



 a| 
[mgmt-API] 管理應用程式介面（ mgmt-API ）
 a| 
處理來自Grid Management API和租戶管理API的要求。



 a| 
[[NMS]] 網路管理系統（ NMS ）
 a| 
提供Grid Manager的功能。



 a| 
[[Prometheus]]Prometheus
 a| 
從所有節點上的服務收集和儲存時間序列度量。



 a| 
[[SIS]] 伺服器狀態監視器（ SSM ）
 a| 
監控作業系統和基礎硬體。

|===