---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: 閘道節點提供專用的負載平衡介面、 S3 用戶端應用程式可用來連線至 StorageGRID 。負載平衡可在多個儲存節點之間分配工作負載、以最大化速度和連線容量。閘道節點為選用項目。 
---
= 什麼是閘道節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
閘道節點提供專用的負載平衡介面、 S3 用戶端應用程式可用來連線至 StorageGRID 。負載平衡可在多個儲存節點之間分配工作負載、以最大化速度和連線容量。閘道節點為選用項目。

StorageGRID 負載平衡器服務會在所有管理節點和所有閘道節點上提供。它會對用戶端要求執行傳輸層安全性（TLS）終止、檢查要求、並建立新的安全連線至儲存節點。負載平衡器服務可無縫地將用戶端導向至最佳儲存節點、讓節點甚至整個站台的故障都能透明化。

您可以設定一或多個負載平衡器端點、以定義傳入和傳出用戶端要求用來存取 Gateway 和管理節點上負載平衡器服務的連接埠和網路傳輸協定（ HTTPS 或 HTTP ）。負載平衡器端點也會定義用戶端類型（ S3 ）、繫結模式、以及選擇性的允許或封鎖租戶清單。請參閱。 link:../admin/managing-load-balancing.html["負載平衡考量"]

視需要、您可以將多個閘道節點和管理節點的網路介面分組為高可用度（ HA ）群組。如果 HA 群組中的作用中介面失敗、備份介面就能管理用戶端應用程式工作負載。請參閱。 link:../admin/managing-high-availability-groups.html["管理高可用度（ HA ）群組"]



== 閘道節點的主要服務

下表顯示閘道節點的主要服務、但此表並未列出所有節點服務。

[cols="1a,2a"]
|===
| 服務 | 按鍵功能 


 a| 
高可用度
 a| 
管理管理節點和閘道節點群組的高可用度虛擬IP位址。

*附註：*此服務也可在管理節點上找到。



 a| 
負載平衡器
 a| 
提供從用戶端到儲存節點的 S3 流量第 7 層負載平衡。這是建議的負載平衡機制。

*附註：*此服務也可在管理節點上找到。



 a| 
伺服器狀態監視器（SSM）
 a| 
監控作業系統和基礎硬體。

|===