---
sidebar: sidebar 
permalink: expand/copying-audit-logs.html 
keywords: copy audit log, Admin Node expansion, 
summary: 當您透過擴充功能新增新的管理節點時，其 AMS 服務僅記錄其加入系統後發生的事件和操作。根據需要，您可以將稽核日誌從先前安裝的管理節點複製到新的擴充管理節點，以便它與StorageGRID系統的其餘部分同步。 
---
= 複製稽核記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您透過擴充功能新增新的管理節點時，其 AMS 服務僅記錄其加入系統後發生的事件和操作。根據需要，您可以將稽核日誌從先前安裝的管理節點複製到新的擴充管理節點，以便它與StorageGRID系統的其餘部分同步。

.開始之前
* 您已完成新增管理節點所需的擴充步驟。
* 您有 `Passwords.txt`檔案。


.關於這項工作
若要在新的管理節點上提供歷史稽核訊息、您必須手動將稽核記錄檔從現有的管理節點複製到擴充管理節點。

[NOTE]
====
預設情況下，審計資訊將發送到 `localaudit`登入每個節點。若要使用此流程，您必須已將管理節點配置為稽核目標，如下所示：

* 您將 *管理節點/本機節點* 配置為日誌目標。
* 您已將*管理節點和外部系統日誌伺服器*配置為日誌目標。


參考link:../monitor/configure-audit-messages.html["設定稽核訊息和外部 Syslog 伺服器"]了解詳情。

====
.步驟
. 登入主要管理節點：
+
.. 輸入下列命令： `ssh _admin@_primary_Admin_Node_IP_`
.. 輸入檔案中列出的密碼 `Passwords.txt`。
.. 輸入以下命令切換到 root ： `su -`
.. 輸入檔案中列出的密碼 `Passwords.txt`。
+
當您以 root 登入時、提示會從變更 `$`為 `#`。



. 停止 AMS 服務以防止其建立新檔案： `service ams stop`
. 瀏覽至稽核匯出目錄：
+
`cd /var/local/audit/export/`

. 重新命名來源 `audit.log`文件以確保它不會覆蓋您要將其複製到的擴充管理節點上的檔案：
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. 將所有稽核記錄檔複製到擴充管理節點上的目的地位置：
+
`scp -p * _IP_address_:/var/local/audit/export/`

. 如果系統提示您輸入的密碼 `/root/.ssh/id_rsa`、請輸入檔案中所列主要管理節點的 SSH 存取密碼 `Passwords.txt`。
. 還原原始 `audit.log`檔案：
+
`mv _new_name_.txt audit.log`

. 啟動AMS服務：
+
`service ams start`

. 從伺服器登出：
+
`exit`

. 登入擴充管理節點：
+
.. 輸入下列命令： `ssh admin@_expansion_Admin_Node_IP_`
.. 輸入檔案中列出的密碼 `Passwords.txt`。
.. 輸入以下命令切換到 root ： `su -`
.. 輸入檔案中列出的密碼 `Passwords.txt`。
+
當您以 root 登入時、提示會從變更 `$`為 `#`。



. 更新稽核記錄檔的使用者和群組設定：
+
`cd /var/local/audit/export/`

+
`chown ams-user:bycast *`

. 從伺服器登出：
+
`exit`


