---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure, StorageGRID 
summary: 新增儲存節點之後、您可以使用抹除編碼重新平衡程序、在現有和新的儲存節點之間重新分配銷毀編碼片段。 
---
= 在StorageGRID系統新增節點後，重新平衡糾刪碼資料。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新增儲存節點之後、您可以使用抹除編碼（ EC ）重新平衡程序、在現有和新的儲存節點之間重新分配銷毀編碼片段。

.開始之前
* 您已完成新增儲存節點的擴充步驟。
* 您已檢閱link:considerations-for-rebalancing-erasure-coded-data.html["重新平衡銷毀編碼資料的考量事項"]。
* 您了解複製的物件資料不會被此過程移動，且 EC 重新平衡過程不會移動複製的資料。但是，在確定將 EC 資料移至何處時，會考慮複製資料。
* 您有 `Passwords.txt`檔案。


.執行此程序時會發生什麼情況
開始程序之前、請注意下列事項：

* 如果一或多個磁碟區離線（未掛載）、或是它們在線上（掛載）但處於錯誤狀態、則 EC 重新平衡程序將不會啟動。
* EC重新平衡程序會暫時保留大量的儲存空間。儲存警示可能會觸發、但會在重新平衡完成時解決。如果保留空間不足、EC重新平衡程序將會失敗。無論程序失敗或成功、在EC重新平衡程序完成時、都會釋出儲存保留。
* 如果在 EC 重新平衡程序進行期間某個 Volume 離線、則重新平衡程序將會終止。已移動的任何資料片段都會保留在新位置、不會遺失任何資料。
+
您可以在所有磁碟區重新上線後重新執行程序。

* 當執行 EC 重新平衡程序時、 ILM 作業和 S3 用戶端作業的效能可能會受到影響。
+

NOTE: 如果需要超過 24 小時才能完成、則上傳物件（或物件零件）的 S3 API 作業可能會在 EC 重新平衡程序期間失敗。如果適用的 ILM 規則在擷取上使用平衡或嚴格的放置方式、則長時間的放置作業將會失敗。將報告以下錯誤： `500 Internal Server Error`。

* * 工作完成條件 * 。當下列任一情況成立時、 EC 重新平衡程序即視為完成：
+
** 它無法移動任何其他的銷毀編碼資料。
** 所有節點中的資料都在目標資料分割區的 5% 偏差內。
** 此程序已執行 30 天。




.步驟
. [[ree_object_storage ]檢閱您計畫重新平衡之站台的目前物件儲存詳細資料。
+
.. 選擇*節點*。
.. 選取站台的第一個儲存節點。
.. 選擇* Storage*（儲存設備）選項卡。
.. 將游標放在「已使用的儲存空間 - 物件資料」圖表上、即可查看儲存節點上目前的複寫資料量和銷毀編碼資料量。
.. 重複這些步驟、即可檢視站台上的其他儲存節點。


. 登入主要管理節點：
+
.. 輸入下列命令： `ssh admin@_primary_Admin_Node_IP_`
.. 輸入檔案中列出的密碼 `Passwords.txt`。
.. 輸入以下命令切換到 root ： `su -`
.. 輸入檔案中列出的密碼 `Passwords.txt`。
+
當您以 root 登入時、提示會從變更 `$`為 `#`。



. 開始以下程序：
+
' 重新平衡資料開始 - 站台 "_side-name_"

+
對於 "_side-name_" 、請指定您新增儲存節點或節點的第一個站台。請以引號括住 `site-name`。

+
EC重新平衡程序隨即開始、並傳回工作ID。

. 複製工作ID。
. [[view-status]] 監控 EC 重新平衡程序的狀態。
+
** 若要檢視單一EC重新平衡程序的狀態：
+
`rebalance-data status --job-id _job-id_`

+
對於 `_job-id_`，請指定在啓動過程時返回的 ID 。

** 若要檢視目前EC重新平衡程序的狀態、以及任何先前完成的程序：
+
`rebalance-data status`

+
[NOTE]
====
若要取得有關reBalance-data命令的說明：

`rebalance-data --help`

====


. 根據傳回的狀態執行其他步驟：
+
** 如果 `State`為 `In progress`、則 EC 重新平衡作業仍在執行中。您應該定期監控程序、直到程序完成為止。
+
前往節點頁面來評估網站中儲存節點的資料分佈。

+
EC 重新平衡工作被視為完成、當所有節點中的資料在目標資料分割區的 5% 偏差內時、就會停止。

** 如果為 `Success`、則 `State`可選擇性地<<review_object_storage,檢閱物件儲存>>查看網站的更新詳細資料。
+
在站台的儲存節點之間、銷毀編碼的資料現在應該更為平衡。

** 如果 `State`是 `Failure`：
+
... 確認站台上的所有儲存節點均已連線至網格。
... 檢查並解決可能影響這些儲存節點的任何警示。
... 重新啟動 EC 重新平衡程序：
+
`rebalance-data start –-job-id _job-id_`

... <<view-status,檢視狀態>>的新程序。如果 `State`仍在 `Failure`、請聯絡技術支援部門。




. 如果EC重新平衡程序產生過多負載（例如、擷取作業會受到影響）、請暫停程序。
+
`rebalance-data pause --job-id _job-id_`

. 如果您需要終止EC重新平衡程序（例如、您可以執行StorageGRID 更新版的程式碼）、請輸入下列命令：
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: 當您終止 EC 重新平衡程序時、任何已移動的資料片段都會保留在新的位置。資料不會移回原始位置。

. 如果您在多個站台使用銷毀編碼、請針對所有其他受影響的站台執行此程序。

