---
permalink: expand/updating-subnets-for-grid-network.html 
sidebar: sidebar 
keywords: expand, expansion, add subnets, Grid Network 
summary: 當您在擴充中新增網格節點或新站台時、可能需要更新或新增子網路至網格網路。 
---
= 更新Grid Network的子網路
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您在擴充中新增網格節點或新站台時、可能需要更新或新增子網路至網格網路。

此技術可維護網格網路（eth0）上用於在網格節點之間進行通訊的網路子網路清單。StorageGRID這些項目包括StorageGRID 您的系統所在站台用於Grid Network的子網路、以及透過Grid Network閘道存取的NTP、DNS、LDAP或其他外部伺服器所使用的任何子網路。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:../admin/admin-group-permissions.html["維護或根存取權限"]。
* 您有資源配置通關密碼。
* 您可以使用CIDR表示法來設定要設定的子網路位址。


.關於這項工作
如果任何新節點在先前未使用的子網路上有Grid Network IP位址、則在開始擴充之前、您必須先將新的子網路新增至Grid Network子網路清單。否則、您必須取消擴充、新增子網路、然後重新開始程序。

[NOTE]
====
請勿對任何節點的網格網路、管理網路或用戶端網路使用包含下列 IPv4 位址的子網路：

* 192,168,130,101
* 192,168,131,101
* 192,168,130,102
* 192,168,131,102
* 198.51.100.2
* 198.51.100.4


例如，不要對任何節點的網格網路、管理網路或客戶端網路使用下列子網路範圍：

* 192.168.130.0/24，因為此子網路範圍包含 IP 位址 192.168.130.101 和 192.168.130.102
* 192.168.131.0/24，因為此子網路範圍包含 IP 位址 192.168.131.101 和 192.168.131.102
* 198.51.100.0/24，因為此子網路範圍包含 IP 位址 198.51.100.2 和 198.51.100.4


====
.步驟
. 選擇*維護* > *網路* > *電網*。
. 選取 * 新增其他子網路 * 、以 CIDR 表示法新增子網路。
+
例如，輸入 `10.96.104.0/22`。

. 輸入資源配置通關密碼、然後選取*「Save*（儲存*）」。
. 等待更改套用完畢，然後下載新的恢復包。
+
.. 選擇*維護* > *系統* > *恢復包*。
.. 輸入*配置密碼*。
+

CAUTION: 復原包檔案必須是安全的，因為它包含可用於從StorageGRID系統取得資料的加密金鑰和密碼。它也用於恢復主管理節點。





您指定的子網路會自動設定為StorageGRID 適用於您的整個系統。
