---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: 物件可擷取的原因有多種、包括從用戶端應用程式讀取要求、複寫物件資料的背景驗證、ILM重新評估、以及在儲存節點還原期間還原物件資料。 
---
= 了解 StorageGRID 中遺失和缺少的物件資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
物件可擷取的原因有多種、包括從用戶端應用程式讀取要求、複寫物件資料的背景驗證、ILM重新評估、以及在儲存節點還原期間還原物件資料。

StorageGRID系統使用物件元資料中的位置資訊來決定從哪個位置擷取物件。如果在預期位置未找到該物件的副本，系統將嘗試從系統的其他位置擷取該物件的另一個副本，假設 ILM 策略包含製作該物件的兩個或更多個副本的規則。

如果檢索成功， StorageGRID系統將取代該物件的遺失副本。否則，將觸發*物件可能遺失*警報，如下所示：

* 對於複寫的複本、如果無法擷取另一個複本、則物件會視為遺失、並觸發警示。
* 如果是以刪除方式編碼的複本、如果無法從預期位置擷取複本、則偵測到毀損的複本（ ECOR ）屬性會在嘗試從其他位置擷取複本之前遞增一次。如果找不到其他複本、則會觸發警示。


您應該立即調查所有*物件可能遺失*警報，以確定遺失的根本原因，並確定物件是否仍存在於離線或目前不可用的儲存節點中。看link:../troubleshoot/investigating-potentially-lost-objects.html["調查可能遺失的物品"] 。遺失物品警報可能會因謹慎而被錯誤觸發。

如果沒有副本的物件資料遺失，則沒有復原解決方案。但是，你必須link:../troubleshoot/investigating-potentially-lost-objects.html#reset-lost-obj-count["重置可能遺失的物件計數器"]以防止已知遺失的物品掩蓋任何新的遺失物品。
