---
permalink: troubleshoot/troubleshooting-network-hardware-and-platform-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot network, how to troubleshoot hardware, how to troubleshoot platform 
summary: 您可以執行多項工作、以協助判斷StorageGRID 與故障有關的問題來源。 
---
= 疑難排解網路、硬體及平台問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行多項工作、以協助判斷StorageGRID 與故障有關的問題來源。



== 「 422 ：無法處理的實體」錯誤

錯誤 422 ：無法處理的實體可能會因不同原因而發生。請查看錯誤訊息、以判斷您的問題是由何種原因造成的。

如果您看到列出的錯誤訊息之一、請採取建議的行動。

[cols="2a,3a"]
|===
| 錯誤訊息 | 根本原因與修正行動 


 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration. Unable to
authenticate, please verify
your username and password:
LDAP Result Code 8 "Strong
Auth Required": 00002028:
LdapErr: DSID-0C090256,
comment: The server requires
binds to turn on integrity
checking if SSL\TLS are not
already active on the
connection, data 0, v3839
---- a| 
如果您在使用Windows Active Directory（AD）設定身分識別聯盟時、選取「傳輸層安全性（TLS）」*「不要使用TLS*」選項、就可能會出現此訊息。

不支援使用*「不使用TLS*」選項來搭配執行LDAP簽署的AD伺服器使用。您必須選取*使用ARTTLS*選項或*使用LDAPS*選項來使用TLS。



 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration.Unable to
begin TLS, verify your
certificate and TLS
configuration: LDAP Result
Code 200 "Network Error":
TLS handshake failed
    (EOF)
---- a| 
如果您嘗試使用不受支援的密碼、將傳輸層安全性（TLS）連線從StorageGRID 支援的內部系統、連接到用於識別聯盟或雲端儲存資源池的外部系統、則會出現此訊息。

檢查外部系統提供的密碼。系統必須使用其中一種link:../admin/supported-ciphers-for-outgoing-tls-connections.html["StorageGRID 支援的密碼"]進行外寄 TLS 連線、如管理 StorageGRID 的指示所示。

|===


== [[troubleshoot _MTU _alert]] Grid Network MTU 不相符警示

當Grid Network介面（eth0）的最大傳輸單位（MTU）設定在網格中的各個節點之間大幅不同時、就會觸發* Grid Network MTU mismis*警示。

.關於這項工作
MTU設定的差異可能代表部分（但並非全部）eth0網路已設定為使用巨型框架。MTU大小不相符的值大於1000、可能會導致網路效能問題。

.步驟
. 列出所有節點上eth0的MTU設定。
+
** 使用Grid Manager中提供的查詢。
** 瀏覽 `_primary Admin Node IP address_/metrics/graph`並輸入下列查詢： `node_network_mtu_bytes{device="eth0"}`


. https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["修改MTU設定"^]為確保所有節點上的網格網路介面（ eth0 ）相同、請視需要加以確認。
+
** 對於 Linux 和 VMware 型節點、請使用下列命令： `+/usr/sbin/change-ip.py [-h] [-n node] mtu network [network...]+`
+
* 範例 * ： `change-ip.py -n node 1500 grid admin`

+
* 注意 * ：在 Linux 型節點上、如果容器中網路所需的 MTU 值超過主機介面上已設定的值、則必須先將主機介面設定為具有所需的 MTU 值、然後使用 `change-ip.py`指令碼來變更容器中網路的 MTU 值。

+
請使用下列引數來修改Linux或VMware節點上的MTU。

+
[cols="1a,2a"]
|===
| 位置引數 | 說明 


 a| 
`mtu`
 a| 
要設定的MTU。必須介於1280至9216之間。



 a| 
`network`
 a| 
要套用MTU的網路。包括下列一種或多種網路類型：

*** 網格
*** 管理
*** 用戶端


|===
+
[cols="2a,2a"]
|===
| 選用引數 | 說明 


 a| 
`-h, – help`
 a| 
顯示說明訊息並結束。



 a| 
`-n node, --node node`
 a| 
節點。預設值為本機節點。

|===






== 節點網路接收框架錯誤警示

* 節點網路接收框架錯誤 * 警示可能是 StorageGRID 與網路硬體之間的連線問題所造成。解決基礎問題後、此警示會自行清除。

.關於這項工作
* 節點網路接收框架錯誤 * 警示可能是因為連線至 StorageGRID 的網路硬體發生下列問題：

* 需要轉送錯誤修正（FEC）、且不使用
* 交換器連接埠和NIC MTU不符
* 高連結錯誤率
* NIC環狀緩衝區溢位


.步驟
. 根據您的網路組態、請遵循疑難排解步驟、找出此警示的所有可能原因。
. 視錯誤原因而定、請執行下列步驟：
+
[role="tabbed-block"]
====
.FEC 不相符
--

NOTE: 這些步驟僅適用於 StorageGRID 應用裝置上 FEC 不相符所造成的 * 節點網路接收框架錯誤 * 警示。

.. 檢查連接StorageGRID 到您的產品的交換器連接埠的FEC狀態。
.. 檢查從設備到交換器的纜線實體完整性。
.. 如果您想要變更 FEC 設定以嘗試解決警示、請先確認在 StorageGRID 應用裝置安裝程式的「連結組態」頁面上、已將應用裝置設定為 * 自動 * 模式（請參閱應用裝置的說明：
+
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SG6160"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SGF6112"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/changing-link-configuration-of-sg6000-cn-controller.html["SG6000"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/changing-link-configuration-of-sg5800-controller.html["SG5800"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/changing-link-configuration-of-e5700sg-controller.html["SG5700"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/changing-link-configuration-of-sg110-and-sg1100-appliance.html["SG110 和 SG1100"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/changing-link-configuration-of-services-appliance.html["SG100 和 SG1000"^]


.. 變更交換器連接埠上的 FEC 設定。如果可能、該產品連接埠會調整其FEC設定。StorageGRID
+
您無法在 StorageGRID 應用裝置上設定 FEC 設定。相反地、應用裝置會嘗試探索並鏡射其所連接之交換器連接埠上的FEC設定。如果鏈路被迫達到25-GbE或100-GbE網路速度、交換器和NIC可能無法協調通用的FEC設定。如果沒有通用的 FEC 設定、網路就會恢復為「無 FEC 」模式。如果未啟用 FEC 、則連線更容易受到電子雜訊所造成的錯誤影響。

+

NOTE: StorageGRID 應用裝置支援 Firecode （ FC ）和 Reed Solomon （ RS ） FEC 、也不支援 FEC 。



--
.交換器連接埠和NIC MTU不符
--
如果警示是由交換器連接埠和 NIC MTU 不符所造成、請檢查節點上設定的 MTU 大小是否與交換器連接埠的 MTU 設定相同。

節點上設定的MTU大小可能小於節點所連接之交換器連接埠上的設定。如果 StorageGRID 節點收到大於其 MTU 的乙太網路訊框（此組態可能會發生）、則可能會回報 * 節點網路接收訊框錯誤 * 警示。如果您認為這是發生的情況、請根據StorageGRID 端點對端點MTU的目標或需求、變更交換器連接埠的MTU以符合該網路介面MTU、或變更StorageGRID 該網路介面的MTU以符合交換器連接埠。


NOTE: 為獲得最佳網路效能、所有節點都應在其Grid Network介面上設定類似的MTU值。如果個別節點上Grid Network的MTU設定有顯著差異、則會觸發* Grid Network MTU mismis*警示。所有網路類型的 MTU 值都不一定相同。如需詳細資訊、請參閱 <<troubleshoot_MTU_alert,疑難排解Grid Network MTU不相符警示>> 。


NOTE: 另請參閱 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["變更MTU設定"^]。

--
.高連結錯誤率
--
.. 啟用FEC（若尚未啟用）。
.. 確認您的網路纜線品質良好、而且未損壞或連接不當。
.. 如果纜線似乎沒有問題、請聯絡技術支援部門。
+

NOTE: 您可能會注意到、在電子雜訊較高的環境中、錯誤率很高。



--
.NIC環狀緩衝區溢位
--
如果錯誤是NIC環緩衝區溢位、請聯絡技術支援部門。

當無法及時處理網路事件時、當整個過程中出現過多的問題時、環狀緩衝區可能會發生溢位StorageGRID 。

--
====
. 監控問題、如果警示無法解決、請聯絡技術支援部門。




== 時間同步錯誤

您可能會在網格中看到時間同步的問題。

如果您遇到時間同步問題、請確認您已指定至少四個外部NTP來源、每個來源都提供階層3或更好的參考資料、而且所有外部NTP來源都正常運作、StorageGRID 且可由您的支援節點存取。


NOTE: 若link:../maintain/configuring-ntp-servers.html["指定外部 NTP 來源"]為正式作業層級的 StorageGRID 安裝、請勿在 Windows Server 2016 之前的 Windows 版本上使用 Windows 時間（ W32Time ）服務。舊版Windows上的時間服務不夠準確、Microsoft不支援在StorageGRID 高準確度環境中使用、例如：



== Linux：網路連線問題

您可能會發現在 Linux 主機上裝載的 StorageGRID 節點的網路連線問題。



=== MAC位址複製

在某些情況下、可使用MAC位址複製來解決網路問題。如果您使用的是虛擬主機、請在節點組態檔中將每個網路的MAC位址複製金鑰值設為「true」。此設定會使StorageGRID 不支援的容器的MAC位址使用主機的MAC位址。若要建立節點組態檔案、請參閱或link:../ubuntu/creating-node-configuration-files.html["Ubuntu或DEBIAN"]的指示link:../rhel/creating-node-configuration-files.html["Red Hat Enterprise Linux"]。


NOTE: 建立獨立的虛擬網路介面、供Linux主機作業系統使用。如果StorageGRID Hypervisor上未啟用混雜模式、則在Linux主機作業系統和支援此功能的Container上使用相同的網路介面、可能會導致主機作業系統無法連線。

如需啟用 MAC 複製的詳細資訊、請參閱或link:../ubuntu/configuring-host-network.html["Ubuntu或DEBIAN"]的說明link:../rhel/configuring-host-network.html["Red Hat Enterprise Linux"]。



=== 混雜模式

如果您不想使用 MAC 位址複製、而是希望允許所有介面接收和傳輸 MAC 位址的資料、而非 Hypervisor 指定的位址、 請確定虛擬交換器和連接埠群組層級的安全性內容在「雜亂模式」、「 MAC 位址變更」和「僞造傳輸」中設為 * 接受 * 。虛擬交換器上設定的值可由連接埠群組層級的值覆寫、因此請確保兩個位置的設定都相同。

有關使用混雜模式的詳細信息，請參閱或link:../ubuntu/configuring-host-network.html["Ubuntu或DEBIAN"]的說明link:../rhel/configuring-host-network.html["Red Hat Enterprise Linux"]。



== Linux ：節點狀態為「孤立」

處於孤立狀態的Linux節點通常表示StorageGRID 、控制StorageGRID 節點容器的孤立服務或是由節點監控的節點監控程式、會在非預期情況下死亡。

.關於這項工作
如果Linux節點回報其處於孤立狀態、您應該：

* 檢查記錄中是否有錯誤和訊息。
* 嘗試重新啟動節點。
* 如有必要、請使用Container Engine命令來停止現有的節點容器。
* 重新啟動節點。


.步驟
. 檢查服務精靈和孤立節點的記錄、查看是否有明顯的錯誤或非預期結束的訊息。
. 以root身分或使用具有Sudo權限的帳戶登入主機。
. 執行下列命令、嘗試再次啟動節點： `$ sudo storagegrid node start node-name`
+
 $ sudo storagegrid node start DC1-S1-172-16-1-172
+
如果節點是孤立的、則回應為

+
[listing]
----
Not starting ORPHANED node DC1-S1-172-16-1-172
----
. 從Linux停止Container引擎和任何控制的storagegrid節點程序。例如：``sudo docker stop --time secondscontainer-name``
+
對於 `seconds`，輸入要等待容器停止的秒數（通常爲 15 分鐘或更短）。例如：

+
[listing]
----
sudo docker stop --time 900 storagegrid-DC1-S1-172-16-1-172
----
. 重新啟動節點： `storagegrid node start node-name`
+
[listing]
----
storagegrid node start DC1-S1-172-16-1-172
----




== Linux：疑難排解IPv6支援

如果您在StorageGRID Linux主機上安裝了支援IPv6的節點、而且您注意到IPv6位址尚未如預期指派給節點容器、則可能需要在核心中啟用IPv6支援。

.關於這項工作
若要查看已指派給網格節點的 IPv6 位址：

. 選取 * 節點 * 、然後選取節點。
. 在「概述」標籤的 * IP 位址 * 旁、選取 * 顯示其他 IP 位址 * 。


如果未顯示IPv6位址、且節點已安裝在Linux主機上、請依照下列步驟在核心中啟用IPv6支援。

.步驟
. 以root身分或使用具有Sudo權限的帳戶登入主機。
. 執行下列命令： `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@SG:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
結果應為 0 。

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+

NOTE: 如果結果不是 0 、請參閱作業系統文件以變更 `sysctl`設定。然後、請先將值變更為0再繼續。

. 輸入 StorageGRID 節點容器： `storagegrid node enter node-name`
. 執行下列命令： `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@DC1-S1:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
結果應為 1 。

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 1
----
+

NOTE: 如果結果不是1、則此程序不適用。聯絡技術支援。

. 結束容器： `exit`
+
[listing]
----
root@DC1-S1:~ # exit
----
. 以 root 用戶身份編輯以下文件 `/var/lib/storagegrid/settings/sysctl.d/net.conf`：。
+
[listing]
----
sudo vi /var/lib/storagegrid/settings/sysctl.d/net.conf
----
. 找出下列兩行、並移除註解標記。然後儲存並關閉檔案。
+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+
[listing]
----
net.ipv6.conf.default.disable_ipv6 = 0
----
. 執行下列命令以重新啟動StorageGRID 此資訊容器：
+
[listing]
----
storagegrid node stop node-name
----
+
[listing]
----
storagegrid node start node-name
----

