---
permalink: troubleshoot/troubleshooting-load-balancer-caching.html 
sidebar: sidebar 
keywords: how to troubleshoot load balancer caching 
summary: 了解負載平衡器快取可能存在的問題以及如何解決這些問題。 
---
= 排查負載平衡器快取問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解負載平衡器快取可能存在的問題以及如何解決這些問題。



== 確定請求是否為快取命中

* X-Cache 標頭是在快取服務處理的請求的回應中設定的。可能的代碼：
+
** `HIT`：該物件由快取提供
** `PARTIAL-HIT`：儲存桶/鍵在快取中有記錄，但並非所有請求的範圍都能夠從快取中得到服務
** `STALE`：儲存桶/鍵在快取中有一個記錄，但自上次從快取中提供該物件後，該物件已被更新。
** `MISS`：該物件不在快取中


* 這 `nginx-gw/endpoint-access.log.gz`請求的記錄包括“unix:/run/cache-svc/cache-svc.sock”，用於快取處理的請求。
* 這 `cache-svc/cache-svc.log`報告諸如「請求 320390：成功完成（快取命中）」或「請求 320375：成功完成（快取未命中）」之類的訊息。透過搜尋具有相同「Request _<number>_」字串的其他記錄來尋找請求的路徑。




== 快取命中率低

* 當新增新的工作負載或工作負載存取的工作集發生變化時，可能會出現較低的快取命中率。在這些情況下，命中率預計會隨著時間的推移而增加。
* 如果多個工作負載正在使用緩存，請考慮新增流量分類策略來隔離由快取服務的工作負載部分。每個流量分類策略都有快取命中率指標。如果某些工作負載的快取命中率不高，請考慮將這些工作負載移至未啟用快取的其他端點。
* 評估快取驅逐率。如果快取太小而無法容納工作集，它將經歷高驅逐率並可能導致命中率降低。
* FPVR 下可能提供用於提高某些工作負載命中率的選項。




== 性能低下

* 評估緩存命中率。低緩存命中率會導致整體效能低下。
* 評估快取驅逐率。在驅逐期間，一些儲存資源用於從磁碟中刪除現有物件。如果驅逐過程跟不上新物件的訪問，系統可能會達到硬水印閾值並開始繞過快取。
* 使用「網路介面接收使用情況」和「網路介面傳輸使用情況」診斷檢查網路限制。

