---
permalink: troubleshoot/verifying-object-integrity.html 
sidebar: sidebar 
keywords: how to verify object integrity, object existence check, background verification 
summary: 此系統可驗證儲存節點上物件資料的完整性、同時檢查毀損和遺失的物件。StorageGRID 
---
= 驗證物件完整性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此系統可驗證儲存節點上物件資料的完整性、同時檢查毀損和遺失的物件。StorageGRID

驗證程序有兩種：背景驗證和物件存在檢查（先前稱為前景驗證）。他們共同合作、確保資料完整性。背景驗證會自動執行、並持續檢查物件資料的正確性。使用者可觸發物件存在檢查、以更快驗證物件的存在（雖然不正確）。



== 什麼是背景驗證？

背景驗證程序會自動持續檢查儲存節點是否有物件資料毀損的複本、並自動嘗試修復找到的任何問題。

背景驗證會檢查複寫物件和銷毀編碼物件的完整性、如下所示：

* *複寫物件*：如果背景驗證程序找到毀損的複寫物件、則毀損的複本會從其位置移除、並隔離儲存節點上的其他位置。接著會產生新的未損毀複本、並將其放置在符合使用中 ILM 原則的位置。新複本可能不會放在原始複本所使用的儲存節點上。



NOTE: 毀損的物件資料會被隔離、而非從系統中刪除、以便仍可存取。如需存取隔離物件資料的詳細資訊、請聯絡技術支援部門。

* *刪除編碼物件*：如果背景驗證程序偵測到刪除編碼物件的片段毀損、StorageGRID 則會使用剩餘的資料和同位元檢查片段、自動嘗試在同一個儲存節點上重新建置遺失的片段。如果損壞的片段無法重建、則會嘗試擷取該物件的另一個複本。如果擷取成功、則會執行ILM評估、以建立銷毀編碼物件的替換複本。
+
背景驗證程序僅會檢查儲存節點上的物件。它不會檢查 Cloud Storage Pool 中的物件。物件必須超過四天才能符合背景驗證資格。



背景驗證會以不干擾一般系統活動的持續速度執行。背景驗證無法停止。不過、您可以提高背景驗證率、以便在懷疑有問題時更快驗證儲存節點的內容。



== 與背景驗證相關的警示

如果系統偵測到毀損的物件無法自動修正（因為毀損會防止物件被識別）、就會觸發 * 未識別的毀損物件偵測 * 警示。

如果後台驗證無法取代損壞的對象，因為它無法找到另一個副本，則會觸發*對象可能會遺失*警報。



== 什麼是物件存在檢查？

物件存在檢查可驗證儲存節點上是否存在所有預期的物件複本和銷毀編碼片段。物件存在檢查不會驗證物件資料本身（背景驗證會驗證）、而是提供驗證儲存裝置完整性的方法、尤其是最近發生的硬體問題可能會影響資料完整性時。

與自動進行背景驗證不同、您必須手動啟動物件存在檢查工作。

物件存在檢查會讀取StorageGRID 儲存在物件中的每個物件的中繼資料、並驗證複寫的物件複本和銷毀編碼的物件片段是否存在。任何遺失的資料都會以下列方式處理：

* *複製的複本*：如果缺少複製物件資料的複本、StorageGRID 則會自動嘗試從儲存在系統其他地方的複本中更換複本。儲存節點會透過ILM評估執行現有複本、以判斷此物件不再符合目前的ILM原則、因為缺少另一個複本。系統會產生並放置新的複本、以滿足系統的主動式 ILM 原則。此新複本可能不會放在儲存遺失複本的相同位置。
* *刪除編碼的片段*：如果刪除編碼物件的片段遺失、StorageGRID 則會使用其餘的片段、自動嘗試在同一個儲存節點上重建遺失的片段。如果無法重建遺失的片段（因為遺失的片段太多）、 ILM 會嘗試尋找物件的另一個複本、以用於產生新的銷毀編碼片段。




== 執行物件存在檢查

您一次只能建立並執行一個物件存在檢查工作。當您建立工作時、請選取您要驗證的儲存節點和磁碟區。您也可以選取工作的一致性。

.開始之前
* 您已使用登入 Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您有link:../admin/admin-group-permissions.html["維護或根存取權限"]。
* 您已確保要檢查的儲存節點處於線上狀態。選擇*節點*來查看節點表。確保要檢查的節點的節點名稱旁邊沒有出現警報圖示。
* 您已確保下列程序*未*在您要檢查的節點上執行：
+
** 網格擴充以新增儲存節點
** 儲存節點取消委任
** 恢復故障的儲存磁碟區
** 恢復具有故障系統磁碟機的儲存節點
** EC重新平衡
** 應用裝置節點複製




物件存在檢查無法在這些程序進行期間提供實用資訊。

.關於這項工作
根據網格中的物件數量、選取的儲存節點和磁碟區、以及選取的一致性、物件存在檢查工作可能需要數天或數週的時間才能完成。您一次只能執行一個工作、但可以同時選取多個儲存節點和磁碟區。

.步驟
. 選擇*維護* > *任務* > *物件存在檢查*。
. 選取*建立工作*。「建立物件存在檢查」工作精靈隨即出現。
. 選取包含您要驗證之磁碟區的節點。若要選取所有線上節點、請選取欄標題中的 * 節點名稱 * 核取方塊。
+
您可以依節點名稱或站台進行搜尋。

+
您無法選取未連線至網格的節點。

. 選擇*繼續*。
. 為清單中的每個節點選取一或多個磁碟區。您可以使用儲存磁碟區編號或節點名稱來搜尋磁碟區。
+
若要為您選取的每個節點選取所有磁碟區、請選取欄標題中的 * 儲存磁碟區 * 核取方塊。

. 選擇*繼續*。
. 選取工作的一致性。
+
一致性決定物件中繼資料的複本數量、用於物件存在檢查。

+
** * Strong站台*：單一站台的兩個中繼資料複本。
** *強式全域*：每個站台有兩份中繼資料複本。
** * All（全部）*（預設）：每個站台的所有三個中繼資料複本。
+
如需一致性的詳細資訊、請參閱精靈中的說明。



. 選擇*繼續*。
. 檢閱並驗證您的選擇。您可以選取*上一個*、移至精靈的上一個步驟、以更新您的選擇。
+
物件存在檢查工作會產生並執行、直到發生下列其中一項：

+
** 工作完成。
** 您可以暫停或取消工作。您可以恢復已暫停的工作、但無法恢復已取消的工作。
** 工作中斷。觸發*物件存在檢查已停止*警示。請遵循針對警示所指定的修正行動。
** 工作失敗。觸發*物件存在檢查失敗*警示。請遵循針對警示所指定的修正行動。
** 出現「服務無法使用」或「內部伺服器錯誤」訊息。一分鐘後、重新整理頁面以繼續監控工作。
+

NOTE: 視需要、您可以離開「物件存在」檢查頁面、然後返回以繼續監控工作。



. 當工作執行時、請檢視*作用中工作*索引標籤、並記下偵測到的遺失物件複本值。
+
此值代表一或多個遺失片段的複寫物件和銷毀編碼物件的遺失複本總數。

+
如果偵測到的遺失物件副本數量大於 100，則儲存節點的儲存可能有問題。

. 工作完成後、請採取任何其他必要行動：
+
** 如果偵測到的物件複本遺失為零、則找不到問題。無需採取任何行動。
** 如果偵測到的遺失物件副本大於零且未觸發*物件可能遺失*警報，則系統已修正所有遺失的副本。驗證所有硬體問題是否都已修正，以防止將來對物件副本造成損壞。
** 如果偵測到的遺失物件副本數大於零，並且觸發了*物件可能會遺失*警報，則資料完整性可能會受到影響。聯繫技術支援。
** 您可以使用 grep 提取 LLST 審計訊息來調查可能遺失的物件副本： `grep LLST audit_file_name` 。
+
此過程類似於link:../troubleshoot/investigating-potentially-lost-objects.html["調查可能遺失的物品"]，儘管你搜尋的是物件副本 `LLST`而不是 `OLST`。



. 如果您為工作選擇了強式站台或強式全域一致性、請等待約三週的中繼資料一致性、然後再次在相同的磁碟區上重新執行工作。
+
當執行此工作時、若有時間為工作中所含的節點和磁碟區達到中繼資料一致性、重新執行工作可能會清除錯誤回報的物件複本、或是在遺失時檢查其他物件複本。StorageGRID

+
.. 選擇*維護* > *物件存在檢查* > *作業記錄*。
.. 判斷哪些工作已準備好要重新執行：
+
... 請查看*結束時間*欄、以判斷三週前執行的工作。
... 對於這些工作、請掃描一致性控制欄、找出強站台或強全域。


.. 選中要重新運行的每個作業的複選框，然後選擇 *rerun* 。
.. 在重新執行工作精靈中、檢閱選取的節點和磁碟區、以及一致性。
.. 當您準備好重新執行工作時、請選取*重新執行*。




此時會出現作用中工作索引標籤。您選取的所有工作都會在強式站台的一致性上以單一工作的方式重新執行。「詳細資料」區段中的*相關工作*欄位會列出原始工作的工作ID。
