---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: 瞭解擷取時保護資料的三種選項（平衡、嚴格或雙重承諾）各有哪些優缺點、可協助您決定要為ILM規則選取哪一種選項。 
---
= 擷取選項的優點、缺點和限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解擷取時保護資料的三種選項（平衡、嚴格或雙重提交）各有哪些優缺點、可協助您決定要為ILM規則選取哪一種選項。

如需擷取選項的總覽link:data-protection-options-for-ingest.html["擷取選項"]、請參閱。



== 平衡且嚴格的選項優勢

相較於在擷取期間建立臨時複本的「雙重提交」、兩個同步放置選項可提供下列優點：

* *更佳的資料安全性*：物件資料會立即受到ILM規則放置指示中所指定的保護、您可設定此指示、以防止各種故障情況發生、包括多個儲存位置的故障。雙重提交只能防止單一本機複本遺失。
* *更有效率的網格作業*：每個物件只會在擷取時處理一次。由於不需要追蹤或刪除過渡複本、因此處理負載較少、資料庫空間也較少。StorageGRID
* *（平衡）建議*：平衡選項可提供最佳ILM效率。除非需要嚴格的擷取行為、或網格符合使用雙重提交的所有條件、否則建議使用平衡選項。
* *（嚴格）物件位置的確定性*：嚴格選項可確保物件立即根據ILM規則中的放置指示儲存。




== 平衡且嚴格的選項缺點

相較於雙重承諾、平衡且嚴格的選項有一些缺點：

* *用戶端擷取時間較長*：用戶端擷取延遲時間可能較長。當您使用平衡或嚴格選項時、除非建立並儲存所有的銷毀編碼片段或複寫複本、否則「擷取成功」訊息不會傳回用戶端。不過、物件資料很可能會更快到達最終放置位置。
* * （嚴格）較高的擷取失敗率 * ：使用嚴格選項、只要 StorageGRID 無法立即製作 ILM 規則中指定的所有複本、擷取就會失敗。如果所需的儲存位置暫時離線、或是網路問題導致站台之間複製物件時延遲、您可能會看到擷取失敗率偏高。
* *（嚴格）S3多部份上傳放置位置在某些情況下可能不如預期*：嚴格來說、您期望物件放置方式必須符合ILM規則的說明、否則擷取失敗。不過、在 S3 多部分上傳時、系統會在擷取物件的每個部分時評估 ILM 、並在多部分上傳完成時評估整個物件的 ILM 。在下列情況下、這可能會導致刊登位置與您預期的不同：
+
** 如果在S3多重部分上傳進行時ILM發生變更*：由於每個部分都是根據擷取零件時作用中的規則放置、因此當多重部分上傳完成時、物件的某些部分可能無法符合目前的ILM需求。在這些情況下、物件的擷取不會失敗。相反地、任何未正確放置的零件都會排入 ILM 重新評估的佇列、稍後會移至正確的位置。
** *當ILM規則根據尺寸篩選*：評估零件的ILM時、StorageGRID 會根據零件大小篩選出、而非物件大小。這表示物件的部分可以儲存在不符合整體物件 ILM 需求的位置。例如、如果規則指定所有10 GB或更大的物件都儲存在DC1、而所有較小的物件則儲存在DC2、則在10部分多部分上傳的每1 GB擷取部分、都會儲存在DC2。評估物件的ILM時、物件的所有部分都會移至DC1。


* *（嚴格）當物件標記或中繼資料更新且無法建立新的必要放置位置時、內嵌功能不會失敗*：嚴格來說、您期望物件放置在ILM規則所述的位置、或是擷取失敗。但是、當您更新已儲存在網格中之物件的中繼資料或標記時、不會重新擷取該物件。這表示任何由更新觸發的物件放置變更、都不會立即進行。當ILM由正常背景ILM程序重新評估時、便會進行放置變更。如果無法進行必要的放置變更（例如、因為新的必要位置無法使用）、更新的物件會保留目前的放置位置、直到可能變更放置位置為止。




== 使用平衡且嚴格的選項來限制物件放置

平衡或嚴格的選項無法用於具有下列任一放置指示的 ILM 規則：

* 第0天放入雲端儲存資源池。
* 當規則的建立時間為使用者定義的參考時間時、放置在雲端儲存池中。


這些限制之所以存在、是因為 StorageGRID 無法同步製作複本至雲端儲存池、而使用者定義的建立時間可能會解決目前的問題。



== ILM 規則與一致性如何互動、以影響資料保護

您的 ILM 規則和一致性選擇都會影響物件的保護方式。這些設定可以互動。

例如、為 ILM 規則選取的擷取行為會影響物件複本的初始放置、而儲存物件時所使用的一致性則會影響物件中繼資料的初始放置。由於 StorageGRID 需要同時存取物件的資料和中繼資料、才能滿足用戶端要求、因此針對一致性和擷取行為選擇符合的保護層級、可以提供更好的初始資料保護和更可預測的系統回應。

以下是 StorageGRID 中可用一致性值的簡短摘要：

* * 全部 * ：所有節點都會立即接收物件中繼資料、否則要求將會失敗。
* *強全域*：保證所有網站上所有客戶端請求的讀寫一致性。配置 Quorum 語意時，將套用下列行為：
+
** 當網格具有三個或更多站點時，允許對客戶端請求進行站點故障容忍。雙站點電網不具備站點故障容忍能力。
** 如果一個站點發生故障，以下 S3 操作將無法成功：
+
*** 刪除 BucketEncryption
*** PutBucketBranch
*** PuttBucketEncryption
*** PuttBucketVersion
*** PutObjectLegalHold
*** PutObjectLockConfiguration
*** PutObjectRetention




+
如果需要的話，你可以 https://kb.netapp.com/hybrid/StorageGRID/Object_Mgmt/Configuring_StorageGRID_quorum_semantics_for_strong-global_consistency["配置StorageGRID Quorum 語意以實現強全域一致性"^]。

* *Strong-site* ：物件中繼資料會立即散佈到站台上的其他節點。保證站台內所有用戶端要求的寫入後讀取一致性。
* * 新寫入後讀 * ：提供新物件的寫入後讀取一致性、以及物件更新的最終一致性。提供高可用度與資料保護保證。建議大多數情況下使用。
* * 可用 * ：提供新物件和物件更新的最終一致性。對於 S3 貯體、請僅視需要使用（例如、包含很少讀取的記錄值之貯體、或用於對不存在的金鑰執行 head 或 Get 作業）。S3 FabricPool 儲存區不支援。



NOTE: 在選擇一致性值之前，link:../s3/consistency.html["閱讀一致性的完整說明"] 。在更改預設值之前，您應該了解其優點和限制。



== 一致性與 ILM 規則互動方式的範例

假設您有一個三站點網格，具有以下 ILM 規則和以下一致性：

* *ILM 規則*：建立三個物件副本，一個在本機站點，另一個在每個遠端站點。使用嚴格的攝取行為。
* *一致性*：強全域（物件元資料立即分發到多個站點）。


當客戶端將物件儲存到網格時， StorageGRID會複製所有三個物件並將元資料分發到多個站點，然後再將成功返回給客戶端。

在接收成功訊息時，物件將受到完全保護，不會遺失。例如，如果本機站點在攝取後不久遺失，則物件資料和物件元資料的副本仍然存在於遠端站點。該物件可以從其他站點完全檢索。

如果您使用相同的 ILM 規則和強站點一致性，則用戶端可能會在物件資料複製到遠端站點之後但在物件元資料分發到那裡之前收到成功訊息。在這種情況下，物件元資料的保護等級與物件資料的保護等級不符。如果本地站點在攝取後不久遺失，則物件元資料就會遺失。無法檢索該物件。

一致性與 ILM 規則之間的相互關係可能很複雜。如需協助、請聯絡 NetApp 。

.相關資訊
link:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.html["範例5：嚴格擷取行為的ILM規則與原則"]
