---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 設定並使用儲存資源池、透過在多個站台之間散佈資料來防止資料遺失。複寫複本和銷毀編碼複本需要不同的儲存池組態。 
---
= 建立儲存資源池的準則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定並使用儲存資源池、透過在多個站台之間散佈資料來防止資料遺失。複寫複本和銷毀編碼複本需要不同的儲存池組態。

請參閱。 link:using-multiple-storage-pools-for-cross-site-replication.html["使用複寫和銷毀編碼來啟用站台遺失保護的範例"]



== 所有儲存資源池的準則

* 盡量簡化儲存資源池組態。請勿建立超過必要數量的儲存資源池。
* 建立盡可能多節點的儲存資源池。每個儲存資源池應包含兩個以上的節點。如果節點無法使用、節點不足的儲存資源池可能會導致ILM待處理記錄。
* 避免建立或使用重疊的儲存資源池（包含一或多個相同節點）。如果儲存資源池重疊、可能會在同一個節點上儲存多個物件資料複本。
* 一般而言、請勿使用「所有儲存節點」儲存池（ StorageGRID 11.6 以上版本）或「所有站台」網站。這些項目會自動更新、以納入您在擴充中新增的任何新網站、這可能不是您想要的行為。




== 複寫複本所使用的儲存資源池準則

* 對於使用的站台遺失保護link:what-replication-is.html["複寫"]，請在中指定一或多個站台專屬link:create-ilm-rule-define-placements.html["每個 ILM 規則的放置指示"]的儲存集區。
+
在 StorageGRID 安裝期間、會為每個站台自動建立一個儲存池。

+
針對每個站台使用儲存資源池、可確保複寫的物件複本完全符合您的期望（例如、每個站台的每個物件都有一個複本、以保護站台損失）。

* 如果您在擴充中新增站台、請建立只包含新站台的新儲存池。然後、link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["更新 ILM 規則"]控制要儲存在新網站上的物件。
* 如果複本數小於儲存集區的數量、系統就會散佈複本、以平衡集區之間的磁碟使用量。
* 如果儲存資源池重疊（包含相同的儲存節點）、則物件的所有複本可能只會儲存在一個站台。您必須確保所選的儲存資源池不包含相同的儲存節點。




== 用於銷毀編碼複本的儲存資源池準則

* 若要使用link:what-erasure-coding-is.html["銷毀編碼"]進行站台遺失保護、請建立至少包含三個站台的儲存資源池。如果儲存池只包含兩個站台、您就無法使用該儲存池進行銷毀編碼。對於有兩個站台的儲存資源池、沒有可用的銷毀編碼方案。
* 儲存資源池中包含的儲存節點和站台數目、決定哪些link:what-erasure-coding-schemes-are.html["銷毀編碼配置"]可用。
* 如果可能、儲存資源池應包含超過您所選銷毀編碼方案所需的最小儲存節點數。例如、如果您使用6+3銷毀編碼方案、則至少必須有九個儲存節點。不過、建議每個站台至少有一個額外的儲存節點。
* 將儲存節點分散至各個站台、盡量平均。例如、若要支援6+3銷毀編碼方案、請在三個站台設定至少包含三個儲存節點的儲存資源池。
* 如果您的處理量需求很高、如果站台之間的網路延遲超過 100 毫秒、則不建議使用包含多個站台的儲存池。隨著延遲時間增加、StorageGRID 由於TCP網路處理量減少、導致導致導致無法建立、放置及擷取物件片段的速度大幅降低。
+
處理量的降低會影響物件擷取和擷取的最大可達成率（如果選取平衡或嚴格作為擷取行為）、或可能導致 ILM 佇列待處理記錄（當選擇雙重提交作為擷取行為時）。請參閱。 link:what-ilm-rule-is.html#ilm-rule-ingest-behavior["ILM 規則擷取行為"]

+

NOTE: 如果您的網格僅包含一個站台、您將無法在銷毀編碼設定檔中使用所有儲存節點儲存池（ StorageGRID 11.6 以上版本）或所有站台。此行為可防止在新增第二個站台時、設定檔變成無效。


