---
permalink: ilm/how-object-retention-is-determined.html 
sidebar: sidebar 
keywords: how object retention is determined 
summary: 支援網格管理員和個別租戶使用者的選項、可指定儲存物件的時間長度。StorageGRID一般而言、租戶使用者所提供的任何保留指示、均優先於網格管理員所提供的保留指示。 
---
= 如何判斷物件保留
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援網格管理員和個別租戶使用者的選項、可指定儲存物件的時間長度。StorageGRID一般而言、租戶使用者所提供的任何保留指示、均優先於網格管理員所提供的保留指示。



== 租戶使用者如何控制物件保留

租戶使用者可以使用這些方法來控制物件在 StorageGRID 中的儲存時間：

* 如果網格已啟用全域 S3 物件鎖定設定、 S3 租戶使用者可以建立啟用 S3 物件鎖定的儲存格、然後為每個儲存格選取 * 預設保留期間 * 。
* 如果已啟用網格的全域S3物件鎖定設定、S3租戶使用者就能建立啟用S3物件鎖定的儲存區、然後使用S3 REST API來指定新增至該儲存區之每個物件版本的保留直到日期和合法保留設定。
+
** 合法持有的物件版本無法由任何方法刪除。
** 在物件版本達到保留截止日期之前、任何方法都無法刪除該版本。
** 啟用 S3 物件鎖定的貯體中物件會由 ILM 「永遠」保留。不過、在達到保留截止日期之後、用戶端要求或儲存庫生命週期到期時、即可刪除物件版本。請參閱。 link:managing-objects-with-s3-object-lock.html["使用S3物件鎖定來管理物件"]


* S3租戶使用者可將生命週期組態新增至其指定到期行動的儲存區。如果儲存區生命週期存在、StorageGRID 除非用戶端先刪除物件、否則在到期行動中指定的日期或天數之前、將會儲存物件。請參閱。 link:../s3/create-s3-lifecycle-configuration.html["建立S3生命週期組態"]
* S3 用戶端可以發出刪除物件要求。確定要刪除或保留物件時、往往會優先處理S3儲存區生命週期或ILM上的用戶端刪除要求。StorageGRID




== 網格管理員如何控制物件保留

網格管理員可以使用下列方法來控制物件保留：

* 為每個租戶設定 S3 物件鎖定最長保留期間。然後、租戶使用者可以為每個貯體設定預設保留期間。對於該貯體（物件的保留至日期）的任何新擷取物件、也會強制執行最大保留期間。
* 建立 ILM 放置指示、以控制物件的儲存時間。當物件與ILM規則相符時、StorageGRID 直到ILM規則的最後一段時間結束為止、才會將這些物件儲存起來。如果為放置指示指定「永遠」、則物件會無限期保留。
* 無論物件保留的時間長短由誰控制、 ILM 設定都會控制儲存的物件複本類型（複寫或銷毀編碼）、以及複本的位置（儲存節點或雲端儲存池）。




== S3儲存區生命週期與ILM之間的互動方式

當 S3 貯體生命週期設定完成時、生命週期到期動作會覆寫符合生命週期篩選器之物件的 ILM 原則。因此、即使放置物件的任何ILM指示失效、物件仍可能保留在網格上。



== 物件保留範例

若要更深入瞭解S3物件鎖定、儲存區生命週期設定、用戶端刪除要求和ILM之間的互動、請考慮下列範例。



=== 範例1：S3儲存區生命週期可延長物件的壽命、而非ILM

ILM:: 儲存兩份複本一年（365天）
生命週期:: 物件在2年內過期（730天）
結果:: 將物件儲存730天。StorageGRID使用儲存區生命週期設定來決定是否要刪除或保留物件。StorageGRID



NOTE: 如果儲存區生命週期指定物件的保留時間應超過ILM指定的時間、StorageGRID 則當判斷要儲存的複本數量和類型時、NetApp會繼續使用ILM放置指示。在此範例中、物件的兩份複本將繼續儲存在StorageGRID 從第3666天到730天的地方。



=== 範例2：S3儲存區生命週期會在ILM之前過期物件

ILM:: 儲存兩份複本2年（730天）
生命週期:: 物件在1年內到期（365天）
結果:: 支援在365天之後刪除物件的兩個複本。StorageGRID




=== 範例3：用戶端刪除會覆寫儲存區生命週期和ILM

ILM:: 在儲存節點上「永遠」儲存兩份複本
生命週期:: 物件在2年內過期（730天）
用戶端刪除要求:: 於第400天發行
結果:: 針對用戶端刪除要求、在第400天刪除物件的兩個複本。StorageGRID




=== 範例4：S3物件鎖定會覆寫用戶端刪除要求

S3物件鎖定:: 物件版本的保留截止日期為2026-03-31。合法持有並未生效。
符合ILM規則:: 在儲存節點上「永遠」儲存兩份複本
用戶端刪除要求:: 於 2024-03-31 發佈
結果:: 由於保留截止日期仍在2年前、所以無法刪除物件版本。StorageGRID

