---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: 身為網格管理員、您可以為StorageGRID 您的系統啟用S3物件鎖定、並實作符合法規的ILM原則、以確保特定S3儲存區中的物件在指定時間內不會被刪除或覆寫。 
---
= 使用S3物件鎖定來管理物件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
身為網格管理員、您可以為 StorageGRID 系統啟用 S3 物件鎖定、並實作相容的 ILM 原則、以確保特定 S3 儲存區中的物件不會在指定的時間內遭到刪除或覆寫。



== 什麼是S3物件鎖定？

「物件鎖定」功能是物件保護解決方案、StorageGRID 相當於Amazon Simple Storage Service（Amazon S3）中的S3物件鎖定。

當 StorageGRID 系統啟用全域 S3 物件鎖定設定時、 S3 租戶帳戶可以建立已啟用或未啟用 S3 物件鎖定的貯體。如果貯體已啟用 S3 物件鎖定、則需要設定貯體版本、而且會自動啟用。

* 沒有 S3 物件鎖定 * 的貯體只能有未指定保留設定的物件。任何擷取的物件都不會有保留設定。

* 具有 S3 物件鎖定 * 的儲存貯體可以有物件、無論是否有 S3 用戶端應用程式指定的保留設定。某些擷取的物件會有保留設定。

* 已設定 S3 物件鎖定和預設保留 * 的貯體、可以使用指定的保留設定來上傳物件、也可以不保留設定來上傳新物件。新物件會使用預設設定、因為尚未在物件層級設定保留設定。

有效地說、所有新擷取的物件在設定預設保留時都會有保留設定。沒有物件保留設定的現有物件不會受到影響。



=== 保留模式

StorageGRID S3 物件鎖定功能支援兩種保留模式、可將不同層級的保護套用至物件。這些模式相當於 Amazon S3 保留模式。

* 在法規遵循模式中：
+
** 直到達到物件的保留日期、才能刪除物件。
** 物件的保留日期可以增加、但不能減少。
** 直到達到該日期為止、才能移除物件的保留日期。


* 在治理模式中：
+
** 具有特殊權限的使用者可以在修改特定保留設定的要求中使用略過標頭。
** 這些使用者可以在達到物件版本的保留截止日期之前刪除物件版本。
** 這些使用者可以增加、減少或移除物件的保留到目前為止。






=== 物件版本的保留設定

如果在啟用 S3 物件鎖定的情況下建立貯體、使用者可以使用 S3 用戶端應用程式、針對新增至貯體的每個物件、選擇性地指定下列保留設定：

* * 保留模式 * ：法規遵循或治理。
* * 保留至日期 * ：如果物件版本的保留至未來日期、則可以擷取物件、但無法刪除。
* *合法持有*：將合法持有套用至物件版本、會立即鎖定該物件。例如、您可能需要對與調查或法律爭議相關的物件保留法律。合法持有沒有到期日、但在明確移除之前、仍會保留到位。合法持有不受保留至日期的限制。
+

NOTE: 如果物件處於合法保留狀態、則無論物件的保留模式為何、任何人都無法刪除該物件。

+
如需物件設定的詳細資料、請參閱link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]。





=== 貯體的預設保留設定

如果在啟用 S3 物件鎖定的情況下建立貯體、使用者可以選擇性地指定貯體的下列預設設定：

* * 預設保留模式 * ：法規遵循或治理。
* * 預設保留期間 * ：新增至此貯體的物件版本應保留多久、從新增物件之日起算。


預設的貯體設定僅適用於沒有自己保留設定的新物件。當您新增或變更這些預設設定時、現有的貯體物件不會受到影響。

請參閱link:../tenant/creating-s3-bucket.html["建立S3儲存區"]和link:../tenant/update-default-retention-settings.html["更新 S3 物件鎖定預設保留"]。



== 比較S3物件鎖定與舊版法規遵循

S3物件鎖定取代舊StorageGRID 版的Compliance功能。由於 S3 物件鎖定功能符合 Amazon S3 的要求、因此它取代了專屬的 StorageGRID 法規遵循功能、這項功能現在稱為「舊版法規遵循」。


NOTE: 全域規範設定已過時。如果您使用舊版 StorageGRID 啟用此設定、 S3 物件鎖定設定會自動啟用。您可以繼續使用 StorageGRID 來管理現有相容貯體的設定、但您無法建立新的相容貯體。如需詳細資訊、請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"^]。

如果您使用StorageGRID 舊版的更新版本的支援功能、請參閱下表、瞭解其與StorageGRID 更新版本中S3物件鎖定功能的比較。

[cols="1a,1a,1a"]
|===
|  | S3物件鎖定 | 法規遵循（舊版） 


 a| 
如何在全域啟用此功能？
 a| 
從網格管理器中，選擇*配置* > *系統* > *S3 物件鎖定*。
 a| 
不再支援。



 a| 
此功能如何啟用儲存庫？
 a| 
使用者必須啟用S3物件鎖定、才能使用租戶管理程式、租戶管理API或S3 REST API建立新的儲存區。
 a| 
不再支援。



 a| 
是否支援儲存區版本管理？
 a| 
是的。儲存區版本設定是必要的、且會在啟用儲存區的S3物件鎖定時自動啟用。
 a| 
不可以



 a| 
如何設定物件保留？
 a| 
使用者可以為每個物件版本設定保留截止日期、也可以為每個貯體設定預設保留期間。
 a| 
使用者必須為整個儲存庫設定保留期間。保留期間適用於貯體中的所有物件。



 a| 
保留期間可以變更嗎？
 a| 
* 在規範模式中、物件版本的保留日期可以增加、但不會減少。
* 在治理模式中、具有特殊權限的使用者可以減少或甚至移除物件的保留設定。

 a| 
貯體的保留期間可以增加、但不會縮短。



 a| 
合法持有控制在哪裡？
 a| 
使用者可以合法持有或撤銷貯體中任何物件版本的合法持有。
 a| 
合法持有會置於貯體上、並影響貯體中的所有物件。



 a| 
何時可以刪除物件？
 a| 
* 在符合性模式中、如果物件未處於合法保留狀態、則可在達到保留截止日期後刪除物件版本。
* 在治理模式中、具有特殊權限的使用者可以在物件達到保留截止日期之前刪除物件、前提是物件未處於合法保留狀態。

 a| 
保留期間到期後、如果儲存區未處於合法保留狀態、則可刪除物件。物件可以自動或手動刪除。



 a| 
是否支援庫位生命週期組態？
 a| 
是的
 a| 
否

|===