---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: 您必須檢閱啟用全域S3物件鎖定設定的需求、建立相容ILM規則和ILM原則的需求、StorageGRID 以及使用S3物件鎖定之貯體和物件的限制等資訊。 
---
= S3物件鎖定需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須檢閱啟用全域S3物件鎖定設定的需求、建立相容ILM規則和ILM原則的需求、StorageGRID 以及使用S3物件鎖定之貯體和物件的限制等資訊。



== 使用全域S3物件鎖定設定的需求

* 您必須先使用Grid Manager或Grid Management API啟用全域S3物件鎖定設定、任何S3租戶才能建立啟用S3物件鎖定的儲存區。
* 啟用全域S3物件鎖定設定可讓所有S3租戶帳戶建立啟用S3物件鎖定的儲存區。
* 啟用全域 S3 物件鎖定設定之後、您就無法停用該設定。
* 除非所有主動式 ILM 原則中的預設規則為 _ 相容 _ （亦即、預設規則必須符合啟用 S3 物件鎖定的儲存區要求）、否則您無法啟用全域 S3 物件鎖定。
* 啟用全域 S3 物件鎖定設定時、除非原則中的預設規則符合規定、否則您無法建立新的 ILM 原則或啟動現有的 ILM 原則。啟用全域 S3 物件鎖定設定後、 ILM 規則和 ILM 原則頁面會指出哪些 ILM 規則符合規定。




== 符合ILM規則的要求

如果您想要啟用全域 S3 物件鎖定設定、則必須確保所有主動式 ILM 原則中的預設規則都符合規定。相容的規則可同時滿足啟用S3物件鎖定的兩個儲存區需求、以及啟用舊版法規遵循的任何現有儲存區：

* 它必須建立至少兩個複寫的物件複本、或一個銷毀編碼複本。
* 這些複本必須存在於儲存節點上、且必須在放置說明中的每一行的整個期間內存在。
* 物件複本無法儲存在雲端儲存池中。
* 至少一行放置指示必須從第 0 天開始、使用 * 擷取時間 * 作為參考時間。
* 至少一行放置指示必須為「永遠」。




== ILM 原則的需求

當啟用全域 S3 物件鎖定設定時、作用中和非作用中的 ILM 原則可以同時包含相容和不相容的規則。

* 作用中或非作用中 ILM 原則中的預設規則必須相容。
* 不相容的規則僅適用於未啟用 S3 物件鎖定或未啟用舊版規範功能的貯體中物件。
* 符合法規的規則可套用至任何儲存區中的物件；不需要為儲存區啟用S3物件鎖定或舊版符合法規。


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["S3 物件鎖定適用的 ILM 原則範例"]



== 啟用S3物件鎖定的儲存區需求

* 如果StorageGRID 已針對整個S3物件鎖定設定啟用for the S廳 系統、您可以使用租戶管理程式、租戶管理API或S3 REST API來建立啟用S3物件鎖定的儲存區。
* 如果您打算使用S3物件鎖定、則必須在建立儲存區時啟用S3物件鎖定。您無法為現有貯體啟用 S3 物件鎖定。
* 當「S3物件鎖定」已啟用時、StorageGRID 即可自動啟用該儲存區的版本管理功能。您無法停用儲存區的 S3 物件鎖定或暫停版本設定。
* 您也可以選擇使用租戶管理員、租戶管理 API 或 S3 REST API 、為每個貯體指定預設保留模式和保留期間。貯體的預設保留設定僅適用於新增至貯體但沒有其本身保留設定的新物件。您可以指定保留模式來覆寫這些預設設定、並在上傳每個物件版本時保留至日期。
* 啟用 S3 物件鎖定的貯體支援貯體生命週期組態。
* 啟用S3物件鎖定的儲存區不支援CloudMirror複寫。




== 啟用S3物件鎖定之儲存區中的物件需求

* 若要保護物件版本、您可以指定貯體的預設保留設定、或是指定每個物件版本的保留設定。可以使用 S3 用戶端應用程式或 S3 REST API 來指定物件層級保留設定。
* 保留設定適用於個別物件版本。物件版本可以同時具有「保留直到日期」和「合法保留」設定、但不能有另一個設定、或兩者都沒有。指定物件的保留截止日期或合法保留設定、只會保護要求中指定的版本。您可以建立物件的新版本、而舊版物件仍會保持鎖定狀態。




== 啟用S3物件鎖定的儲存區物件生命週期

儲存在已啟用 S3 物件鎖定的儲存貯體中的每個物件都會經過下列階段：

. *物件擷取*
+
當物件版本新增至啟用 S3 物件鎖定的儲存區時、保留設定會套用如下：

+
** 如果為物件指定保留設定、則會套用物件層級的設定。任何預設貯體設定都會被忽略。
** 如果未指定物件的保留設定、則會套用預設貯體設定（如果存在）。
** 如果未指定物件或貯體的保留設定、則 S3 物件鎖定不會保護該物件。


+
如果套用保留設定、則物件和任何 S3 使用者定義的中繼資料都會受到保護。

. * 物件保留與刪除 *
+
StorageGRID 會在指定的保留期間內儲存每個受保護物件的多個複本。物件複本和儲存位置的確切數量和類型取決於主動式 ILM 原則中的相容規則。受保護物件是否能在達到保留截止日期之前刪除、取決於其保留模式。

+
** 如果物件處於合法保留狀態、則無論物件的保留模式為何、任何人都無法刪除該物件。




.相關資訊
* link:../tenant/creating-s3-bucket.html["建立S3儲存區"]
* link:../tenant/update-default-retention-settings.html["更新 S3 物件鎖定預設保留"]
* link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 來設定 S3 物件鎖定"]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["範例7：S3物件鎖定的符合ILM原則"]

