---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: 雲端儲存資源池可讓您使用 ILM 將物件資料移轉到 StorageGRID 系統之外。例如，您可能想要將不常存取的物件移轉到成本更低的雲端儲存設備，例如 Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud 或 Microsoft Azure Blob Storage 中的封存存取層。或者，您可能想要維護 StorageGRID 物件的雲端備份，以增強災難恢復能力。 
---
= 了解 StorageGRID 中的雲端儲存資源池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
雲端儲存資源池可讓您使用 ILM 將物件資料移轉到 StorageGRID 系統之外。例如，您可能想要將不常存取的物件移轉到成本更低的雲端儲存設備，例如 Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud 或 Microsoft Azure Blob Storage 中的封存存取層。或者，您可能想要維護 StorageGRID 物件的雲端備份，以增強災難恢復能力。

從 ILM 的角度來看，雲端儲存資源池與儲存資源池類似。若要將物件儲存在任一位置，您需要在建立 ILM 規則的放置指令時選擇對應的資源池。但是，儲存資源池由 StorageGRID 系統內的儲存節點組成，而雲端儲存資源池則由外部儲存桶（S3）或 Container（Azure Blob Storage）組成。

下表將儲存資源池與雲端儲存資源池進行比較、並顯示高層級的相似點和差異。

[cols="1a,2a,5a"]
|===
|  | 儲存資源池 | 雲端儲存資源池 


 a| 
如何建立？
 a| 
使用Grid Manager中的* ILM *>* Storage Pools*選項。
 a| 
在 Grid Manager 中使用 *ILM* > * 儲存池 * > * 雲端儲存池 * 選項。

您必須先設定外部儲存區或容器、才能建立雲端儲存資源池。



 a| 
您可以建立多少集區？
 a| 
無限。
 a| 
最多10個。



 a| 
物件儲存在何處？
 a| 
在 StorageGRID 中的一個或多個儲存節點上。
 a| 
在 Amazon S3 儲存桶、Azure Blob Storage Container 或 StorageGRID 系統外部的 Google Cloud 中。

如果雲端儲存資源池是Amazon S3儲存區：

* 您可以選擇性地設定儲存區生命週期、將物件移轉至低成本的長期儲存設備、例如Amazon S3 Glacier或S3 Glacier Deep Archive。外部儲存系統必須支援 Glacier 儲存類別和 S3 RestoreObject API 。
* 您可以建立雲端儲存資源池、以搭配支援AWS Secret Region的AWS商業雲端服務（C2S）使用。


如果雲端儲存資源池是 Azure Blob Storage Container，StorageGRID 會將物件轉換到封存分層。

*附註：* 一般而言，請勿為用於雲端儲存資源池的 Container 設定 Azure Blob Storage 生命週期管理。RestoreObject 對雲端儲存資源池中物件的操作可能會受到已設定生命週期的影響。



 a| 
什麼控制物件放置？
 a| 
使用中 ILM 原則中的 ILM 規則。
 a| 
使用中 ILM 原則中的 ILM 規則。



 a| 
使用哪種資料保護方法？
 a| 
複寫或銷毀編碼。
 a| 
複寫：



 a| 
每個物件允許多少份複本？
 a| 
多重：
 a| 
一份複本放在Cloud Storage Pool中、另有一或多份StorageGRID 複本可選擇放在

* 注意： * 您無法在任何指定時間將物件儲存在多個雲端儲存池中。



 a| 
有哪些優點？
 a| 
物件隨時都能快速存取。
 a| 
低成本儲存。

* 注意 * ： FabricPool 資料無法階層化至雲端儲存資源池。

|===