---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure-coding scheme 
summary: 銷毀編碼方案可控制每個物件所建立的資料片段數量、以及同位元檢查片段數量。 
---
= 什麼是銷毀編碼方案？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
銷毀編碼方案可控制每個物件所建立的資料片段數量、以及同位元檢查片段數量。

當您建立或編輯 ILM 規則時、請選取可用的銷毀編碼配置。StorageGRID 會根據您計畫使用的儲存資源池中有多少個儲存節點和站台、自動建立銷毀編碼方案。



== 資料保護

此系統使用Reed-Solomon銷毀編碼演算法。StorageGRID演算法將物件分成 `k`資料片段、並計算 `m`同位元片段。

這些 `k + m = n`片段分佈在儲存節點之間 `n`、以提供下列資料保護：

* 若要擷取或修復物件、 `k`需要片段。
* 物件可承受最多 `m`遺失或毀損的片段。的值越高 `m`、容錯能力就越高。


最佳的資料保護是由銷毀編碼方案提供、其在儲存資源池中具有最高的節點或磁碟區容錯能力。



== 儲存負荷

擦除編碼方案的儲存負荷是通過將同位檢查片段數除(`m`以計算得出的）(`k`。您可以使用儲存負荷來計算每個銷毀編碼物件所需的磁碟空間：

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

例如、如果您使用4+2配置儲存10 MB物件（儲存負荷為50%）、則物件會耗用15 MB的網格儲存空間。如果您使用6+2方案儲存相同的10 MB物件（其儲存負荷高達33%）、則物件會耗用約13.3MB的空間。

選取符合您需求、總價值最低的銷毀編碼方案 `k+m`。具有較少片段的銷毀編碼方案、在運算上更有效率、因為：

* 每個物件建立和散佈（或擷取）的片段較少
* 由於片段大小較大、因此效能表現較佳
* 它們可能需要在中新增較少的節點link:../expand/index.html["需要更多儲存空間時進行擴充"]




== 儲存資源池準則

當選擇要用於建立銷毀編碼複本規則的儲存池時、請針對儲存池使用下列準則：

* 儲存資源池必須包含三個或多個站台、或只包含一個站台。
+

NOTE: 如果儲存池包含兩個站台、則無法使用抹除編碼。

+
** <<包含三個以上站台之儲存資源池的銷毀編碼配置,包含三個以上站台之儲存資源池的銷毀編碼配置>>
** <<單一站台儲存資源池的銷毀編碼配置,單一站台儲存資源池的銷毀編碼配置>>


* 請勿使用包含 All Sites 網站的儲存池。
* 儲存池至少應包含 `_k+m_ +1`可儲存物件資料的儲存節點。
+

NOTE: 可以在安裝期間配置儲存節點以包含物件資料和元資料（「組合」儲存節點）、僅包含物件元資料或僅包含物件資料。有關詳細信息，請參閱link:../primer/what-storage-node-is.html#types-of-storage-nodes["儲存節點類型"] 。

+
所需的最小儲存節點數為 `k+m`。不過、如果所需的儲存節點暫時無法使用、則至少要有一個額外的儲存節點、有助於防止擷取失敗或ILM待處理項目。





== 包含三個以上站台之儲存資源池的銷毀編碼配置

下表說明StorageGRID 目前由支援的銷毀編碼方案、適用於包含三個以上站台的儲存資源池。所有這些方案都提供站台遺失保護。一個站台可能會遺失、而且物件仍可存取。

對於提供站台遺失保護的銷毀編碼方案、儲存池中建議的儲存節點數量超過 `_k+m_ +1`、因為每個站台至少需要三個儲存節點。

[cols="1a,1a,1a,1a,1a,1a"]
|===
| 銷毀編碼方案（_k+m_） | 已部署站台的最小數量 | 每個站台的建議儲存節點數 | 建議的儲存節點總數 | 站台遺失保護？ | 儲存負荷 


 a| 
4+2.
 a| 
3
 a| 
3
 a| 
9
 a| 
是的
 a| 
50%



 a| 
6+2.
 a| 
4
 a| 
3
 a| 
12
 a| 
是的
 a| 
33%



 a| 
8+2.
 a| 
5
 a| 
3
 a| 
15
 a| 
是的
 a| 
25%



 a| 
6+3.
 a| 
3
 a| 
4
 a| 
12
 a| 
是的
 a| 
50%



 a| 
9+3.
 a| 
4
 a| 
4
 a| 
16
 a| 
是的
 a| 
33%



 a| 
2+1.
 a| 
3
 a| 
3
 a| 
9
 a| 
是的
 a| 
50%



 a| 
4+1.
 a| 
5
 a| 
3
 a| 
15
 a| 
是的
 a| 
25%



 a| 
6+1.
 a| 
7
 a| 
3
 a| 
21
 a| 
是的
 a| 
17%



 a| 
7+5.
 a| 
3
 a| 
5
 a| 
15
 a| 
是的
 a| 
71%

|===

NOTE: 每個站台至少需要三個儲存節點。StorageGRID若要使用7+5方案、每個站台至少需要四個儲存節點。建議每個站台使用五個儲存節點。

選取提供站台保護的銷毀編碼方案時、請平衡下列因素的相對重要性：

* *片段數量*：當片段總數較少時、效能和擴充彈性通常會較佳。
* * 容錯能力 * ：容錯能力會增加、因為同位元區段越多（也就是當值越高時 `m`）。
* * 網路流量 * ：當從故障中恢復時、使用具有更多片段的方案（即、較高的總數） `k+m`會產生更多網路流量。
* *儲存負荷*：成本較高的配置需要更多的每個物件儲存空間。


例如、在4+2方案和6+3方案（兩者都有50%的儲存負荷）之間做出決定時、如果需要額外的容錯能力、請選取6+3方案。如果網路資源受到限制、請選取4+2方案。如果所有其他因素都相同、請選取4+2、因為它的片段總數較少。


NOTE: 如果您不確定要使用哪種方案、請選取4+2或6+3、或聯絡技術支援部門。



== 單一站台儲存資源池的銷毀編碼配置

只要站台有足夠的儲存節點、單一站台儲存池即可支援針對三個以上站台所定義的所有銷毀編碼方案。

所需的儲存節點最小數量為 `k+m`、但建議使用儲存節點的儲存池 `k+m +1`。例如、2+1銷毀編碼方案需要至少三個儲存節點的儲存資源池、但建議使用四個儲存節點。

[cols="1a,1a,1a,1a"]
|===
| 銷毀編碼方案（_k+m_） | 最小儲存節點數 | 建議的儲存節點數 | 儲存負荷 


 a| 
4+2.
 a| 
6
 a| 
7
 a| 
50%



 a| 
6+2.
 a| 
8
 a| 
9
 a| 
33%



 a| 
8+2.
 a| 
10
 a| 
11
 a| 
25%



 a| 
6+3.
 a| 
9
 a| 
10
 a| 
50%



 a| 
9+3.
 a| 
12
 a| 
13
 a| 
33%



 a| 
2+1.
 a| 
3
 a| 
4
 a| 
50%



 a| 
4+1.
 a| 
5
 a| 
6
 a| 
25%



 a| 
6+1.
 a| 
7
 a| 
8
 a| 
17%



 a| 
7+5.
 a| 
12
 a| 
13
 a| 
71%

|===